"""Command-line interface.

A thin face over `core.game.Game`, the same class the API uses. No game logic
lives here.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import sys
import uuid
from datetime import datetime
from pathlib import Path

from ...assets.mirror import PHASES, build
from ...arena.bench import (CATEGORIES, STANDARD_SEEDS, format_result,
                                  run_benchmark)
from ...arena.leaderboard import build_index, format_table, record_result
from ...core.runner import play_run
from ...assets.server import AssetServer
from ...core import render
from ...core.browser import SEED_MAX, normalise_seed
from ...core.game import Game, IllegalAction
from ...stats import format_summary, record, recent, summary

SITE_ROOT = Path(__file__).resolve().parents[4] / "site"

# The state reference is generated into STATE.md between these two lines.
STATE_BEGIN = "<!-- BEGIN state-reference: generated by `pokelike schema --markdown`, do not edit by hand -->"
STATE_END = "<!-- END state-reference -->"
BOTS = Path(__file__).resolve().parents[4] / "bots"

REPL_HELP = """
commands:
  <number>   take the action with that number
  w a b      swap team slots a and b (slot 0 leads; free, does not use the turn)
  s          show the score
  j          show the raw state as JSON
  l          show the legend of map symbols
  n          new run
  q          quit
"""


# --------------------------------------------------------------- credentials
#
# Three flags, on every command that can end up calling a model: --endpoint,
# --api-key and --model. They override the environment; without them nothing
# changes, so `export FW_ENDPOINT=...` keeps working exactly as before and no
# existing script or fork breaks.
#
# A key on the command line is READABLE BY OTHER USERS of the machine, in `ps`,
# and it lands in your shell history. That is a real cost, so `--api-key` also
# accepts `@path`, reads the file and keeps the key out of both. The environment
# and a file are the safe ways; the literal flag is the convenient one.


def add_llm_flags(parser, with_model: bool = True) -> None:
    """The credential flags, worded the same everywhere they appear."""
    g = parser.add_argument_group(
        "model credentials",
        "override FW_ENDPOINT, FW_TOKEN and MODEL_ID without exporting anything",
    )
    g.add_argument("--endpoint", default=None, metavar="URL",
                   help="OpenAI-compatible base URL, no /v1 (overrides $FW_ENDPOINT)")
    g.add_argument("--api-key", dest="api_key", default=None, metavar="KEY",
                   help="the key, or @path to read it from a file (overrides $FW_TOKEN). "
                        "A literal key is visible in `ps` and saved in shell history")
    if with_model:
        g.add_argument("--model", default=None, metavar="ID",
                       help="model id (overrides $MODEL_ID, unless the bot pins one)")


def llm_settings(args) -> dict[str, str]:
    """What was actually given, ready to hand to a bot's constructor.

    Only non-empty values, and that is the whole point: an absent flag must not
    become an empty string, or it would override the environment with nothing and
    turn a working setup into "FW_TOKEN is required".
    """
    out: dict[str, str] = {}
    if getattr(args, "endpoint", None):
        out["endpoint"] = args.endpoint
    if getattr(args, "model", None):
        out["model"] = args.model
    key = getattr(args, "api_key", None)
    if key:
        # @path reads the file, so the key never appears in argv or in history.
        if key.startswith("@"):
            path = Path(key[1:]).expanduser()
            if not path.is_file():
                print(f"no key file at {path}", file=sys.stderr)
                raise SystemExit(2)
            key = path.read_text(encoding="utf-8").strip()
            if not key:
                print(f"{path} is empty", file=sys.stderr)
                raise SystemExit(2)
        out["token"] = key
    return out


def _own_bridge(name: str | None) -> Path | None:
    """A bridge a bot carries, at `<bot>/artifacts/bridge.js`, or None.

    The state is a projection of the game written by hand in `bridge.js`, so a bot
    that needs the engine to give up something nobody thought to expose has nowhere
    else to do it: no `view()` and no tool can invent data the bridge never read.

    In `artifacts/` and not the folder root, because the leaderboard hashes `bot.py`
    plus everything under `artifacts/`. Putting it there makes the score checkable
    for free, and puts the choice in front of anyone reading the submission.

    Resolves the same way `create()` does, so a path and a unique prefix both work.
    Returns None rather than raising: the bot has already been built by the time
    this is called, so a name that does not resolve here is not a new error.
    """
    if not name:
        return None
    try:
        from ...bot import resolve
        from ...bot.catalogue import folder

        base = Path(name) if ("/" in name or "\\" in name) else folder(resolve(name))
        own = base / "artifacts" / "bridge.js"
        return own if own.is_file() else None
    except Exception:  # noqa: BLE001
        return None


def _server_and_game(args) -> tuple[AssetServer, Game]:
    if not SITE_ROOT.is_dir() or not (SITE_ROOT / "index.html").is_file():
        print(
            f"offline copy missing in {SITE_ROOT}\n"
            "run it once with:  pokelike setup",
            file=sys.stderr,
        )
        raise SystemExit(2)
    server = AssetServer(SITE_ROOT, port=args.port)
    server.start()

    watch = getattr(args, "watch", False)
    # With a window open the animations should run at their own speed, otherwise
    # everything flashes past unseen. Headless squashes them to 1 ms because
    # nobody is watching.
    #
    # Which bridge drives the game, in order of precedence.
    #
    # A benchmark run uses the pair frozen beside its harness: every model under a
    # version has to be asked the same question, and the bridge decides what is in
    # the state at all.
    #
    # A bot may carry its own at `bots/<name>/artifacts/bridge.js`. The state is a
    # projection of the game written by hand, so a bot that wants the engine to
    # give up something nobody thought to expose has nowhere else to do it: no
    # `view()` and no tool can invent data the bridge never read. `artifacts/` and
    # not the folder root, because the leaderboard hashes `bot.py` plus everything
    # under `artifacts/`, so putting it there makes the score checkable for free.
    #
    # `init.js` is deliberately NOT overridable by a bot. It pins Math.random and
    # Date.now, and a run's seed is built from both, so a bot supplying its own
    # would play fifty different games while the table said it had played the
    # standard fifty seeds. More information is fair game and is visible in the
    # fingerprint; a different game under the same seed is not.
    #
    # Everything else gets the shared pair, and should: play and bot follow a fix
    # rather than being pinned away from one.
    scripts = {}
    if getattr(args, "harness", None):
        from ...harness import llmbench as _lb
        scripts = _lb.script_paths(args.harness)
    else:
        own = _own_bridge(getattr(args, "bot", None))
        if own is not None:
            scripts = {"bridge": own}
            print(f"bridge: {own}")
    game = Game(url=server.url, watch=watch, max_delay=100_000 if watch else 1,
                **scripts)
    try:
        game.open()
    except Exception as e:  # noqa: BLE001
        server.stop()
        text = str(e)
        if "missing dependencies" in text or "error while loading shared libraries" in text:
            print("cannot start the browser." + MISSING_DEPS_HELP, file=sys.stderr)
            raise SystemExit(3) from e
        if watch:
            print(
                f"cannot open the window: {e}\n\n"
                "--watch needs the full browser, not just the headless shell:\n"
                "    uv run playwright install chromium",
                file=sys.stderr,
            )
            raise SystemExit(3) from e
        raise
    return server, game


# -------------------------------------------------------------------- commands


MISSING_DEPS_HELP = """
The browser downloaded but cannot start: your Linux is missing the system
libraries Chromium needs. This is common on Raspberry Pi, minimal server images
and containers.

Install them, then run `pokelike setup` again:

    sudo apt-get install -y libatk1.0-0t64 libatk-bridge2.0-0t64 libcups2t64 \
        libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 \
        libasound2t64 libatspi2.0-0t64 libpango-1.0-0 libcairo2 libnss3

On older Ubuntu or Debian, drop the `t64` suffixes. Or let Playwright do it:

    sudo $(which python) -m playwright install-deps chromium

Note the `sudo $(which python)`: plain `sudo playwright` usually fails because
the virtualenv is not on root's PATH."""


def browser_works() -> tuple[bool, str]:
    """Actually launches the browser. Downloading it is not the same as running it.

    The Playwright installer exits 0 even when it warns that the host is missing
    libraries, so trusting the exit code makes `setup` claim success and every
    later command fail with a stack trace. Better to find out here.
    """
    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as pw:
            b = pw.chromium.launch(args=["--no-sandbox"])
            b.close()
        return True, ""
    except Exception as e:  # noqa: BLE001
        return False, str(e)


def cmd_setup(args) -> int:
    """Gets everything ready: browser + offline copy. Run once."""
    import subprocess

    print("[1/3] downloading the headless browser (~120 MB)")
    r = subprocess.run(
        [sys.executable, "-m", "playwright", "install", "chromium", "--only-shell"]
    )
    if r.returncode != 0:
        print("browser installation failed", file=sys.stderr)
        return r.returncode

    print("[2/3] checking it actually starts")
    ok, why = browser_works()
    if not ok:
        print("\n  the browser does not start.\n", file=sys.stderr)
        if "missing dependencies" in why or "error while loading shared libraries" in why:
            print(MISSING_DEPS_HELP, file=sys.stderr)
        else:
            print(f"  {why[:600]}", file=sys.stderr)
        return 3
    print("      ok")

    if (SITE_ROOT / "index.html").is_file() and not args.force:
        print(f"[3/3] offline copy already in {SITE_ROOT}, skipping")
        print("      (use --force to rebuild it)")
    else:
        print("[3/3] downloading the game for offline use (~130 MB, a few minutes)")
        build(SITE_ROOT)

    print("\nReady. Try:  pokelike play")
    return 0


def cmd_mirror(args) -> int:
    build(SITE_ROOT, phases=args.phase)
    return 0


def cmd_play(args) -> int:
    server, game = _server_and_game(args)
    try:
        obs = game.reset(seed=args.seed)
        print(f"\nnew run, seed {args.seed}")
        if args.shots:
            print(f"images in {args.shots}/")
        print(REPL_HELP)
        while True:
            print()
            print(render.screen(obs))
            if args.shots:
                f = game.screenshot(Path(args.shots) / f"{game.steps:03d}-{obs['screen']}.png")
                print(f"\n[image: {f}]")
            if obs.get("done"):
                print()
                print(render.score_view(game.score()))
                print("\n('n' for another run, 'q' to quit)")

            try:
                line = input("\n> ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print()
                return 0

            if line in {"q", "quit", "exit"}:
                return 0
            if line == "n":
                args.seed += 1
                obs = game.reset(seed=args.seed)
                print(f"\nnew run, seed {args.seed}")
                continue
            if line == "s":
                print()
                print(render.score_view(game.score()))
                continue
            if line == "j":
                print(json.dumps(game.state(), indent=1, ensure_ascii=False))
                continue
            if line == "l":
                print()
                print(render.LEGEND)
                continue
            if line.startswith("w"):
                bits = line.split()
                if len(bits) != 3 or not all(b.isdigit() for b in bits[1:]):
                    print("usage: w <slot> <slot>, e.g. 'w 0 2'")
                    continue
                try:
                    obs = game.reorder(int(bits[1]), int(bits[2]))
                except IllegalAction as e:
                    print(e)
                continue
            if line in {"?", "h", "help"}:
                print(REPL_HELP)
                continue
            if not line.isdigit():
                print("did not understand: type a number, or '?' for help")
                continue

            try:
                obs = game.step(int(line))
            except IllegalAction as e:
                print(f"action refused: {e}")
    finally:
        game.close()
        server.stop()


def cmd_bot(args) -> int:
    """Runs a bot. The bot decides the moves; this only drives the loop."""
    from ...bot import create

    try:
        bot = create(args.bot, seed=args.seed, **llm_settings(args))
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        raise SystemExit(2) from e
    except TypeError as e:
        print(e.args[0], file=sys.stderr)
        raise SystemExit(2) from e

    # Runs walk the seed forward, so a start that is fine on its own can still
    # run off the end part way through. Better to say so now than to stop after
    # the third of ten runs.
    if args.seed + args.runs > SEED_MAX:
        print(f"seed {args.seed} plus {args.runs} runs goes past the engine's "
              f"limit of {SEED_MAX - 1}: start lower.", file=sys.stderr)
        raise SystemExit(2)

    server, game = _server_and_game(args)
    try:
        for i in range(args.runs):
            seed = args.seed + i

            def each_step(obs, steps, _i=i):
                # Before the decision, so you see the board it was taken on.
                if args.graph and obs.get("map"):
                    print(render.graph_view(obs["map"], colour=sys.stdout.isatty(),
                                            emoji=not args.ascii_map), flush=True)
                if args.shots:
                    game.screenshot(
                        Path(args.shots) / f"{_i:02d}-{steps:03d}-{obs['screen']}.png"
                    )
                if args.watch and steps:
                    game.session.page.wait_for_timeout(args.pause)

            # Streamed rather than printed at the end: a run takes tens of
            # seconds, and watching it decide is the point of asking for a log.
            def each_decision(entry):
                print(render.trace_view([entry], detail=args.detailed), flush=True)

            if args.detailed:
                print(f"\n--- run {i + 1}/{args.runs}, seed {seed} ---", flush=True)

            r = play_run(game, bot, seed, max_steps=args.max_steps, on_step=each_step,
                         on_decision=each_decision if args.detailed else None)

            if args.detailed:
                print(render.ending_view(r["final_state"], game.last_alive,
                                         r["score_detail"]), flush=True)

            if not args.no_stats:
                record(bot=args.bot, seed=seed, state=r["final_state"],
                       score=r["score_detail"], steps=r["steps"], alive=game.last_alive,
                       extra=bot.metadata() if hasattr(bot, "metadata") else None)
            # We print `score` (points without the time bonus) because it is the
            # only comparable one: the time bonus is worth ~1000 on a scale where
            # everything else is in the tens.
            print(
                f"run {i + 1}/{args.runs}  seed {seed}  "
                f"steps {r['steps']:>3}  end {r['ending']:<16} "
                f"badges {r['badges']}  score {r['score']}  "
                f"(KO {r['kos']}, faints {r['faints']}, maps {r['maps']})"
            )
        return 0
    finally:
        game.close()
        server.stop()


def cmd_new_bot(args) -> int:
    """Creates a bot folder that already plays, so it can be measured at once."""
    from ...arena.scaffold import new_bot

    try:
        d = new_bot(args.name, BOTS, llm=args.llm)
    except FileExistsError as e:
        print(e, file=sys.stderr)
        raise SystemExit(2) from e

    rel = d.relative_to(Path.cwd()) if d.is_relative_to(Path.cwd()) else d
    slug = d.name
    print(f"created {rel}/\n")
    if args.llm:
        print("  bot.py        a prompt on the shared LLM harness. Rewrite PROMPT.")
    else:
        print("  bot.py        a bot that already plays. Replace what it does.")
    print("  artifacts/    weights, prompts, tables, whatever yours needs")
    print("  README.md     one line on how it decides\n")
    if args.llm:
        print("Point it at a model, then measure it:\n")
        print('  export FW_ENDPOINT="https://..."   # base URL, no /v1')
        print('  export FW_TOKEN="..."')
        print('  export MODEL_ID="..."')
    else:
        print("Try it, then measure it before you change anything:\n")
    print(f"  uv run pokelike bot run --bot {slug} --runs 5 -d")
    print(f"  uv run pokelike bot bench --bot {slug} --dry-run\n")
    print("The whole path from here to a pull request is in CONTRIBUTING.md.")
    return 0


def cmd_bench(args) -> int:
    """Runs the standard benchmark and writes a submittable result file."""
    from ...bot import LLMBot, create

    try:
        bot = create(args.bot, seed=0, **llm_settings(args))
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        raise SystemExit(2) from e
    except TypeError as e:
        print(e.args[0], file=sys.stderr)
        raise SystemExit(2) from e

    # A path means the bot is being measured where it lives — inside an
    # experiment folder, usually. That is the point: you benchmark what you are
    # working on without moving it. It is never recorded from there; recording
    # is for bots/, reached by the standard procedure.
    from_path = "/" in args.bot or "\\" in args.bot
    display = (Path(args.bot).resolve().parent.name if args.bot.endswith("bot.py")
               else Path(args.bot).resolve().name) if from_path else args.bot

    seeds = STANDARD_SEEDS[: args.runs] if args.runs else STANDARD_SEEDS

    # Whether this ends in a recorded entry is decided here, before the runs, so
    # the notes below can say what will happen instead of what usually happens.
    partial = len(seeds) < len(STANDARD_SEEDS)
    records = not (args.dry_run or partial or from_path)

    # The one place the two benchmarks get mixed up. Both end up as "an LLM playing
    # the game", and nothing on screen said which question was being answered.
    #
    # Asked of the bot, not of --category. Keyed on the category, the note reached
    # only those who had already understood the difference well enough to pass
    # --category llm. Whoever needs it passes nothing and lands in the default.
    if isinstance(bot, LLMBot):
        print("note: this is the BOT competition, where the model is not held\n"
              "  still: your prompt, view and tools are the submission, and the\n"
              "  model is whatever --model or $MODEL_ID names. To measure a MODEL\n"
              "  against a fixed scaffold, that is `pokelike model bench`.\n")
        if records and args.category != "llm":
            print(f"  it would be recorded under category {args.category!r}, which\n"
                  "  is wrong for a bot that calls a model. Add `--category llm`.\n")

    server, game = _server_and_game(args)
    try:
        result = run_benchmark(
            game, bot, bot_name=args.name or display, site=SITE_ROOT, seeds=seeds,
            author=args.author, category=args.category, description=args.description,
        )
    finally:
        game.close()
        server.stop()

    print(format_result(result))

    # A PARTIAL run does not produce an entry, and neither does --dry-run, which
    # is what `records` above already worked out.
    #
    # This used to write one whatever happened, so a `--runs 5` sanity check left
    # a real submission on disk that the next `git add` would pick up. Refusing
    # is not caution, it is the same rule the leaderboard already states: a score
    # over 5 seeds is not comparable to one over 50, so it is not a submission,
    # and something that is not a submission should not be written as one.
    if not records:
        if from_path:
            print(f"\n  nothing recorded (measured from {args.bot}).")
            print("  When it earns its place, bring it into bots/ the standard")
            print("  way: `pokelike bot new`, or copy your bot.py and artifacts.")
            print("  Then bench it there.")
            return 0
        why = ("--dry-run" if args.dry_run
               else f"only {len(seeds)} of the {len(STANDARD_SEEDS)} standard seeds")
        print(f"\n  nothing recorded ({why}).")
        if partial and not args.dry_run:
            print("  run it without --runs to record a result worth comparing.")
        return 0

    # Recorded INTO the bot's own folder, next to the code that earned it, along
    # with whatever it declared in artifacts() and a fingerprint over both. A
    # score and the thing that produced it cannot then drift apart unnoticed.
    if not args.author:
        # The standings have a column for it. Left empty here, it is empty there,
        # and the fix afterwards is another fifty runs.
        print("note: no --author, so the entry will carry an empty one.\n")

    try:
        d = record_result(args.bot, result, bot, BOTS)
    except Exception as e:  # noqa: BLE001 — the runs are the expensive part
        # Fifty runs took minutes; a failure in the last five seconds must not
        # throw them away. Written somewhere plain, with the one command that
        # files it once whatever broke is fixed.
        from ...arena.bench import save
        from ...bot.catalogue import slugify

        rescue = save(result, BOTS / slugify(args.bot) / "result.unrecorded.json")
        print(f"\n  could not record: {type(e).__name__}: {e}", file=sys.stderr)
        print(f"  the {len(seeds)} runs are NOT lost, they are in {rescue}", file=sys.stderr)
        print("  fix the error, then:  uv run pokelike bot board", file=sys.stderr)
        raise SystemExit(1) from e
    build_index(BOTS)

    rel = d.relative_to(Path.cwd()) if d.is_relative_to(Path.cwd()) else d
    print(f"\n  recorded in {rel}/result.json")
    for f in sorted(d.rglob("*")):
        if f.is_file() and "__pycache__" not in f.parts:
            print(f"    {f.relative_to(d)}")
    print("\n  to submit, with origin your fork:")
    print(f"    git checkout -b {result['bot']}")
    print(f"    git add {rel}")
    print(f"    git commit -m 'Add {result['bot']}'")
    print(f"    git push origin {result['bot']}")
    print("    then open the pull request GitHub offers you")
    print("\n  (if you cloned this repo instead of your own fork, origin is not")
    print("   yours to push to: fork it and add that remote first. See CONTRIBUTING.md.)")
    return 0


def cmd_watch(args) -> int:
    """Follows one pass, from the trace it is already writing."""
    from ...harness.watch import dashboard, monitor, overview

    if args.overview:
        return monitor(version=args.harness, every=args.every)
    if args.all:
        return overview(version=args.harness)
    return dashboard(version=args.harness, once=args.once,
                     stamp=args.stamp, model=args.model, every=args.every)


def cmd_llm_bench(args) -> int:
    """Runs one or more models against a frozen harness version."""
    from ...harness import llmbench

    # Asked of both verbs. A version IS the question a row answers, so neither
    # running nor reading can be done without naming one.
    known = llmbench.versions()
    if not args.harness:
        print("--harness is required: it decides which frozen scaffold the model is\n"
              "asked to play, and rows are never compared across versions.\n"
              f"  on disk: {', '.join(known) or 'none'}",
              file=sys.stderr)
        return 2
    if args.harness not in known:
        print(f"no harness {args.harness} here. On disk: "
              f"{', '.join(known) or 'none'}", file=sys.stderr)
        return 2

    if getattr(args, "docker", False):
        return _in_docker(args)

    if args.table:
        # Fetched now, not stored: prices are somebody else's changing fact, and a
        # cost written into a result would be a claim about today made months ago.
        price = llmbench.prices()
        if not price:
            print("  (no price list: offline, so no cost column)", file=sys.stderr)
        # The version asked for, and no other. Printing every version on disk put
        # the table you wanted between tables you did not ask about.
        table = llmbench.format_table(args.harness, price)
        print()
        print(table or f"  nothing measured yet on harness {args.harness}")
        print(f"\n  all versions: {llmbench.write_readme(price)}")
        return 0

    # Only the endpoint and the key: here the model is not a setting for one bot,
    # it is the thing being measured, and it arrives per model in the loop below.
    creds = llm_settings(args)
    creds.pop("model", None)

    try:
        settings = llmbench.parse_settings(args.settings)
    except ValueError as e:
        print(e, file=sys.stderr)
        return 2
    if settings:
        # Asked of the harness before the browser is up and the pre-flight is paid
        # for. Below the `--table` branch and not above it, because `board` has no
        # such flag at all: reading it there raised AttributeError on a command that
        # was only printing a table.
        #
        # The constructor is what decides, and it names what it refused. Nothing
        # here has a list of settings to check against, which is the point: a
        # harness added tomorrow needs no change on this side.
        from ...bot.catalogue import load_class

        try:
            load_class(llmbench.harness_path(args.harness))(
                seed=0, model="x", endpoint="http://x", token="x", **settings)
        except TypeError as e:
            print(f"harness {args.harness}: {e}", file=sys.stderr)
            print(f"  `--set` reaches the harness, and this one does not take "
                  f"what was passed.", file=sys.stderr)
            return 2
        except Exception:  # noqa: BLE001, anything else is not this flag's business
            pass

    models = [m.strip() for m in (args.models or args.model or "").split(",") if m.strip()]
    if not models:
        print("name at least one model: --model openai/gpt-4o-mini", file=sys.stderr)
        raise SystemExit(2)
    try:
        llmbench.harness_path(args.harness)
    except FileNotFoundError as e:
        print(e, file=sys.stderr)
        raise SystemExit(2) from e

    if args.seeds:
        try:
            seeds = parse_seeds(args.seeds)
        except ValueError as e:
            print(e, file=sys.stderr)
            raise SystemExit(2) from e
    else:
        seeds = STANDARD_SEEDS[: args.runs] if args.runs else STANDARD_SEEDS

    # Asked of llmbench rather than compared here: it is the one rule whose
    # failure puts an incomparable row in the table looking exactly like a
    # comparable one, so it lives in one place and has a test.
    partial = not llmbench.records(seeds)

    # Checked here, before the pre-flight spends a token, as well as inside
    # `fan_out` where it cannot be bypassed. A harness that carries the model's
    # notes between runs has no independent runs to hand out: splitting fifty seeds
    # over eight workers gives eight separate notebooks, each covering a fraction of
    # the pass, and the result depends on how the seeds were dealt. It would look
    # like an ordinary row.
    if args.workers > 1 and llmbench.cross_run_memory(args.harness):
        print(f"harness {args.harness} lets the model keep notes between runs, so "
              f"the runs are not independent\nand the pass cannot be split across "
              f"{args.workers} workers. Run it sequentially: drop --workers.",
              file=sys.stderr)
        raise SystemExit(2)

    # Asked once per model, before any seed is played. A model that cannot emit a
    # tool call scores zero over fifty runs and takes half an hour to do it, and
    # the only trace is fallback_rate at 1.0 afterwards. A few hundred tokens now
    # instead of a wasted benchmark later.
    #
    # `preflight` reports rather than raises, deliberately: the harness is a frozen
    # copy with its own exception classes, so there is nothing here that could
    # reliably catch what it throws.
    preflight_said: dict[str, str] = {}
    if not args.no_preflight:
        alive = []
        for model in models:
            p = llmbench.preflight(args.harness, model, **creds)
            preflight_said[model] = ("ready: " + ", ".join(p["tool_calls"])
                                     if p["ok"] else f"skipped: {p.get('why', '')[:200]}")
            if p["ok"]:
                print(f"  {model}: ready (called {', '.join(p['tool_calls'])}, "
                      f"{p['tokens_in']}+{p['tokens_out']} tokens)")
                alive.append(model)
            else:
                print(f"  {model}: SKIPPED ({p.get('why', 'unknown')})",
                      file=sys.stderr)
        if not alive:
            print("\nno model passed the pre-flight; nothing to benchmark",
                  file=sys.stderr)
            raise SystemExit(1)
        models = alive

        # What this is about to cost, before it is spent. The one question a
        # progress bar can never answer and the one worth answering first.
        price = llmbench.prices()
        if price:
            total = 0.0
            for model in models:
                e = llmbench.estimate(args.harness, model,
                                      len(seeds) * args.repeat, price.get(model))
                usd = e["usd"]
                total += usd or 0.0
                print(f"    {model}: ~{e['tokens_in'] / 1e6:.1f}M in / "
                      f"{e['tokens_out'] / 1e6:.2f}M out, "
                      + ("free" if usd == 0 else f"about ${usd:.2f}" if usd
                         else "price unknown"))
            if total:
                print(f"    estimated total: about ${total:.2f} "
                      f"({llmbench.estimate(args.harness, models[0], 1, None)['basis']})")

    # One directory for this whole command: every pass of every model writes its
    # log and its decision trace inside it, so `ls -t` lists your commands and
    # `tail -f <dir>/*.log` follows one of them.
    folder = llmbench.session_dir(args.harness)
    llmbench.record_command(folder, {
        "at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "harness": args.harness,
        "models": models,
        "runs": len(seeds),
        "seeds": seeds,
        "workers": args.workers,
        "repeat": args.repeat,
        "records": not (args.dry_run or partial),
        # What the harness was told beyond the shared flags. Recorded because a pass
        # with a different setting is answering a different question, and the flags
        # were the one thing nothing wrote down before.
        **({"settings": settings} if settings else {}),
        # The endpoint, never the key: which provider served a row changes what the
        # row means, and is worth having later. A token is worth nothing later.
        "endpoint": creds.get("endpoint") or os.environ.get("FW_ENDPOINT") or None,
        "preflight": preflight_said,
    })
    print(f"  writing to {folder}")

    # In parallel each worker owns its own browser and its own server, so the
    # parent starts neither. One at a time still uses this process's game, which
    # keeps a single run cheap to look at.
    server = game = None
    if args.workers <= 1:
        server, game = _server_and_game(args)
    try:
        # Model outer, pass inner. Repeats of one model back to back share the
        # same conditions -- same endpoint load, same hour -- which is what makes
        # the spread between them the model's own variance rather than the
        # provider having a bad afternoon halfway through.
        for model in models:
            for attempt in range(1, args.repeat + 1):
                if args.repeat > 1:
                    print(f"\n  pass {attempt} of {args.repeat}")
                if args.workers > 1:
                    one = llmbench.fan_out(args.harness, model, seeds, args.workers,
                                           SITE_ROOT, port0=args.port + 10,
                                           folder=folder, attempt=attempt,
                                           settings=settings, **creds)
                else:
                    one = llmbench.play_model(game, args.harness, model, SITE_ROOT,
                                              seeds, folder=folder, attempt=attempt,
                                              settings=settings, **creds)
                s = one["summary"]
                print(f"  {model} @ {args.harness}: badges {s.get('badges_mean')} "
                      f"(best {s.get('badges_best')}), "
                      f"{one['tokens_in']:,} in / {one['tokens_out']:,} out tokens, "
                      f"fallback {one['fallback_rate']}, retried {one['retries']}")
                print(f"    log {one.get('log')}")
                print(f"    decisions {one.get('trace')}")
                # Same rule as the main benchmark: a partial run is practice by
                # definition, and --dry-run is how you spend a model's tokens
                # without committing to what came out.
                if args.dry_run or partial:
                    why = "--dry-run" if args.dry_run else f"only {len(seeds)} seeds"
                    print(f"    nothing recorded ({why})")
                    continue
                print(f"    recorded in {llmbench.record(args.harness, model, one)}")
            # Said per model rather than at the end, because with repeats this is
            # the number that decides whether any gap to another model is real,
            # and it is worth seeing before committing to the next model's spend.
            if args.repeat > 1 and not (args.dry_run or partial):
                st = llmbench.stats(
                    json.loads(llmbench.result_path(args.harness, model)
                               .read_text(encoding="utf-8")), args.harness)
                print(f"    {st['passes']} passes: {st['badges_mean']} badges "
                      f"±{st['badges_sem']}, spread across passes "
                      f"{st.get('pass_spread')}")
    finally:
        if game is not None:
            game.close()
        if server is not None:
            server.stop()

    if not (args.dry_run or partial):
        # WITH the price list. Without it every `$` and `$/run` cell is written as a
        # dash, and since this regeneration runs at the end of every recorded pass it
        # would silently wipe the money columns that `--table` had just filled in --
        # which it did, three times, before anyone noticed the two paths disagreed.
        money = llmbench.prices()
        llmbench.write_readme(money)
        table = llmbench.format_table(args.harness, money)
        if table:
            print(f"\n{table}")
    return 0


def _in_docker(args) -> int:
    """Runs this same `model bench` inside the container, and returns.

    Exactly the documented compose command, built here so the flags cannot be got
    wrong: `--build` so the image is never stale, `--rm` so the container removes
    itself when the pass ends, `-d` because a fifty-seed pass outlives the shell.
    Compose, not `docker run`, on purpose: the mounts, the 2 GB /dev/shm and the
    env_file live in the compose file, and duplicating them here would be a second
    copy to keep in step. Behaviour is therefore identical to running it by hand.
    """
    import shutil
    import subprocess

    root = Path(__file__).resolve().parents[4]
    compose = root / "llm-bench" / "docker" / "docker-compose.yml"
    if not compose.exists():
        print(f"no compose file at {compose}", file=sys.stderr)
        return 2
    if not shutil.which("docker"):
        print("docker is not on PATH", file=sys.stderr)
        return 2

    # The pass's own flags, forwarded untouched, minus the ones that describe HOW to
    # launch rather than WHAT to play. `--docker` itself would otherwise recurse.
    passthru: list[str] = []
    for i, a in enumerate(sys.argv[1:]):
        if a in ("--docker",):
            continue
        if a == "--name" or (i and sys.argv[i] == "--name"):
            continue
        passthru.append(a)
    # Drop the leading `model bench` verbs: they are the image's ENTRYPOINT.
    while passthru and passthru[0] in ("model", "bench"):
        passthru.pop(0)

    model = (args.model or args.models or "many").replace("/", "-").replace(":", "-")
    # A short random suffix, for the same reason the pass directory carries one: two
    # passes of the same model on the same harness are a normal thing to want (a
    # --repeat, a second seed range), and without it the second launch dies on a
    # name Docker already holds.
    name = args.name or f"pk_{args.harness}_{model}_{uuid.uuid4().hex[:4]}"

    cmd = ["docker", "compose", "-f", str(compose), "run", "--build", "--rm", "-d",
           "--name", name, "bench", *passthru]
    # Echoed with the key masked. A token on a command line is already visible in
    # `ps` and saved in shell history; printing it as well would put it in whatever
    # log is capturing this. `--api-key @path`, or .env, keeps it out of all three.
    shown, mask = [], False
    for a in cmd:
        shown.append("<redacted>" if mask else a)
        mask = a == "--api-key"
    print("  " + " ".join(shown))
    # COMPOSE_IGNORE_ORPHANS: every pass is its own container in one shared compose
    # project, so the passes already running are not orphans and the warning about
    # them is noise on every launch.
    env = {**os.environ, "COMPOSE_IGNORE_ORPHANS": "true"}
    r = subprocess.run(cmd, cwd=root, env=env)
    if r.returncode == 0:
        print(f"\n  {name} is playing. Follow it with:\n"
              f"    pokelike model watch\n"
              f"    docker logs -f {name}\n"
              f"  It removes itself when the pass ends; `docker stop {name}` ends it early.")
    return r.returncode


def cmd_leaderboard(args) -> int:
    """Rebuilds the index from the entries on disk and prints the table."""
    index = build_index(BOTS)
    print(format_table(index))
    print(f"\n  {len(index['entries'])} measured, in {BOTS}/")
    return 0


def cmd_schema(args) -> int:
    """Prints what a bot receives, captured from a live run."""
    from ...core.schema import as_markdown, capture, describe

    server, game = _server_and_game(args)
    try:
        obs = capture(game)
    finally:
        game.close()
        server.stop()

    if args.json:
        print(json.dumps(obs, indent=1))
    elif args.markdown:
        # Written into STATE.md rather than into the README. It is 420 lines of
        # generated reference, which is longer than everything a reader needs to
        # decide whether the project is for them, and it pushed the rest of the
        # page out of reach.
        out = Path(__file__).resolve().parents[4] / "STATE.md"
        text = out.read_text(encoding="utf-8")
        begin, end = text.find(STATE_BEGIN), text.find(STATE_END)
        if begin < 0 or end < 0:
            print(f"markers not found in {out}: expected\n  {STATE_BEGIN}\n  {STATE_END}",
                  file=sys.stderr)
            return 2
        out.write_text(
            text[:begin] + STATE_BEGIN + "\n" + as_markdown(obs) + "\n" + text[end:],
            encoding="utf-8",
        )
        print(f"state reference written into {out}")
    else:
        print(describe(obs))
    return 0


def cmd_stats(args) -> int:
    print(format_summary(summary(), explain=args.explain))
    if args.recent:
        print()
        for r in recent(args.recent, bot=args.bot):
            print(f"  #{r['id']:<5} {r['played_at']}  {r['bot']:<10} seed {r['seed']:<5}"
                  f" steps {r['steps']:>3}  {r['ending']:<16} score {r['points']}")
    return 0


def cmd_api(args) -> int:
    from ..api.server import serve

    server, game = _server_and_game(args)
    try:
        # A run is ready as soon as the server starts, so GET /state answers
        # right away without having to POST /new first.
        game.reset(seed=args.seed)
        print(f"API on http://127.0.0.1:{args.api_port}/   (ctrl-c to stop)")
        print(f"run ready with seed {args.seed}."
              f"  Try:  curl 127.0.0.1:{args.api_port}/state")
        serve(game, port=args.api_port)
        return 0
    finally:
        game.close()
        server.stop()


# ------------------------------------------------------------------ arguments


def parse_seeds(text: str) -> list[int]:
    """`10010,10011` or `10010-10019`, or both mixed, in the order written.

    Order is kept rather than sorted: under a harness that carries notes between
    runs the order IS part of the measurement, so quietly reordering would change
    what was asked for.
    """
    out: list[int] = []
    for part in text.replace(" ", "").split(","):
        if not part:
            continue
        if "-" in part:
            a, _, b = part.partition("-")
            lo, hi = normalise_seed(int(a)), normalise_seed(int(b))
            if hi < lo:
                raise ValueError(f"--seeds {part}: {b} comes before {a}")
            out += list(range(lo, hi + 1))
        else:
            out.append(normalise_seed(int(part)))
    if not out:
        raise ValueError("--seeds needs at least one seed, e.g. --seeds 10010,10011")
    if len(out) != len(set(out)):
        raise ValueError("--seeds lists the same seed twice; every run has to be a "
                         "different game")
    return out


def seed_arg(value: str) -> int:
    """`--seed` as argparse sees it: refused here rather than after the run.

    The check also lives in `Game.reset`, which is what protects the API and
    anyone using the package as a library. Doing it here as well is what turns
    a traceback into one line, before Chromium has even started.
    """
    try:
        seed = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError(f"'{value}' is not a whole number") from None
    try:
        normalise_seed(seed)
    except ValueError as e:
        raise argparse.ArgumentTypeError(str(e)) from None
    return seed


# ------------------------------------------------------------------ the commands
#
# Two families, because there are two benchmarks in here and they answer different
# questions. Keeping them as `bench` and `llm-bench` at the same level made the
# second read as a special case of the first, which is the opposite of true:
#
#   pokelike bot   ...   your code is the entry, the game is fixed
#   pokelike model ...   the scaffold is fixed, the model is the entry
#
# `bench` appears in both, qualified by the noun, so the word now says what varies
# instead of hiding it. And `pokelike bot bench --harness v3` does not exist, so the
# two cannot be mixed by accident.
#
# The old flat names still work and are not listed: see ALIASES below.

# rich when installed, plain argparse when not. The help has to render in an
# environment where an optional dependency failed to install.
try:
    from rich_argparse import RawDescriptionRichHelpFormatter as _FORMATTER
except ImportError:  # pragma: no cover
    _FORMATTER = argparse.RawDescriptionHelpFormatter


# Three boxes, one per thing this repo does, and every command lives in exactly one.
FAMILIES = (
    ("the game", (
        ("setup", "browser plus an offline copy of the game. Once"),
        ("play", "play it yourself in the terminal"),
        ("api", "drive it over HTTP"),
        ("schema", "what a bot receives: state, actions, node kinds"),
        ("history", "what you have played here"),
        ("mirror", "rebuild the offline copy if it breaks"))),
    ("pokelike bot", (
        ("new", "write a bot folder that already plays"),
        ("run", "play it and watch the decisions"),
        ("bench", "the 50 standard seeds, records a result"),
        ("board", "the standings"))),
    ("pokelike model", (
        ("bench", "a model against one frozen harness version"),
        ("board", "what has been measured, per version"),
        ("watch", "follow a pass while it plays"))),
)

_FAMILY = dict(FAMILIES)   # name -> verbs, for the per-group boxes


def _boxes(families) -> str:
    """One bordered box per family (title + its verbs). Shared by the top-level
    help and by every group screen, so all of them look the same.

    Falls back to plain text rather than failing: `--help` is the one thing that
    must work even where an optional dependency did not install.
    """
    try:
        from rich.console import Console
        from rich.panel import Panel
        from rich.table import Table
    except ImportError:  # pragma: no cover
        out = [""]
        for name, verbs in families:
            out.append(f"{name}:")
            out += [f"  {v:<9}{h}" for v, h in verbs]
            out.append("")
        return "\n".join(out)

    console = Console(width=min(84, Console().width), record=True)
    with console.capture() as cap:
        console.print()
        for name, verbs in families:
            verb_rows = Table.grid(padding=(0, 2))
            verb_rows.add_column(style="bold",
                                 width=max(len(v) for v, _ in verbs) + 1)
            verb_rows.add_column()
            for verb, help_ in verbs:
                verb_rows.add_row(verb, help_)
            console.print(Panel(
                verb_rows,
                title=f"[bold]{name}[/bold]",
                title_align="left", border_style="dim", padding=(0, 1),
            ))
            console.print()
    return cap.get()


def groups_epilog() -> str:
    return _boxes(FAMILIES)


def _bot_run_args(s) -> None:
    s.add_argument("--bot", default="random", help="which bot to play: a folder under bots/")
    s.add_argument("--seed", type=seed_arg, default=1)
    s.add_argument("--runs", type=int, default=3)
    s.add_argument("--max-steps", type=int, default=300)
    s.add_argument("--watch", action="store_true", help="open a real window and watch")
    s.add_argument("--shots", metavar="FOLDER", help="save an image at every step")
    s.add_argument("--pause", type=int, default=800, help="ms between moves with --watch")
    s.add_argument("--no-history", "--no-stats", dest="no_stats", action="store_true",
                   help="do not record the runs")
    s.add_argument("-g", "--graph", action="store_true",
                   help="draw the map before each decision, with where you are on it")
    s.add_argument("--ascii-map", action="store_true",
                   help="draw the map with symbols instead of emoji, for terminals "
                        "whose font has no colour emoji")
    s.add_argument("-d", "--detailed", action="count", default=0,
                   help="one line per decision; -dd adds the bot's reasoning, "
                        "-ddd adds the team")
    add_llm_flags(s)
    s.set_defaults(func=cmd_bot)


def _bot_new_args(s) -> None:
    s.add_argument("name", help="what to call it, e.g. my-bot")
    s.add_argument("--llm", action="store_true",
                   help="start from the shared LLM harness: you write only the prompt")
    s.set_defaults(func=cmd_new_bot)


def _bot_bench_args(s) -> None:
    s.add_argument("--bot", default="random", help="which bot to benchmark")
    s.add_argument("--name", default=None, help="name for the leaderboard (defaults to --bot)")
    s.add_argument("--author", default="", help="your name or github handle")
    s.add_argument("--category", default="other", choices=list(CATEGORIES),
                   help="rules, rl, llm, human or other")
    s.add_argument("--description", default="", help="one line on how it works")
    s.add_argument("--runs", type=int, default=0,
                   help="use only the first N standard seeds. A partial run is a "
                        "practice run: it prints the result and writes no entry")
    s.add_argument("--dry-run", action="store_true",
                   help="play all 50 and print the result, but write no entry")
    add_llm_flags(s)
    s.set_defaults(func=cmd_bench)


def _model_bench_args(s) -> None:
    # No default harness. A version IS the question a row answers, so choosing one
    # silently would let two passes that asked different things look like the same
    # command. Not `required=True` either, because `board` reads every version; the
    # check is in `cmd_llm_bench`, where reading and running are told apart.
    from ...harness import llmbench as _lbv
    s.add_argument("--harness", default=None,
                   help="harness version, one of: "
                        f"{', '.join(_lbv.versions()) or 'none on disk'}. Required")
    s.add_argument("--model", default="", help="model id, e.g. openai/gpt-4o-mini")
    s.add_argument("--models", default="", help="several, comma separated")
    s.add_argument("--workers", type=int, default=1,
                   help="play the seeds in N parallel processes. An LLM run is mostly "
                        "spent waiting on the provider, so this can exceed your core "
                        "count, but watch for rate limits")
    s.add_argument("--repeat", type=int, default=1, metavar="N",
                   help="play the whole seed list N times and record each as a pass. "
                        "The spread between passes is the model's own sampling "
                        "noise, and the only way to know whether a gap to another "
                        "model is bigger than it")
    s.add_argument("--runs", type=int, default=0,
                   help="use only the first N standard seeds. A partial run is a "
                        "practice run: it prints the result and records nothing")
    s.add_argument("--seeds", default="",
                   help="pick the seeds yourself: 10010,10011 or 10010-10019. "
                        "Anything other than the standard 50 records nothing, so "
                        "this is for testing and for running two at once")
    # Whatever one harness understands and the others do not. The flags above are
    # the ones every version needs; this is where a version speaks for itself.
    s.add_argument("--set", action="append", dest="settings", default=[],
                   metavar="KEY=VALUE",
                   help="a setting this harness understands, repeatable. v4 takes "
                        "`--set notes=4` to cap its notebook. A different setting "
                        "is a different question, so it is recorded with the pass")
    s.add_argument("--dry-run", action="store_true",
                   help="play the seeds and print, but record nothing")
    s.add_argument("--docker", action="store_true",
                   help="run this same command inside the container instead of here: "
                        "rebuilds the image, then launches it detached and "
                        "self-removing. Prints the name to watch it by")
    s.add_argument("--name", default="", metavar="NAME",
                   help="container name for --docker. The default, "
                        "pk_<harness>_<model>_<hash>, carries a short random suffix "
                        "so two passes of the same model can run at once")
    s.add_argument("--table", action="store_true", help=argparse.SUPPRESS)
    add_llm_flags(s, with_model=False)
    s.add_argument("--no-preflight", action="store_true",
                   help="skip the one-call check that the model can emit tool calls")
    s.set_defaults(func=cmd_llm_bench)


def _model_watch_args(s) -> None:
    from ...harness import llmbench as _lbv
    # Optional here, unlike on `bench` and `board`. Watching is about what is
    # happening rather than about a question being answered, and with nothing
    # said it follows whichever pass was written to last.
    s.add_argument("--harness", default=None,
                   help="follow a pass of this version, one of: "
                        f"{', '.join(_lbv.versions()) or 'none on disk'}. "
                        "Default: whichever was written to last")
    s.add_argument("--once", action="store_true",
                   help="draw it once and exit, instead of following it")
    s.add_argument("--all", action="store_true",
                   help="every pass on this machine, one row each, instead of "
                        "one pass in detail")
    # Which pass, when more than one is running. Without either, it asks; with
    # nothing to ask (a pipe, a script) it follows the newest and says which.
    s.add_argument("--stamp", default=None, metavar="STAMP",
                   help="the log directory to follow, e.g. 20260820-153310. Part "
                        "of the name is enough")
    s.add_argument("--model", default=None, metavar="ID",
                   help="follow the pass playing this model")
    s.add_argument("-o", "--overview", action="store_true",
                   help="every RUNNING pass at once, each with a live progress bar")
    s.add_argument("--every", type=float, default=2.0, metavar="SECS",
                   help="refresh interval for the live views (default 2س)".replace("س", "s"))
    s.set_defaults(func=cmd_watch)


def _model_board_args(s) -> None:
    from ...harness import llmbench as _lbv
    s.add_argument("--harness", default=None,
                   help="harness version, one of: "
                        f"{', '.join(_lbv.versions()) or 'none on disk'}. Required")
    s.set_defaults(func=cmd_llm_bench, table=True)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="pokelike",
        usage=argparse.SUPPRESS,
        epilog=groups_epilog(),
        formatter_class=_FORMATTER,
        add_help=False,
    )
    p.add_argument("--port", type=int, default=8422, help="port of the game-file server")
    # -h/--help still works, it is just not listed: only --port is worth showing.
    p.add_argument("-h", "--help", action="help", help=argparse.SUPPRESS)
    # The listing is in the epilog, grouped by family, so the brace list is replaced
    # by a placeholder rather than printing eleven names on one line.
    # The listing is the three boxes in the epilog, so argparse's own is suppressed
    # rather than printing the same eight names again with no grouping.
    sub = p.add_subparsers(dest="command", required=False, metavar="<command>",
                           help=argparse.SUPPRESS)

    s = sub.add_parser("setup")
    s.add_argument("--force", action="store_true", help="rebuild the copy even if present")
    s.set_defaults(func=cmd_setup)

    s = sub.add_parser("mirror")
    s.add_argument("--phase", choices=list(PHASES), default="all",
                   help="resume from one phase without downloading everything again")
    s.set_defaults(func=cmd_mirror)

    s = sub.add_parser("play")
    s.add_argument("--seed", type=seed_arg, default=1, help="seed of the run")
    s.add_argument("--watch", action="store_true", help="open a real window and watch")
    s.add_argument("--shots", metavar="FOLDER", help="save an image of every screen")
    s.set_defaults(func=cmd_play)

    s = sub.add_parser("api")
    s.add_argument("--api-port", type=int, default=8423)
    s.add_argument("--seed", type=seed_arg, default=1, help="seed of the initial run")
    s.set_defaults(func=cmd_api)

    # ---- the competition: your code is the entry -------------------------------
    fam = sub.add_parser(
        "bot", usage=argparse.SUPPRESS, add_help=False, formatter_class=_FORMATTER,
        epilog=_boxes([("pokelike bot", _FAMILY["pokelike bot"])]),
    )
    fam.add_argument("-h", "--help", action="help", help=argparse.SUPPRESS)
    bots = fam.add_subparsers(dest="verb", required=False, metavar="<verb>",
                              help=argparse.SUPPRESS)
    fam.set_defaults(func=lambda a, _p=fam: _p.print_help() or 0)
    _bot_new_args(bots.add_parser("new", help="write a bot folder that already plays"))
    _bot_run_args(bots.add_parser("run", help="play it and watch the decisions"))
    _bot_bench_args(bots.add_parser(
        "bench", help="the 50 standard seeds, records a result",
        description="Plays the standard fifty seeds and writes bots/<name>/result.json. "
                    "The scaffold is whatever you wrote, so this ranks ideas.",
    ))
    bots.add_parser("board", help="the standings").set_defaults(func=cmd_leaderboard)

    # ---- the model benchmark: the model is the entry ---------------------------
    fam = sub.add_parser(
        "model", usage=argparse.SUPPRESS, add_help=False, formatter_class=_FORMATTER,
        epilog=_boxes([("pokelike model", _FAMILY["pokelike model"])]),
    )
    fam.add_argument("-h", "--help", action="help", help=argparse.SUPPRESS)
    models = fam.add_subparsers(dest="verb", required=False, metavar="<verb>",
                                help=argparse.SUPPRESS)
    fam.set_defaults(func=lambda a, _p=fam: _p.print_help() or 0)
    _model_bench_args(models.add_parser(
        "bench", help="a model against one frozen harness version"))
    _model_board_args(models.add_parser(
        "board", help="what has been measured, per version"))
    _model_watch_args(models.add_parser(
        "watch", help="follow a pass while it plays",
        description="Redraws what the model is doing from the trace the pass is "
                    "already writing: the runs it has finished, where it is now, "
                    "the tools it called this turn and what it has in memory.",
    ))

    s = sub.add_parser("schema")
    s.add_argument("--json", action="store_true", help="print a real observation instead")
    s.add_argument("--markdown", action="store_true",
                   help="regenerate the state reference inside STATE.md")
    s.set_defaults(func=cmd_schema)

    # `history`, not `stats`: this is what YOU played on this machine, and the
    # name has to stop reading like a sibling of the standings.
    s = sub.add_parser("history")
    s.add_argument("-d", "--explain", action="store_true",
                   help="explain what each column means")
    s.add_argument("--recent", type=int, default=0, help="also show the last N runs")
    s.add_argument("--bot", default=None, help="filter the recent list by bot")
    s.set_defaults(func=cmd_stats)

    args = p.parse_args(list(argv) if argv is not None else sys.argv[1:])

    # Bare `pokelike` (no command) shows the help rather than erroring: the help
    # is the most useful thing to see when you have not said what to do yet.
    if not hasattr(args, "func"):
        p.print_help()
        return 0

    # Graceful exit. Ctrl-C (SIGINT -> KeyboardInterrupt) and `docker stop`
    # (SIGTERM) both unwind cleanly: every command that owns a browser does so
    # through a `with session()`/context manager, whose `__exit__` closes it on
    # the way out. SIGTERM is turned into SystemExit so it travels through that
    # same cleanup instead of killing the process where it stands, and Ctrl-C
    # prints one line rather than a traceback.
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(143))
    try:
        return args.func(args)
    except KeyboardInterrupt:
        print("\ninterrupted.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
