"""Command-line interface.

A thin face over `core.game.Game`, the same class the API uses. No game logic
lives here.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from ...assets.mirror import PHASES, build
from ...bench import CATEGORIES, STANDARD_SEEDS, format_result, run_benchmark
from ...leaderboard import build_index, format_table, record_result
from ...runner import play_run
from ...assets.server import AssetServer
from ...core import render
from ...core.browser import SEED_MAX, normalise_seed
from ...core.game import Game, IllegalAction
from ...stats import format_summary, record, recent, summary

SITE_ROOT = Path(__file__).resolve().parents[4] / "site"

# The state reference is generated into README.md between these two lines.
STATE_BEGIN = "<!-- BEGIN state-reference: generated by `pokelike schema --markdown`, do not edit by hand -->"
STATE_END = "<!-- END state-reference -->"
BOTS = Path(__file__).resolve().parents[4] / "bots"

REPL_HELP = """
commands:
  <number>   take the action with that number
  w a b      swap team slots a and b (slot 0 leads; free, does not use the turn)
  s          show the score
  j          show the raw state as JSON
  l          show the legend of map symbols
  n          new run
  q          quit
"""


def _server_and_game(args) -> tuple[AssetServer, Game]:
    if not SITE_ROOT.is_dir() or not (SITE_ROOT / "index.html").is_file():
        print(
            f"offline copy missing in {SITE_ROOT}\n"
            "run it once with:  pokelike setup",
            file=sys.stderr,
        )
        raise SystemExit(2)
    server = AssetServer(SITE_ROOT, port=args.port)
    server.start()

    watch = getattr(args, "watch", False)
    # With a window open the animations should run at their own speed, otherwise
    # everything flashes past unseen. Headless squashes them to 1 ms because
    # nobody is watching.
    game = Game(url=server.url, watch=watch, max_delay=100_000 if watch else 1)
    try:
        game.open()
    except Exception as e:  # noqa: BLE001
        server.stop()
        text = str(e)
        if "missing dependencies" in text or "error while loading shared libraries" in text:
            print("cannot start the browser." + MISSING_DEPS_HELP, file=sys.stderr)
            raise SystemExit(3) from e
        if watch:
            print(
                f"cannot open the window: {e}\n\n"
                "--watch needs the full browser, not just the headless shell:\n"
                "    uv run playwright install chromium",
                file=sys.stderr,
            )
            raise SystemExit(3) from e
        raise
    return server, game


# -------------------------------------------------------------------- commands


MISSING_DEPS_HELP = """
The browser downloaded but cannot start: your Linux is missing the system
libraries Chromium needs. This is common on Raspberry Pi, minimal server images
and containers.

Install them, then run `pokelike setup` again:

    sudo apt-get install -y libatk1.0-0t64 libatk-bridge2.0-0t64 libcups2t64 \
        libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 \
        libasound2t64 libatspi2.0-0t64 libpango-1.0-0 libcairo2 libnss3

On older Ubuntu or Debian, drop the `t64` suffixes. Or let Playwright do it:

    sudo $(which python) -m playwright install-deps chromium

Note the `sudo $(which python)`: plain `sudo playwright` usually fails because
the virtualenv is not on root's PATH."""


def browser_works() -> tuple[bool, str]:
    """Actually launches the browser. Downloading it is not the same as running it.

    The Playwright installer exits 0 even when it warns that the host is missing
    libraries, so trusting the exit code makes `setup` claim success and every
    later command fail with a stack trace. Better to find out here.
    """
    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as pw:
            b = pw.chromium.launch(args=["--no-sandbox"])
            b.close()
        return True, ""
    except Exception as e:  # noqa: BLE001
        return False, str(e)


def cmd_setup(args) -> int:
    """Gets everything ready: browser + offline copy. Run once."""
    import subprocess

    print("[1/3] downloading the headless browser (~120 MB)")
    r = subprocess.run(
        [sys.executable, "-m", "playwright", "install", "chromium", "--only-shell"]
    )
    if r.returncode != 0:
        print("browser installation failed", file=sys.stderr)
        return r.returncode

    print("[2/3] checking it actually starts")
    ok, why = browser_works()
    if not ok:
        print("\n  the browser does not start.\n", file=sys.stderr)
        if "missing dependencies" in why or "error while loading shared libraries" in why:
            print(MISSING_DEPS_HELP, file=sys.stderr)
        else:
            print(f"  {why[:600]}", file=sys.stderr)
        return 3
    print("      ok")

    if (SITE_ROOT / "index.html").is_file() and not args.force:
        print(f"[3/3] offline copy already in {SITE_ROOT} — skipping")
        print("      (use --force to rebuild it)")
    else:
        print("[3/3] downloading the game for offline use (~130 MB, a few minutes)")
        build(SITE_ROOT)

    print("\nReady. Try:  pokelike play")
    return 0


def cmd_mirror(args) -> int:
    build(SITE_ROOT, phases=args.phase)
    return 0


def cmd_play(args) -> int:
    server, game = _server_and_game(args)
    try:
        obs = game.reset(seed=args.seed)
        print(f"\nnew run — seed {args.seed}")
        if args.shots:
            print(f"images in {args.shots}/")
        print(REPL_HELP)
        while True:
            print()
            print(render.screen(obs))
            if args.shots:
                f = game.screenshot(Path(args.shots) / f"{game.steps:03d}-{obs['screen']}.png")
                print(f"\n[image: {f}]")
            if obs.get("done"):
                print()
                print(render.score_view(game.score()))
                print("\n('n' for another run, 'q' to quit)")

            try:
                line = input("\n> ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print()
                return 0

            if line in {"q", "quit", "exit"}:
                return 0
            if line == "n":
                args.seed += 1
                obs = game.reset(seed=args.seed)
                print(f"\nnew run — seed {args.seed}")
                continue
            if line == "s":
                print()
                print(render.score_view(game.score()))
                continue
            if line == "j":
                print(json.dumps(game.state(), indent=1, ensure_ascii=False))
                continue
            if line == "l":
                print()
                print(render.LEGEND)
                continue
            if line.startswith("w"):
                bits = line.split()
                if len(bits) != 3 or not all(b.isdigit() for b in bits[1:]):
                    print("usage: w <slot> <slot>, e.g. 'w 0 2'")
                    continue
                try:
                    obs = game.reorder(int(bits[1]), int(bits[2]))
                except IllegalAction as e:
                    print(e)
                continue
            if line in {"?", "h", "help"}:
                print(REPL_HELP)
                continue
            if not line.isdigit():
                print("did not understand — type a number, or '?' for help")
                continue

            try:
                obs = game.step(int(line))
            except IllegalAction as e:
                print(f"action refused: {e}")
    finally:
        game.close()
        server.stop()


def cmd_bot(args) -> int:
    """Runs a bot. The bot decides the moves; this only drives the loop."""
    from ...bot import create

    try:
        bot = create(args.bot, seed=args.seed)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        raise SystemExit(2) from e

    # Runs walk the seed forward, so a start that is fine on its own can still
    # run off the end part way through. Better to say so now than to stop after
    # the third of ten runs.
    if args.seed + args.runs > SEED_MAX:
        print(f"seed {args.seed} plus {args.runs} runs goes past the engine's "
              f"limit of {SEED_MAX - 1}: start lower.", file=sys.stderr)
        raise SystemExit(2)

    server, game = _server_and_game(args)
    try:
        for i in range(args.runs):
            seed = args.seed + i

            def each_step(obs, steps, _i=i):
                # Before the decision, so you see the board it was taken on.
                if args.graph and obs.get("map"):
                    print(render.graph_view(obs["map"], colour=sys.stdout.isatty(),
                                            emoji=not args.ascii_map), flush=True)
                if args.shots:
                    game.screenshot(
                        Path(args.shots) / f"{_i:02d}-{steps:03d}-{obs['screen']}.png"
                    )
                if args.watch and steps:
                    game.session.page.wait_for_timeout(args.pause)

            # Streamed rather than printed at the end: a run takes tens of
            # seconds, and watching it decide is the point of asking for a log.
            def each_decision(entry):
                print(render.trace_view([entry], detail=args.detailed), flush=True)

            if args.detailed:
                print(f"\n--- run {i + 1}/{args.runs}, seed {seed} ---", flush=True)

            r = play_run(game, bot, seed, max_steps=args.max_steps, on_step=each_step,
                         on_decision=each_decision if args.detailed else None)

            if args.detailed:
                print(render.ending_view(r["final_state"], game.last_alive,
                                         r["score_detail"]), flush=True)

            if not args.no_stats:
                record(bot=args.bot, seed=seed, state=r["final_state"],
                       score=r["score_detail"], steps=r["steps"], alive=game.last_alive,
                       extra=bot.notes() if hasattr(bot, "notes") else None)
            # We print `score` (points without the time bonus) because it is the
            # only comparable one: the time bonus is worth ~1000 on a scale where
            # everything else is in the tens.
            print(
                f"run {i + 1}/{args.runs}  seed {seed}  "
                f"steps {r['steps']:>3}  end {r['ending']:<16} "
                f"badges {r['badges']}  score {r['score']}  "
                f"(KO {r['kos']}, faints {r['faints']}, maps {r['maps']})"
            )
        return 0
    finally:
        game.close()
        server.stop()


def cmd_new_bot(args) -> int:
    """Creates a bot folder that already plays, so it can be measured at once."""
    from ...scaffold import new_bot

    try:
        d = new_bot(args.name, BOTS, llm=args.llm)
    except FileExistsError as e:
        print(e, file=sys.stderr)
        raise SystemExit(2) from e

    rel = d.relative_to(Path.cwd()) if d.is_relative_to(Path.cwd()) else d
    slug = d.name
    print(f"created {rel}/\n")
    if args.llm:
        print("  bot.py        a prompt on the shared LLM harness. Rewrite PROMPT.")
    else:
        print("  bot.py        a bot that already plays. Replace what it does.")
    print("  artifacts/    weights, prompts, tables — whatever yours needs")
    print("  README.md     one line on how it decides\n")
    if args.llm:
        print("Point it at a model, then measure it:\n")
        print('  export FW_ENDPOINT="https://..."   # base URL, no /v1')
        print('  export FW_TOKEN="..."')
        print('  export MODEL_ID="..."')
    else:
        print("Try it, then measure it before you change anything:\n")
    print(f"  uv run pokelike bot --bot {slug} --runs 5 -d")
    print(f"  uv run pokelike bench --bot {slug} --dry-run\n")
    print("The whole path from here to a pull request is in GUIDE.md.")
    return 0


def cmd_bench(args) -> int:
    """Runs the standard benchmark and writes a submittable result file."""
    from ...bot import create

    try:
        bot = create(args.bot, seed=0)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        raise SystemExit(2) from e

    # A path means the bot is being measured where it lives — inside an
    # experiment folder, usually. That is the point: you benchmark what you are
    # working on without moving it. It is never recorded from there; recording
    # is for bots/, reached by the standard procedure.
    from_path = "/" in args.bot or "\\" in args.bot
    display = (Path(args.bot).resolve().parent.name if args.bot.endswith("bot.py")
               else Path(args.bot).resolve().name) if from_path else args.bot

    seeds = STANDARD_SEEDS[: args.runs] if args.runs else STANDARD_SEEDS
    server, game = _server_and_game(args)
    try:
        result = run_benchmark(
            game, bot, bot_name=args.name or display, site=SITE_ROOT, seeds=seeds,
            author=args.author, category=args.category, description=args.description,
        )
    finally:
        game.close()
        server.stop()

    print(format_result(result))

    # A PARTIAL run does not produce an entry, and neither does --dry-run.
    #
    # This used to write one whatever happened, so a `--runs 5` sanity check left
    # a real submission on disk that the next `git add` would pick up. Refusing
    # is not caution, it is the same rule the leaderboard already states: a score
    # over 5 seeds is not comparable to one over 50, so it is not a submission,
    # and something that is not a submission should not be written as one.
    partial = len(seeds) < len(STANDARD_SEEDS)
    if args.dry_run or partial or from_path:
        if from_path:
            print(f"\n  nothing recorded (measured from {args.bot}).")
            print("  When it earns its place: bring it into bots/ the standard way —")
            print("  new-bot, or copy your bot.py and artifacts — then bench it there.")
            return 0
        why = ("--dry-run" if args.dry_run
               else f"only {len(seeds)} of the {len(STANDARD_SEEDS)} standard seeds")
        print(f"\n  nothing recorded ({why}).")
        if partial and not args.dry_run:
            print("  run it without --runs to record a result worth comparing.")
        return 0

    # Recorded INTO the bot's own folder, next to the code that earned it, along
    # with whatever it declared in artifacts() and a fingerprint over both. A
    # score and the thing that produced it cannot then drift apart unnoticed.
    try:
        d = record_result(args.bot, result, bot, BOTS)
    except Exception as e:  # noqa: BLE001 — the runs are the expensive part
        # Fifty runs took minutes; a failure in the last five seconds must not
        # throw them away. Written somewhere plain, with the one command that
        # files it once whatever broke is fixed.
        from ...bench import save
        from ...bot.catalogue import slugify

        rescue = save(result, BOTS / slugify(args.bot) / "result.unrecorded.json")
        print(f"\n  could not record: {type(e).__name__}: {e}", file=sys.stderr)
        print(f"  the {len(seeds)} runs are NOT lost, they are in {rescue}", file=sys.stderr)
        print("  fix the error, then:  uv run pokelike leaderboard", file=sys.stderr)
        raise SystemExit(1) from e
    build_index(BOTS)

    rel = d.relative_to(Path.cwd()) if d.is_relative_to(Path.cwd()) else d
    print(f"\n  recorded in {rel}/result.json")
    for f in sorted(d.rglob("*")):
        if f.is_file() and "__pycache__" not in f.parts:
            print(f"    {f.relative_to(d)}")
    print("\n  to submit — origin is your fork, so:")
    print(f"    git checkout -b {result['bot']}")
    print(f"    git add {rel}")
    print(f"    git commit -m 'Add {result['bot']}'")
    print(f"    git push origin {result['bot']}")
    print("    then open the pull request GitHub offers you")
    print("\n  (if you cloned this repo instead of your own fork, origin is not")
    print("   yours to push to — fork it and add that remote first. See GUIDE.md.)")
    return 0


def cmd_llm_bench(args) -> int:
    """Runs one or more models against a frozen harness version."""
    from ... import llmbench

    if args.table:
        # Fetched now, not stored: prices are somebody else's changing fact, and a
        # cost written into a result would be a claim about today made months ago.
        price = llmbench.prices()
        if not price:
            print("  (no price list: offline, so no cost column)", file=sys.stderr)
        for v in reversed(llmbench.versions()):
            print()
            print(llmbench.format_table(v, price))
        print(f"\n  table written to {llmbench.write_readme(price)}")
        return 0

    models = [m.strip() for m in (args.models or args.model or "").split(",") if m.strip()]
    if not models:
        print("name at least one model: --model openai/gpt-4o-mini", file=sys.stderr)
        raise SystemExit(2)
    try:
        llmbench.harness_path(args.harness)
    except FileNotFoundError as e:
        print(e, file=sys.stderr)
        raise SystemExit(2) from e

    seeds = STANDARD_SEEDS[: args.runs] if args.runs else STANDARD_SEEDS
    partial = len(seeds) < len(STANDARD_SEEDS)

    # Asked once per model, before any seed is played. A model that cannot emit a
    # tool call scores zero over fifty runs and takes half an hour to do it, and
    # the only trace is fallback_rate at 1.0 afterwards. A few hundred tokens now
    # instead of a wasted benchmark later.
    #
    # `preflight` reports rather than raises, deliberately: the harness is a frozen
    # copy with its own exception classes, so there is nothing here that could
    # reliably catch what it throws.
    if not args.no_preflight:
        alive = []
        for model in models:
            p = llmbench.preflight(args.harness, model)
            if p["ok"]:
                print(f"  {model}: ready (called {', '.join(p['tool_calls'])}, "
                      f"{p['tokens_in']}+{p['tokens_out']} tokens)")
                alive.append(model)
            else:
                print(f"  {model}: SKIPPED — {p.get('why', 'unknown')}",
                      file=sys.stderr)
        if not alive:
            print("\nno model passed the pre-flight; nothing to benchmark",
                  file=sys.stderr)
            raise SystemExit(1)
        models = alive

        # What this is about to cost, before it is spent. The one question a
        # progress bar can never answer and the one worth answering first.
        price = llmbench.prices()
        if price:
            total = 0.0
            for model in models:
                e = llmbench.estimate(args.harness, model,
                                      len(seeds) * args.repeat, price.get(model))
                usd = e["usd"]
                total += usd or 0.0
                print(f"    {model}: ~{e['tokens_in'] / 1e6:.1f}M in / "
                      f"{e['tokens_out'] / 1e6:.2f}M out, "
                      + ("free" if usd == 0 else f"about ${usd:.2f}" if usd
                         else "price unknown"))
            if total:
                print(f"    estimated total: about ${total:.2f} "
                      f"({llmbench.estimate(args.harness, models[0], 1, None)['basis']})")

    # In parallel each worker owns its own browser and its own server, so the
    # parent starts neither. One at a time still uses this process's game, which
    # keeps a single run cheap to look at.
    server = game = None
    if args.workers <= 1:
        server, game = _server_and_game(args)
    try:
        # Model outer, pass inner. Repeats of one model back to back share the
        # same conditions -- same endpoint load, same hour -- which is what makes
        # the spread between them the model's own variance rather than the
        # provider having a bad afternoon halfway through.
        for model in models:
            for attempt in range(1, args.repeat + 1):
                if args.repeat > 1:
                    print(f"\n  pass {attempt} of {args.repeat}")
                if args.workers > 1:
                    one = llmbench.fan_out(args.harness, model, seeds, args.workers,
                                           SITE_ROOT, port0=args.port + 10)
                else:
                    one = llmbench.play_model(game, args.harness, model, SITE_ROOT,
                                              seeds)
                s = one["summary"]
                print(f"  {model} @ {args.harness}: badges {s.get('badges_mean')} "
                      f"(best {s.get('badges_best')}), "
                      f"{one['tokens_in']:,} in / {one['tokens_out']:,} out tokens, "
                      f"fallback {one['fallback_rate']}, retried {one['retries']}")
                print(f"    log {one.get('log')}")
                # Same rule as the main benchmark: a partial run is practice by
                # definition, and --dry-run is how you spend a model's tokens
                # without committing to what came out.
                if args.dry_run or partial:
                    why = "--dry-run" if args.dry_run else f"only {len(seeds)} seeds"
                    print(f"    nothing recorded ({why})")
                    continue
                print(f"    recorded in {llmbench.record(args.harness, model, one)}")
            # Said per model rather than at the end, because with repeats this is
            # the number that decides whether any gap to another model is real,
            # and it is worth seeing before committing to the next model's spend.
            if args.repeat > 1 and not (args.dry_run or partial):
                st = llmbench.stats(
                    json.loads(llmbench.result_path(args.harness, model)
                               .read_text(encoding="utf-8")), args.harness)
                print(f"    {st['passes']} passes: {st['badges_mean']} badges "
                      f"±{st['badges_sem']}, spread across passes "
                      f"{st.get('pass_spread')}")
    finally:
        if game is not None:
            game.close()
        if server is not None:
            server.stop()

    if not (args.dry_run or partial):
        llmbench.write_readme()
        print(f"\n{llmbench.format_table(args.harness)}")
    return 0


def cmd_leaderboard(args) -> int:
    """Rebuilds the index from the entries on disk and prints the table."""
    index = build_index(BOTS)
    print(format_table(index))
    print(f"\n  {len(index['entries'])} measured, in {BOTS}/")
    return 0


def cmd_schema(args) -> int:
    """Prints what a bot receives, captured from a live run."""
    from ...schema import as_markdown, capture, describe

    server, game = _server_and_game(args)
    try:
        obs = capture(game)
    finally:
        game.close()
        server.stop()

    if args.json:
        print(json.dumps(obs, indent=1))
    elif args.markdown:
        # Written INTO the README rather than to a file of its own. A separate
        # reference is a file nobody opens; the point of generating it was that
        # it cannot drift, and that property is worth more where people read.
        out = Path(__file__).resolve().parents[4] / "README.md"
        text = out.read_text(encoding="utf-8")
        begin, end = text.find(STATE_BEGIN), text.find(STATE_END)
        if begin < 0 or end < 0:
            print(f"markers not found in {out}: expected\n  {STATE_BEGIN}\n  {STATE_END}",
                  file=sys.stderr)
            return 2
        out.write_text(
            text[:begin] + STATE_BEGIN + "\n" + as_markdown(obs) + "\n" + text[end:],
            encoding="utf-8",
        )
        print(f"state reference written into {out}")
    else:
        print(describe(obs))
    return 0


def cmd_stats(args) -> int:
    print(format_summary(summary(), explain=args.explain))
    if args.recent:
        print()
        for r in recent(args.recent, bot=args.bot):
            print(f"  #{r['id']:<5} {r['played_at']}  {r['bot']:<10} seed {r['seed']:<5}"
                  f" steps {r['steps']:>3}  {r['ending']:<16} score {r['points']}")
    return 0


def cmd_api(args) -> int:
    from ..api.server import serve

    server, game = _server_and_game(args)
    try:
        # A run is ready as soon as the server starts, so GET /state answers
        # right away without having to POST /new first.
        game.reset(seed=args.seed)
        print(f"API on http://127.0.0.1:{args.api_port}/   (ctrl-c to stop)")
        print(f"run ready with seed {args.seed} — try: curl 127.0.0.1:{args.api_port}/state")
        serve(game, port=args.api_port)
        return 0
    finally:
        game.close()
        server.stop()


# ------------------------------------------------------------------ arguments


def seed_arg(value: str) -> int:
    """`--seed` as argparse sees it: refused here rather than after the run.

    The check also lives in `Game.reset`, which is what protects the API and
    anyone using the package as a library. Doing it here as well is what turns
    a traceback into one line, before Chromium has even started.
    """
    try:
        seed = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError(f"'{value}' is not a whole number") from None
    try:
        normalise_seed(seed)
    except ValueError as e:
        raise argparse.ArgumentTypeError(str(e)) from None
    return seed


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="pokelike",
        description="Play pokelike.xyz headless, from the command line or over HTTP.",
    )
    p.add_argument("--port", type=int, default=8422, help="port of the game-file server")
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("setup", help="get everything ready: browser + offline copy (run once)")
    s.add_argument("--force", action="store_true", help="rebuild the copy even if present")
    s.set_defaults(func=cmd_setup)

    s = sub.add_parser("mirror", help="rebuild only the offline copy of the game")
    s.add_argument("--phase", choices=list(PHASES), default="all",
                   help="resume from one phase without downloading everything again")
    s.set_defaults(func=cmd_mirror)

    s = sub.add_parser("play", help="interactive run in the terminal")
    s.add_argument("--seed", type=seed_arg, default=1, help="seed of the run")
    s.add_argument("--watch", action="store_true", help="open a real window and watch")
    s.add_argument("--shots", metavar="FOLDER", help="save an image of every screen")
    s.set_defaults(func=cmd_play)

    s = sub.add_parser("bot", help="run a bot")
    s.add_argument("--bot", default="random", help="which bot to play: a folder under bots/")
    s.add_argument("--seed", type=seed_arg, default=1)
    s.add_argument("--runs", type=int, default=3)
    s.add_argument("--max-steps", type=int, default=300)
    s.add_argument("--watch", action="store_true", help="open a real window and watch")
    s.add_argument("--shots", metavar="FOLDER", help="save an image at every step")
    s.add_argument("--pause", type=int, default=800, help="ms between moves with --watch")
    s.add_argument("--no-history", "--no-stats", dest="no_stats", action="store_true",
                   help="do not record the runs")
    s.add_argument("-g", "--graph", action="store_true",
                   help="draw the map before each decision, with where you are on it")
    s.add_argument("--ascii-map", action="store_true",
                   help="draw the map with symbols instead of emoji, for terminals "
                        "whose font has no colour emoji")
    s.add_argument("-d", "--detailed", action="count", default=0,
                   help="one line per decision; -dd adds the bot's reasoning, "
                        "-ddd adds the team")
    s.set_defaults(func=cmd_bot)

    s = sub.add_parser("api", help="start the HTTP API")
    s.add_argument("--api-port", type=int, default=8423)
    s.add_argument("--seed", type=seed_arg, default=1, help="seed of the initial run")
    s.set_defaults(func=cmd_api)

    s = sub.add_parser("new-bot", help="create a new bot folder under bots/")
    s.add_argument("name", help="what to call it, e.g. my-bot")
    s.add_argument("--llm", action="store_true",
                   help="start from the shared LLM harness: you write only the prompt")
    s.set_defaults(func=cmd_new_bot)

    s = sub.add_parser("bench", help="run the standard benchmark and produce a result file")
    s.add_argument("--bot", default="random", help="which bot to benchmark")
    s.add_argument("--name", default=None, help="name for the leaderboard (defaults to --bot)")
    s.add_argument("--author", default="", help="your name or github handle")
    s.add_argument("--category", default="other", choices=list(CATEGORIES),
                   help="rules, rl, llm, human or other")
    s.add_argument("--description", default="", help="one line on how it works")
    s.add_argument("--runs", type=int, default=0,
                   help="use only the first N standard seeds. A partial run is a "
                        "practice run: it prints the result and writes no entry")
    s.add_argument("--dry-run", action="store_true",
                   help="play all 50 and print the result, but write no entry")
    s.set_defaults(func=cmd_bench)

    s = sub.add_parser("leaderboard", help="rebuild and print the leaderboard table")
    s.set_defaults(func=cmd_leaderboard)

    # A different question from `bench`, which is why it is a different command.
    # There the prompt is the submission; here the harness is frozen and the model
    # is the only thing that varies, so a row says something about the model.
    s = sub.add_parser("llm-bench", help="run models against a frozen LLM harness")
    s.add_argument("--harness", default="v0", help="harness version, e.g. v0")
    s.add_argument("--model", default="", help="model id, e.g. openai/gpt-4o-mini")
    s.add_argument("--models", default="", help="several, comma separated")
    s.add_argument("--workers", type=int, default=1,
                   help="play the seeds in N parallel processes. An LLM run is mostly "
                        "spent waiting on the provider, so this can exceed your core "
                        "count — but watch for rate limits")
    s.add_argument("--repeat", type=int, default=1, metavar="N",
                   help="play the whole seed list N times and record each as a pass. "
                        "The spread between passes is the model's own sampling "
                        "noise, and the only way to know whether a gap to another "
                        "model is bigger than it")
    s.add_argument("--runs", type=int, default=0,
                   help="use only the first N standard seeds. A partial run is a "
                        "practice run: it prints the result and records nothing")
    s.add_argument("--dry-run", action="store_true",
                   help="play the seeds and print, but record nothing")
    s.add_argument("--table", action="store_true",
                   help="print what is recorded and regenerate llm-bench/README.md")
    s.add_argument("--no-preflight", action="store_true",
                   help="skip the one-call check that the model can emit tool calls")
    s.set_defaults(func=cmd_llm_bench)

    s = sub.add_parser("schema", help="what a bot receives: state, actions, node kinds")
    s.add_argument("--json", action="store_true", help="print a real observation instead")
    s.add_argument("--markdown", action="store_true",
                   help="regenerate the state reference inside README.md")
    s.set_defaults(func=cmd_schema)

    # `history`, not `stats`: this is what YOU played on this machine, and the
    # name has to stop reading like a sibling of `leaderboard`. `stats` stays as
    # an alias so anything already typed or scripted keeps working.
    s = sub.add_parser("history", aliases=["stats"],
                       help="what you have played on this machine (not comparable)")
    s.add_argument("-d", "--explain", action="store_true",
                   help="explain what each column means")
    s.add_argument("--recent", type=int, default=0, help="also show the last N runs")
    s.add_argument("--bot", default=None, help="filter the recent list by bot")
    s.set_defaults(func=cmd_stats)

    args = p.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
