"""The model benchmark: one frozen harness, many models.

    uv run pokelike llm-bench --harness v0 --model openai/gpt-4o-mini

Different question from `bots/`. There, the prompt and the tools are the
submission and the model is usually whatever `$MODEL_ID` names — the leaderboard
ranks ideas. Here the harness is held still on purpose and the MODEL is the only
thing that moves, so a row says something about the model rather than about who
tuned their scaffold hardest.

The two feed each other in one direction. Ideas are discovered in `bots/`, where
anyone may change anything and the badge count decides whether it was a good
idea. When one earns it, it is folded into a NEW harness version here. Nothing
flows the other way, and nothing arrives from outside.

WHY THE VERSION IS A DIRECTORY. `llm-bench/v0/harness/bot.py` holds the harness
and `llm-bench/v0/results/` holds what was measured under it. Results live inside
the version rather than beside it so that pairing them wrongly is not a mistake
available to anyone. A harness improvement is `v1/`, a new directory; v0's rows
stay valid where they were earned and are never ranked against v1's, because two
models asked different questions were not compared.

WHAT IS RECORDED, AND WHAT IS NOT. Token counts in and out, per run, never money.
Prices change and a measurement should not rot because a provider ran a promotion,
so cost stays a function of these counts applied whenever it is asked for — from
OpenRouter's model list, at query time.

WHY PASSES AND NOT ONE NUMBER. An LLM run is not reproducible: same seed, same
prompt, different answer. So a model is measured more than once and every pass is
kept in full. Repeats over a FIXED seed list separate the two noise sources —
seed luck is already inside each pass's mean, so the spread ACROSS passes is the
model's own sampling noise. Without that, this benchmark would confidently rank
gaps it cannot resolve, which is the failure the `bots/` table has already been
caught committing over fifty seeds.
"""

from __future__ import annotations

import hashlib
import json
import statistics
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .bench import STANDARD_SEEDS, _tok, progress_bar, run_benchmark, summarise

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "llm-bench"
RENDER = Path(__file__).resolve().parent / "core" / "render.py"

# How many runs at each end of a pass make up the learning comparison. Ten of
# fifty: long enough to average out a lucky seed, short enough that the two
# ends are actually early and late rather than two halves of the same curve.
LEARN_K = 10

README_BEGIN = "<!-- BEGIN llm-bench: generated by `pokelike llm-bench --table`, do not edit by hand -->"
README_END = "<!-- END llm-bench -->"


def versions() -> list[str]:
    """Harness versions on disk, oldest first."""
    if not BENCH.is_dir():
        return []
    found = [d.name for d in BENCH.iterdir()
             if d.is_dir() and (d / "harness" / "bot.py").is_file()]
    return sorted(found, key=lambda v: int(v.lstrip("v") or 0))


def harness_path(version: str) -> Path:
    p = BENCH / version / "harness" / "bot.py"
    if not p.is_file():
        have = ", ".join(versions()) or "none"
        raise FileNotFoundError(f"no harness at {p} (versions on disk: {have})")
    return p


def slug(model: str) -> str:
    """A model id as a filename. `openai/gpt-4o-mini` -> `openai--gpt-4o-mini`."""
    return model.replace("/", "--").replace(":", "-").replace(" ", "-")


def fingerprints(version: str) -> dict[str, str]:
    """What the measurement actually depended on.

    The harness, and the render module it renders the state with. The second one
    is not frozen — it is shared with the CLI — so it is fingerprinted instead:
    change it and every row that used it is marked rather than quietly meaning
    something new. See the header of the harness file.
    """
    sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()[:16]  # noqa: E731
    return {"bot.py": sha(harness_path(version)), "render.py": sha(RENDER)}


def cross_run_memory(version: str) -> bool:
    """Whether this harness lets the model carry notes from one run into the next.

    Asked of the harness rather than hardcoded here, because the harness is the
    thing that knows: v1 declares `CROSS_RUN_MEMORY = True`, and a future version
    that drops the idea says so by not declaring it. Nothing in this file has to
    be edited when a version is added.

    Reading it means importing the harness module, which is cheap and needs no
    credentials — the class is only inspected, never constructed.
    """
    from .bot.catalogue import load_class

    return bool(getattr(load_class(harness_path(version)), "CROSS_RUN_MEMORY", False))


def prices(url: str = "https://openrouter.ai/api/v1/models",
           timeout: float = 10.0) -> dict[str, dict[str, float]]:
    """Per-token USD prices, keyed by model id. Fetched, never stored.

    A public endpoint: no key, so this works whatever provider a run actually
    used. OpenRouter quotes per TOKEN as strings — `"0.00000015"` — and a free
    model is exactly `"0"`, which is why the column can legitimately read 0.

    Returns an empty dict rather than raising when there is no network. Cost is a
    convenience on top of the measurement, and a table that refuses to print
    because a price list was unreachable would have its priorities backwards.
    """
    import urllib.request

    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            data = json.loads(r.read()).get("data") or []
    except Exception:  # noqa: BLE001 — offline is a normal state, not an error
        return {}
    out: dict[str, dict[str, float]] = {}
    for m in data:
        p = m.get("pricing") or {}
        try:
            out[m["id"]] = {"in": float(p.get("prompt") or 0),
                            "out": float(p.get("completion") or 0)}
        except (TypeError, ValueError):
            continue
    return out


def cost(tokens_in: int, tokens_out: int, price: dict[str, float] | None) -> float | None:
    """USD for tokens already counted, at prices supplied from outside.

    Kept as a function of the two counts rather than a field in the result, and
    that is the whole point: prices are somebody else's changing fact. A cost
    written into a result would be a claim about what today costs, made months
    ago, that nobody can correct without re-running a benchmark that has not
    changed. The tokens are the measurement; money is a view of it.
    """
    if not price:
        return None
    return tokens_in * price.get("in", 0.0) + tokens_out * price.get("out", 0.0)


# Tokens a single run spends, when nothing has been recorded yet to look at.
# Only used to answer "what will this cost me" BEFORE the first pass exists; once
# one does, the real numbers replace it.
TYPICAL_RUN = (30_000, 1_600)


def estimate(version: str, model: str, n_runs: int,
             price: dict[str, float] | None) -> dict[str, Any]:
    """What a sweep is about to cost, before any of it is spent.

    Uses the tokens per run actually recorded under this harness — any model's,
    since the harness is what decides how much text a turn carries — and falls
    back to a documented guess when the benchmark is empty. Says which it used,
    because an estimate whose basis is invisible gets quoted as a measurement.
    """
    seen = [r for d in load(version) for p in (d.get("passes") or [])
            for r in (p.get("runs") or [])]
    if seen:
        per_in = sum(r.get("tokens_in") or 0 for r in seen) / len(seen)
        per_out = sum(r.get("tokens_out") or 0 for r in seen) / len(seen)
        basis = f"{len(seen)} runs already recorded under {version}"
    else:
        per_in, per_out = TYPICAL_RUN
        basis = "a typical run; nothing recorded under this harness yet"
        # Not silently scaled up by a guessed factor -- that would be an invented
        # number wearing an estimate's clothes. Said out loud instead: a harness
        # that carries notes puts them in every prompt of every turn, so its real
        # input is higher than this until one pass exists to measure.
        if cross_run_memory(version):
            basis += ", which had none of the notes this one puts in every prompt"
    total_in, total_out = round(per_in * n_runs), round(per_out * n_runs)
    return {
        "model": model, "runs": n_runs, "basis": basis,
        "tokens_in": total_in, "tokens_out": total_out,
        "usd": cost(total_in, total_out, price),
    }


# ------------------------------------------------------------------- pre-flight


def preflight(version: str, model: str, endpoint: str | None = None,
              token: str | None = None) -> dict[str, Any]:
    """One call, before spending anything, to find out whether this can work.

    The failure this exists for: a model that cannot emit tool calls scores a
    perfect zero and takes half an hour to do it. Every turn exhausts its rounds,
    falls back to the safe heuristic, and the run completes looking like a model
    that plays badly — the only sign being `fallback_rate` at 1.0, read afterwards.
    Fifty runs, real money, and nothing measured.

    So: one trivial request with the real tools attached, asking for the one thing
    the harness cannot do without. Deliberately not a game state — this is not
    asking whether the model plays well, only whether it can speak the protocol.
    Costs a few hundred tokens.

    NEVER RAISES, and that is not laziness. The harness is a frozen copy, so it
    defines its own `LLMConfigError` under its own module name — a class the
    package's `except LLMConfigError` does not catch. Anything that reaches out
    from behind that boundary and expects the caller to recognise it is wrong by
    construction. So every outcome comes back as data, and the caller has one
    branch: `ok`.
    """
    from .bot.catalogue import load_class

    out: dict[str, Any] = {"model": model, "harness": version, "ok": False,
                           "tool_calls": [], "tokens_in": 0, "tokens_out": 0}
    try:
        cls = load_class(harness_path(version))
        bot = cls(seed=0, model=model, endpoint=endpoint, token=token)
    except Exception as e:  # noqa: BLE001 — a bad endpoint or token lands here
        out["why"] = f"{type(e).__name__}: {e}"
        return out

    # Something with an unambiguous right answer, so a refusal to use the tool is
    # about the model's abilities and not about the question being hard.
    probe = [
        {"role": "system", "content": "You are testing a tool call. Do exactly as asked."},
        {"role": "user", "content":
            "There is one legal action, index 0. Call the play tool with index 0 "
            "and any reason. Do not answer in prose."},
    ]
    try:
        msg = bot._call(probe)
    except Exception as e:  # noqa: BLE001
        out.update(why=f"{type(e).__name__}: {e}",
                   tokens_in=bot.tokens_in, tokens_out=bot.tokens_out,
                   retries=bot.retries)
        return out

    calls = msg.get("tool_calls") or []
    out.update(
        tool_calls=[c.get("function", {}).get("name") for c in calls],
        tokens_in=bot.tokens_in, tokens_out=bot.tokens_out, retries=bot.retries,
        ok=bool(calls),
    )
    if not calls:
        out["why"] = (
            "answered, but called no tool. The harness ends a turn by calling "
            "play(), so every turn would exhaust its rounds and fall back to the "
            "safe heuristic — fifty runs of our heuristic under the model's name. "
            "Check that this model supports tool calling on this endpoint."
        )
    return out


# ------------------------------------------------------------------- recording


def records(seeds: list[int]) -> bool:
    """Whether a pass over these seeds may be written to `results/`.

    Only the standard fifty, and compared BY VALUE. Length is not enough: fifty
    seeds of somebody's own choosing would otherwise be recorded, and the row would
    sit in the table looking exactly like one that is comparable to every other.
    That is the one mistake this file exists to prevent, so it is a function with a
    test rather than a comparison inlined at the one place that happens to need it.

    Order counts too, deliberately. Under a harness that carries the model's notes
    from one run to the next, the order the seeds were played in is part of what was
    measured, so the same fifty seeds shuffled are not the same measurement.
    """
    return list(seeds) == list(STANDARD_SEEDS)


def result_path(version: str, model: str) -> Path:
    return BENCH / version / "results" / f"{slug(model)}.json"


def record(version: str, model: str, one_pass: dict[str, Any]) -> Path:
    """Appends a pass to this model's file under this harness version.

    Appends rather than replaces, because two passes of the same model are the
    only way to know whether the gap to another model is bigger than the model's
    own variance.
    """
    path = result_path(version, model)
    if path.is_file():
        doc = json.loads(path.read_text(encoding="utf-8"))
    else:
        doc = {"model": model, "harness": version, "passes": []}
    # Recorded per pass, not per file: a pass played before render.py changed and
    # one played after are different measurements, and the file must be able to
    # say so rather than carrying one hash for both.
    doc["passes"].append(one_pass)
    doc["model"] = model
    doc["harness"] = version
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=1), encoding="utf-8")
    return path


def load(version: str) -> list[dict[str, Any]]:
    d = BENCH / version / "results"
    if not d.is_dir():
        return []
    return [json.loads(f.read_text(encoding="utf-8")) for f in sorted(d.glob("*.json"))]


# ------------------------------------------------------------------ statistics


def learning(passes: list[dict[str, Any]], k: int = LEARN_K) -> dict[str, Any]:
    """First k runs of a pass against its last k, averaged over passes.

    The number a memory harness is for. Its mean is still comparable to a
    memoryless version, but a mean over a learning curve averages a naive model
    with a practised one and hides the only effect being tested.

    Computed in the order the runs were PLAYED, not seed order: the fortieth run
    had thirty-nine runs' worth of notes behind it, and rows are stored sorted by
    seed. Falls back to seed order for rows recorded before `order` existed, which
    is the same thing whenever the seed list was ascending.

    Per pass, then averaged, rather than pooling every run: pooling would compare
    the first k of one pass against the last k of another, which are different
    lifetimes.
    """
    firsts: list[float] = []
    lasts: list[float] = []
    for p in passes:
        runs = p.get("runs") or []
        # Fewer than 2k runs and the two halves would overlap, which would show a
        # gain that is really the same runs counted twice.
        if len(runs) < 2 * k:
            continue
        played = sorted(runs, key=lambda r: (r.get("order") is None, r.get("order"),
                                             r.get("seed")))
        firsts.append(statistics.mean([r.get("badges") or 0 for r in played[:k]]))
        lasts.append(statistics.mean([r.get("badges") or 0 for r in played[-k:]]))
    if not firsts:
        return {"k": k, "first": None, "last": None, "delta": None, "passes": 0}
    first, last = statistics.mean(firsts), statistics.mean(lasts)
    return {
        "k": k,
        "first": round(first, 2),
        "last": round(last, 2),
        "delta": round(last - first, 2),
        "passes": len(firsts),
    }


def stats(doc: dict[str, Any], version: str | None = None) -> dict[str, Any]:
    """Pooled over every run of every pass, with the across-pass spread beside it.

    Statistics are derived here and never stored: the rows are the record, and a
    stored average is a number that cannot be checked and goes wrong silently when
    the definition changes.
    """
    passes = doc.get("passes") or []
    runs = [r for p in passes for r in (p.get("runs") or [])]
    if not runs:
        return {"model": doc.get("model"), "passes": 0, "runs": 0}

    badges = [r.get("badges") or 0 for r in runs]
    sd = statistics.stdev(badges) if len(badges) > 1 else 0.0
    per_pass = [
        statistics.mean([r.get("badges") or 0 for r in p["runs"]])
        for p in passes if p.get("runs")
    ]
    tok_in = sum(r.get("tokens_in") or 0 for r in runs)
    tok_out = sum(r.get("tokens_out") or 0 for r in runs)
    turns = sum(r.get("turns") or 0 for r in runs)
    falls = sum(r.get("fallbacks") or 0 for r in runs)

    out = {
        "model": doc.get("model"),
        "passes": len(passes),
        "runs": len(runs),
        "badges_mean": round(statistics.mean(badges), 3),
        # The number that decides whether any gap in this table is real.
        "badges_sem": round(sd / len(badges) ** 0.5, 3) if sd else 0.0,
        "badges_median": statistics.median(badges),
        "badges_best": max(badges),
        # Sampling noise on its own: the seeds are fixed, so what moves between
        # passes is the model.
        "pass_spread": round(max(per_pass) - min(per_pass), 3) if len(per_pass) > 1 else None,
        "tokens_in_per_run": round(tok_in / len(runs)),
        "tokens_out_per_run": round(tok_out / len(runs)),
        "tokens_total": tok_in + tok_out,
        "fallback_rate": round(falls / turns, 3) if turns else 0.0,
        "notes_kept": (
            max((r.get("notes_kept") or 0) for r in runs)
            if any("notes_kept" in r for r in runs) else None
        ),
        "learning": learning(passes),
    }
    if version:
        now = fingerprints(version)
        used = {k: v for p in passes for k, v in (p.get("fingerprint") or {}).items()}
        out["stale"] = bool(used) and used != now
    return out


# --------------------------------------------------------------------- logging
#
# A benchmark can run for hours. A progress bar is fine while you are watching it
# and worth nothing afterwards: come back to a finished terminal and there is no
# answer to "what did it do for three hours", "when did it start failing", or
# "how much did that cost". So every pass writes a log beside its results.
#
# Deliberately a readable text file rather than JSON. The rows themselves are
# already stored, in full, in the result -- this is the thing you `tail -f` from
# another terminal, so it is aligned columns and nothing else.


def session_dir(version: str) -> Path:
    """One directory per command, named for the moment it was launched.

    Everything that command writes goes inside: a log and a decision trace for
    each pass, and what was asked for. Flat files named by model and timestamp
    could not answer "which of these twelve belong together" -- with `--models a,b
    --repeat 3` there were six pairs loose in one directory and only the clock to
    guess by.

    `ls -t` therefore lists your commands, newest first, and
    `tail -f logs/<stamp>/*.log` follows exactly one command and nothing else.

    Results deliberately do NOT live here. A result is one file per model with
    every pass appended, because it is the comparable record: ten commands over
    three days build up one model's history, and splitting it by invocation would
    destroy the only thing it is for.
    """
    d = BENCH / version / "logs" / datetime.now().strftime("%Y%m%d-%H%M%S")
    d.mkdir(parents=True, exist_ok=True)
    return d


def record_command(folder: Path, payload: dict[str, Any]) -> Path:
    """What was asked for, beside what it produced.

    The one thing nothing wrote down before: come back to a finished sweep three
    hours later and the flags it ran with were gone, so a surprising number could
    not be traced to how it was asked for.

    The endpoint is written because a row measured against one provider is not the
    same measurement as against another, and that is worth knowing later. A token is
    worth nothing later and is a liability forever, so this REFUSES to write one
    rather than trusting every future caller to leave it out. The check is on the
    keys, not on the values: guessing at the shape of a secret is how secrets get
    written, while a field called `api_key` has no business here whatever it holds.
    """
    banned = {"api_key", "apikey", "token", "fw_token", "key", "secret",
              "password", "authorization"}
    bad = sorted(k for k in payload if k.lower().replace("-", "_") in banned)
    if bad:
        raise ValueError(
            f"refusing to write {', '.join(bad)} into {folder.name}/command.json: "
            f"credentials do not belong in a record of what was measured."
        )
    path = folder / "command.json"
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")
    return path


class PassLog:
    """One line per finished run, flushed as it happens.

    Flushed per line on purpose: a log that buffers tells you nothing about a run
    still in progress, which is the only time you need it, and loses the ending if
    the process dies -- which is exactly the ending worth reading.

    In parallel, lines arrive in completion order rather than seed order, because
    they are written as workers finish. That is not a defect: it is what tells you
    a particular worker has been stuck on one game for two minutes.
    """

    COLUMNS = ("  seed  badges  steps        in       out  fell  retry     secs")
    COLUMNS_MEMORY = COLUMNS + "  notes"

    def __init__(self, version: str, model: str, seeds: list[int], workers: int,
                 memory: bool = False, folder: Path | None = None,
                 attempt: int = 1) -> None:
        # The command's directory, made by the caller so that every pass of a
        # sweep lands in the same one. Created here when there is no caller to ask
        # -- play_model() is usable on its own from a notebook.
        folder = folder or session_dir(version)
        # Numbered rather than timestamped: inside one command the pass number is
        # what tells them apart, and it sorts correctly.
        self.path = folder / f"{slug(model)}-pass{attempt}.log"
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.started = time.time()
        self.n = 0
        self.total = len(seeds)
        self.badges: list[int] = []
        # Last notebook seen, so the log can show what CHANGED rather than
        # reprinting twelve unchanged notes fifty times.
        self.memory = memory
        self.model = model
        self.book: list[str] = []
        # Per seed, the last (in, out) seen for it. Two jobs from one dict: the
        # difference against the previous reading is what a turn cost, and the sum
        # over every seed is what the pass has cost -- including runs still in
        # flight on other workers, which a running total of finished rows alone
        # would miss. A finished row overwrites its seed's entry with the final
        # figure, so nothing is double counted.
        self.spent: dict[int, tuple[int, int]] = {}
        self.fh = self.path.open("w", encoding="utf-8", buffering=1)
        # What the model decided and why, one JSON object per decision. A separate
        # file because it is a different shape and a different reader: the .log is
        # for a person watching, this is for anyone asking afterwards "why did it
        # walk into that". Line-buffered too, so a killed run keeps what it had.
        #
        # NOT in the result. Twenty decisions a run times fifty runs would multiply
        # the size of a file whose job is to hold one comparable row per seed.
        self.trace_path = self.path.with_suffix(".jsonl")
        self.tf = self.trace_path.open("w", encoding="utf-8", buffering=1)
        # The two things the model WRITES, each in its own file, one block per run:
        # what it decided to keep between runs, and the route it meant to take.
        # They are in the run rows too, but a result holds fifty of them interleaved
        # with everything else, and the question these answer -- how did it write
        # them, and how did they change -- wants them alone and in order.
        #
        # Opened on demand rather than up front: v0 has neither, and two empty files
        # per pass would be litter that reads like a bug.
        self.book_path = self.path.with_name(self.path.stem + "-notebook.log")
        self.plan_path = self.path.with_name(self.path.stem + "-plan.log")
        self.bf: Any = None
        self.pf: Any = None
        self._last_book: list[str] | None = None
        self._last_plan: str | None = None
        self._say(f"{datetime.now():%Y-%m-%d %H:%M:%S}  harness {version}  {model}")
        self._say(f"{len(seeds)} seeds, {workers} worker{'s' if workers != 1 else ''}, "
                  f"seeds {seeds[0]}..{seeds[-1]}")
        if memory:
            self._say("this harness keeps the model's notes between runs: they are "
                      "logged as they change.")
        self._say(self.COLUMNS_MEMORY if memory else self.COLUMNS)

    def _say(self, line: str) -> None:
        self.fh.write(line + "\n")

    def run(self, row: dict[str, Any]) -> None:
        self.n += 1
        self.badges.append(row.get("badges") or 0)
        # The final word on what this seed spent: the last decision was not the end
        # of the run, since the turn after it can still have cost tokens.
        self.spent[row.get("seed")] = (row.get("tokens_in") or 0,
                                       row.get("tokens_out") or 0)
        self._say(
            f"{row.get('seed', 0):>6}{row.get('badges') or 0:>8}{row.get('steps') or 0:>7}"
            f"{row.get('tokens_in') or 0:>10}{row.get('tokens_out') or 0:>10}"
            f"{row.get('fallbacks') or 0:>6}{row.get('retries') or 0:>7}"
            f"{row.get('secs') or 0:>9.1f}"
            + (f"{row.get('notes_kept') or 0:>7}" if self.memory else "")
            # Only annotated when it is worth reading: a run the model did not
            # really play, or one that wedged.
            + ("   <- fell back" if (row.get("fallbacks") or 0) else "")
            + ("   <- STALLED" if row.get("stalled") else "")
        )
        # What the model changed its mind about, when it did. The interesting
        # output of a memory harness is not the badge count, it is this: read the
        # log after an hour and you can see what it decided the game rewards.
        if self.memory and "notebook" in row:
            book = list(row["notebook"])
            for note in [x for x in book if x not in self.book]:
                self._say(f"       + {note}")
            for note in [x for x in self.book if x not in book]:
                self._say(f"       - {note}")
            self.book = book
        self._write_notebook(row)
        self._write_plan(row)
        # A mark every ten runs, with where it is and when it should finish. The
        # point of the whole file: come back after an hour and the last of these
        # lines answers "is this going to take another twenty minutes or another
        # three hours", without doing arithmetic on the column above.
        if self.total and self.n % 10 == 0 and self.n < self.total:
            done = time.time() - self.started
            left = done / self.n * (self.total - self.n)
            self._say(
                f"  .. {self.n}/{self.total}  "
                f"badges {sum(self.badges) / len(self.badges):.2f}  "
                f"{done / 60:.0f} min in, about {left / 60:.0f} left, "
                f"done around {datetime.fromtimestamp(time.time() + left):%H:%M}"
            )

    def done(self, one_pass: dict[str, Any]) -> None:
        s = one_pass.get("summary") or {}
        mins = (time.time() - self.started) / 60
        fell = one_pass.get("fallback_rate", 0)
        self._say(
            f"done  {s.get('runs', self.n)} runs  {s.get('badges_mean')} badges  "
            f"{one_pass.get('tokens_in', 0) / 1e6:.2f}M in  "
            f"{one_pass.get('tokens_out', 0) / 1e6:.2f}M out  "
            f"fallback {fell}  retries {one_pass.get('retries', 0)}  "
            f"in {mins:.1f} min"
        )
        if fell > 0.1:
            self._say("WARNING fallback over 0.1: this row measures the harness, "
                      "not the model")
        # What it ended up believing. Printed in full here even though every change
        # is above, because this is the version's actual output and a reader should
        # not have to replay a diff to see it.
        if self.memory:
            # Derived here rather than read off the pass: statistics are computed
            # from the rows every time, so there is no stored average to go stale
            # when the definition changes.
            lc = learning([one_pass])
            if lc.get("delta") is not None:
                self._say(f"first {lc['k']} runs {lc['first']} badges, "
                          f"last {lc['k']} {lc['last']}, so {lc['delta']:+} "
                          f"-- what this harness is for")
            self._say(f"notes it finished with ({len(self.book)}):")
            for i, note in enumerate(self.book, 1):
                self._say(f"  [{i}] {note}")

    def _write_notebook(self, row: dict[str, Any]) -> None:
        """One block a run: the notes as they stood when that run ended.

        `unchanged` rather than a reprint when nothing moved, because fifty
        identical blocks would bury the three runs where it actually learned
        something.
        """
        book = row.get("notebook")
        if book is None:
            return
        if self.bf is None:
            self.bf = self.book_path.open("w", encoding="utf-8", buffering=1)
            self.bf.write(f"notes the model kept between runs — {self.model}\n"
                          f"one block per finished run, in the order played\n\n")
        head = f"run {self.n:>2}  seed {row.get('seed')}  ({len(book)} notes)"
        if book == self._last_book:
            self.bf.write(f"{head}  unchanged\n")
        else:
            self.bf.write(head + "\n")
            for i, note in enumerate(book, 1):
                self.bf.write(f"  [{i}] {note}\n")
            if not book:
                self.bf.write("  (empty — it wrote nothing)\n")
            self._last_book = list(book)

    def _write_plan(self, row: dict[str, Any]) -> None:
        """One block a run: the route it had committed to when the run ended.

        Per run, which is the honest granularity: the harness reports the plan as it
        stands at the end, so a route replaced twice mid-run shows only its last
        version. Catching every change would mean the harness recording its own
        history, and the harness is frozen.
        """
        plan = row.get("plan")
        if plan is None:
            return
        if self.pf is None:
            self.pf = self.plan_path.open("w", encoding="utf-8", buffering=1)
            self.pf.write(f"the route the model planned for each map — {self.model}\n"
                          f"as it stood when the run ended\n\n")
        head = f"run {self.n:>2}  seed {row.get('seed')}"
        if plan == self._last_plan:
            self.pf.write(f"{head}  unchanged\n")
        elif not plan:
            self.pf.write(f"{head}  (none — it never called plan)\n")
        else:
            self.pf.write(f"{head}\n  {plan}\n")
        self._last_plan = plan

    def decision(self, e: dict[str, Any]) -> None:
        """One decision, as JSON. The minimum that answers what and why.

        Deliberately not the prompt, not the tool calls and not the rendered
        screen: those are reconstructible from the harness plus the seed, they are
        most of the bytes, and none of them is what you come here to read. What is
        NOT reconstructible is which option it took out of the ones it had and the
        sentence it gave for it.

        `options` is kept because an index means nothing on its own, and `why`
        already says when the turn was played by the fallback instead of the model.
        """
        seed = e.get("seed")
        run_in, run_out = e.get("run_in") or 0, e.get("run_out") or 0
        was_in, was_out = self.spent.get(seed, (0, 0))
        self.spent[seed] = (run_in, run_out)
        pass_in = sum(v[0] for v in self.spent.values())
        pass_out = sum(v[1] for v in self.spent.values())

        self.tf.write(json.dumps({
            "seed": seed,
            "step": e.get("step"),
            "screen": e.get("screen"),
            "map": e.get("map"),
            "badges": e.get("badges"),
            "chose": e.get("chosen"),
            "action": e.get("chosen_label"),
            "options": e.get("options"),
            "swapped": e.get("swapped"),
            "why": e.get("why"),
            # Three levels of the same two numbers. `turn_*` is the difference
            # against this seed's previous decision, so it covers every HTTP call
            # the turn made -- v0 allows four tool rounds, and what you want to know
            # is what the TURN cost, not what one of its requests cost.
            "turn_in": max(run_in - was_in, 0),
            "turn_out": max(run_out - was_out, 0),
            "run_in": run_in,
            "run_out": run_out,
            "pass_in": pass_in,
            "pass_out": pass_out,
        }, ensure_ascii=False) + "\n")

    def fail(self, why: str) -> None:
        self._say(f"FAILED after {self.n} runs: {why}")

    def close(self) -> None:
        for fh in (self.fh, self.tf, self.bf, self.pf):
            if fh is not None and not fh.closed:
                fh.close()

    def __enter__(self) -> "PassLog":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


# ---------------------------------------------------------------------- running


def play_model(game, version: str, model: str, site: Path,
               seeds: list[int] | None = None, endpoint: str | None = None,
               token: str | None = None, folder: Path | None = None,
               attempt: int = 1) -> dict[str, Any]:
    """One pass: this model over the seed list, under this harness."""
    from .bot.catalogue import load_class

    seeds = seeds or STANDARD_SEEDS
    cls = load_class(harness_path(version))
    bot = cls(seed=0, model=model, endpoint=endpoint, token=token)
    # Taken now, against the code about to play, not at the end against whatever
    # is on disk by then.
    stamp = fingerprints(version)
    log = PassLog(version, model, seeds, workers=1, folder=folder,
                  attempt=attempt, memory=cross_run_memory(version))
    last = [time.time()]

    # One bot for the whole pass, which is what resets a memory harness: notes
    # survive `on_start` and so cross between runs, and nothing survives the bot,
    # so the next pass starts naive. Nothing to reset by hand — and nothing that
    # could be forgotten, which is why it is arranged this way rather than with a
    # reset call.

    # Token counts are per run: `on_start` resets them, so reading notes() once at
    # the end would report only the last of fifty runs. `on_run` hands back the row
    # itself, so each one carries what that run actually spent.
    def on_run(row: dict[str, Any], done: int, total: int) -> None:
        now = time.time()
        n = bot.notes()
        row.update(tokens_in=n.get("tokens_in", 0), tokens_out=n.get("tokens_out", 0),
                   calls=n.get("calls", 0), turns=n.get("turns", 0),
                   fallbacks=n.get("fallbacks", 0), retries=n.get("retries", 0),
                   secs=round(now - last[0], 1))
        # Which run of the pass this was. Rows are stored in seed order, but a
        # memory harness is only interpretable in the order it was PLAYED — the
        # tenth run had nine runs' worth of notes behind it. Recorded for every
        # version, because it costs one integer and its absence cannot be
        # reconstructed afterwards.
        row["order"] = done
        if "notebook" in n:
            # What the model believed at the end of this run, saved with the run
            # rather than once at the end of the pass, so a lesson that was learned
            # and later revised away is still in the record.
            row["notebook"] = n["notebook"]
            row["notes_kept"] = n.get("notes_kept", len(n["notebook"]))
        if "plan" in n:
            # The route it had committed to when the run ended. Per run, like the
            # notebook, and for the same reason: the interesting object is how it
            # changed, not where it landed.
            row["plan"] = n["plan"]
        last[0] = now
        log.run(row)

    try:
        result = run_benchmark(
            game, bot, bot_name=f"{model} @ {version}", site=site, seeds=seeds,
            category="llm", description=f"model benchmark, harness {version}",
            on_run=on_run, on_decision=log.decision,
        )
    except BaseException as e:
        log.fail(f"{type(e).__name__}: {e}")
        log.close()
        raise
    one = _as_pass(version, model, seeds, result["runs"], result["game"],
                   result.get("notes") or {}, fingerprint=stamp)
    one["log"] = str(log.path)
    one["trace"] = str(log.trace_path)
    log.done(one)
    log.close()
    return one


def _as_pass(version: str, model: str, seeds: list[int], runs: list[dict[str, Any]],
             game: dict[str, str], notes: dict[str, Any],
             fingerprint: dict[str, str] | None = None) -> dict[str, Any]:
    """The pass as it will be recorded.

    `fingerprint` is taken by the CALLER, before the first seed is played, and
    passed in. Hashing the harness here instead would hash it half an hour later:
    edit the file mid-pass and the row would claim the code it never ran, while
    matching disk perfectly -- a false statement that nothing could detect, which
    is the exact opposite of what a fingerprint is for. Recomputed here only when
    no caller supplied one, so the function stays usable on its own.
    """
    turns = sum(r.get("turns") or 0 for r in runs)
    falls = sum(r.get("fallbacks") or 0 for r in runs)
    return {
        "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "model": model,
        "harness": version,
        "fingerprint": fingerprint or fingerprints(version),
        "game": game,
        "seeds": seeds,
        "summary": summarise(runs),
        "tokens_in": sum(r.get("tokens_in") or 0 for r in runs),
        "tokens_out": sum(r.get("tokens_out") or 0 for r in runs),
        "retries": sum(r.get("retries") or 0 for r in runs),
        "fallback_rate": round(falls / turns, 3) if turns else 0.0,
        "notes": notes,
        "runs": sorted(runs, key=lambda r: r["seed"]),
    }


# ------------------------------------------------------------------- in parallel
#
# Worth much more here than for a local bot. An LLM run is about twenty turns and
# one HTTP request each, so almost all of its wall clock is spent waiting on the
# provider rather than on this machine -- which means workers can outnumber cores
# and still help. Fifty seeds sequentially is half an hour; eight at a time is a
# few minutes, for the same tokens and the same money.
#
# Processes, not threads, and not by choice: Playwright's sync API is bound to the
# thread that created it, so one game per process is the only arrangement that
# works. `experiments/drrn/collect.py` fans out the same way for the same reason.
#
# Seeds are independent, so splitting them changes nothing about the result: the
# merged pass is what a sequential run would have produced, sorted back into seed
# order. Interleaved rather than in blocks, so a worker that draws a run of long
# games does not become the one everybody waits for.


def fan_out(version: str, model: str, seeds: list[int], workers: int,
            site: Path, port0: int = 8500, endpoint: str | None = None,
            token: str | None = None, folder: Path | None = None,
            attempt: int = 1) -> dict[str, Any]:
    """The same pass, played by several processes at once."""
    import os
    import queue
    import subprocess
    import sys
    import threading

    # Not for a harness whose model keeps notes between runs. Splitting the seeds
    # would give each worker its own notebook and each note to a tenth of the pass,
    # so the result would depend on how the seeds happened to be dealt and on which
    # worker finished first. Refused rather than warned about: the pass would look
    # exactly like a valid one, and the recorded row would be unreproducible in a
    # way nothing in the file would reveal.
    if cross_run_memory(version):
        raise RuntimeError(
            f"harness {version} carries the model's notes from one run into the "
            f"next, so its runs are not independent and the pass cannot be split "
            f"across {workers} workers.\n"
            f"  Run it sequentially: drop --workers (or pass --workers 1).\n"
            f"  A pass is one lifetime of {len(seeds)} runs, in seed order, which is "
            f"part of what {version} measures."
        )

    # Credentials reach the workers through the environment even when they came
    # from a flag, and NOT on their command line: every process list on the
    # machine shows argv, so a key passed that way would be readable by any other
    # user for as long as the benchmark runs. The model id is not a secret and
    # stays visible, which is what makes `ps` useful here.
    # Before a single worker starts, for the same reason as the sequential path.
    stamp = fingerprints(version)

    env = dict(os.environ)
    if endpoint:
        env["FW_ENDPOINT"] = endpoint
    if token:
        env["FW_TOKEN"] = token

    chunks = [seeds[k::workers] for k in range(workers)]
    chunks = [c for c in chunks if c]
    procs = []
    for k, chunk in enumerate(chunks):
        procs.append(subprocess.Popen(
            [sys.executable, "-m", "pokelike.llmbench", "--worker",
             "--harness", version, "--model", model, "--port", str(port0 + k),
             "--seeds", ",".join(str(s) for s in chunk)],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, env=env,
        ))

    # Rows arrive as they finish, from whichever worker finished them, so the bar
    # measures the whole pass rather than one process's share of it.
    rows: list[dict[str, Any]] = []
    # Where each worker is right now, keyed by worker. Overwritten rather than
    # appended: this is a reading, not a record -- the record is the row that
    # arrives when the run finishes.
    live: dict[int, dict[str, Any]] = {}
    q: queue.Queue = queue.Queue()

    def pump(p: Any, k: int) -> None:
        for line in p.stdout:
            line = line.strip()
            if line.startswith("{"):
                q.put((k, json.loads(line)))
        q.put((k, None))

    for k, p in enumerate(procs):
        threading.Thread(target=pump, args=(p, k), daemon=True).start()

    log = PassLog(version, model, seeds, workers=len(procs), folder=folder,
                  attempt=attempt)
    bar = progress_bar(total=len(seeds), desc=f"{model} @ {version}",
                       unit="run", leave=True)
    def postfix() -> None:
        done = [r for r in rows if r.get("badges") is not None]
        # Finished runs plus what the in-flight ones have spent so far, in and out
        # kept apart: output is priced several times higher, so one total cannot be
        # turned into a bill.
        t_in = (sum(r.get("tokens_in", 0) for r in rows)
                + sum(v.get("tokens_in", 0) for v in live.values()))
        t_out = (sum(r.get("tokens_out", 0) for r in rows)
                 + sum(v.get("tokens_out", 0) for v in live.values()))
        bar.set_postfix({
            "badges": round(sum(r["badges"] for r in done) / len(done), 2) if done else None,
            "in": _tok(t_in),
            "out": _tok(t_out),
            "fell": sum(r.get("fallbacks", 0) for r in rows),
            # What the workers are on at this instant, so a bar stuck on the same
            # count still shows movement -- or shows that there is none. Seed and
            # depth only: badges and steps mid-run are noise, and the row written
            # when the run finishes carries both. Passed as a dict rather than as
            # keywords because tqdm renders numbers through its own formatter, and
            # a seed becomes `1e+4`.
            "now": " ".join(f"{v['seed']}@{v.get('layer', '?')}"
                            for v in sorted(live.values(), key=lambda x: x["seed"])),
        })

    ended = 0
    while ended < len(procs):
        k, item = q.get()
        if item is None:
            ended += 1
            live.pop(k, None)
            postfix()
            continue
        if item.get("live"):
            live[k] = item
            postfix()
            continue
        if "trace" in item:
            # Written by the parent rather than by each worker, so a parallel pass
            # produces ONE trace file instead of one per process -- and so no two
            # processes ever write the same file.
            log.decision(item["trace"])
            continue
        rows.append(item)
        log.run(item)
        live.pop(k, None)
        bar.update(1)
        postfix()
    bar.close()

    # All or nothing. A pass with 43 of 50 seeds in it is worse than no pass: the
    # mean would be over whichever seeds happened to survive, and nothing in the
    # file would say so.
    for k, p in enumerate(procs):
        p.wait()
        if p.returncode != 0:
            err = (p.stderr.read() or "").strip()[-600:]
            log.fail(f"worker {k} exited {p.returncode}: {err[-200:]}")
            log.close()
            raise RuntimeError(
                f"worker {k} exited {p.returncode}; discarding the whole pass "
                f"rather than recording a partial one.\n{err}"
            )
    if len(rows) != len(seeds):
        log.fail(f"collected {len(rows)} of {len(seeds)} runs")
        log.close()
        raise RuntimeError(
            f"expected {len(seeds)} runs, collected {len(rows)}; discarding the pass"
        )

    from .bench import bundle_fingerprint
    one = _as_pass(version, model, seeds, rows, bundle_fingerprint(site), {},
                   fingerprint=stamp)
    one["log"] = str(log.path)
    one["trace"] = str(log.trace_path)
    log.done(one)
    log.close()
    return one


def _worker() -> int:
    """One process, one browser, its slice of the seeds. Prints a JSON row each."""
    import argparse

    from .assets.server import AssetServer
    from .bot.catalogue import load_class
    from .core.game import Game
    from .bench import live_fields
    from .runner import play_run

    p = argparse.ArgumentParser()
    p.add_argument("--worker", action="store_true")
    p.add_argument("--harness", required=True)
    p.add_argument("--model", required=True)
    p.add_argument("--port", type=int, required=True)
    p.add_argument("--seeds", required=True)
    a = p.parse_args()

    seeds = [int(s) for s in a.seeds.split(",") if s]
    cls = load_class(harness_path(a.harness))
    bot = cls(seed=0, model=a.model)
    server = AssetServer(ROOT / "site", port=a.port)
    server.start()
    game = Game(url=server.url)
    game.open()
    try:
        for seed in seeds:
            began = time.time()

            # A worker's run takes one to three minutes and the parent cannot see
            # inside it, so without this the shared bar has nothing to say for
            # minutes at a time. Every fifth step, because the point is "it is
            # moving and here is where", not a transcript.
            def live(obs, steps, _seed=seed):
                if steps % 5:
                    return
                # Raw counts, not the bar's pretty strings: the parent has to add
                # them up across workers before anyone formats anything.
                print(json.dumps({
                    "live": True, "seed": _seed, "step": steps,
                    "tokens_in": bot.tokens_in, "tokens_out": bot.tokens_out,
                    **live_fields(obs),
                }), flush=True)

            def decided(entry, _seed=seed):
                print(json.dumps({"trace": {
                    "seed": _seed,
                    "run_in": bot.tokens_in, "run_out": bot.tokens_out,
                    **entry,
                }}, ensure_ascii=False), flush=True)

            full = play_run(game, bot, seed, max_steps=400, on_step=live,
                            on_decision=decided)
            n = bot.notes()
            row = {k: full[k] for k in ("seed", "steps", "score", "badges", "maps",
                                        "kos", "faints", "ending", "stalled")}
            row.update(tokens_in=n.get("tokens_in", 0), tokens_out=n.get("tokens_out", 0),
                       calls=n.get("calls", 0), turns=n.get("turns", 0),
                       fallbacks=n.get("fallbacks", 0), retries=n.get("retries", 0),
                       secs=round(time.time() - began, 1))
            print(json.dumps(row), flush=True)
    finally:
        game.close()
        server.stop()
    return 0


if __name__ == "__main__":
    raise SystemExit(_worker())


# ----------------------------------------------------------------------- table


def format_table(version: str, price: dict[str, dict[str, float]] | None = None) -> str:
    rows = [stats(d, version) for d in load(version)]
    rows = [r for r in rows if r.get("runs")]
    if not rows:
        return f"no models measured under harness {version} yet"
    rows.sort(key=lambda r: -r["badges_mean"])
    money = bool(price)
    # Only for a harness that keeps notes. On a memoryless version the first ten
    # seeds against the last ten is noise with a suggestive name.
    learns = cross_run_memory(version)
    head = (f"{'model':<34}{'passes':>7}{'runs':>6}{'badges~':>9}{'±sem':>7}"
            f"{'med':>5}{'best':>6}" + (f"{'learn':>8}{'notes':>7}" if learns else "")
            + f"{'tok in/run':>11}{'tok out/run':>12}{'fallback':>9}"
            # `$` rather than `usd`, and the per-run figure beside the total: the
            # total answers "what did this row cost", the per-run answers "what
            # will another pass cost me", which is the question you actually ask.
            + (f"{'$':>8}{'$/run':>9}" if money else ""))
    out = [head, "-" * len(head)]
    for r in rows:
        usd = cost(r["tokens_in_per_run"] * r["runs"], r["tokens_out_per_run"] * r["runs"],
                   (price or {}).get(r["model"])) if money else None
        lc = r.get("learning") or {}
        out.append(
            f"{str(r['model'])[:33]:<34}{r['passes']:>7}{r['runs']:>6}"
            f"{r['badges_mean']:>9}{r['badges_sem']:>7}{r['badges_median']:>5}"
            f"{r['badges_best']:>6}"
            + ((f"{lc['delta']:>+8.2f}" if lc.get("delta") is not None else f"{'-':>8}")
               + f"{r.get('notes_kept') if r.get('notes_kept') is not None else '-':>7}"
               if learns else "")
            + f"{r['tokens_in_per_run']:>11}"
            f"{r['tokens_out_per_run']:>12}{r['fallback_rate']:>9}"
            + (f"{usd:>8.2f}{usd / r['runs']:>9.4f}" if usd is not None
               else (f"{'-':>8}{'-':>9}" if money else ""))
            + ("  <- harness or render changed since this ran" if r.get("stale") else "")
            + ("  <- fallback over 0.1: measuring the harness, not the model"
               if r["fallback_rate"] > 0.1 else "")
        )
    out += ["-" * len(head),
            f"harness {version}, {len(STANDARD_SEEDS)} fixed seeds a pass. Two models "
            f"whose means differ by less than about",
            "twice the ±sem are not distinguishable here — read that column before "
            "reading the order."]
    if learns:
        out += [
            "learn is the last 10 runs of a pass minus its first 10, in the order "
            "played: this harness lets the",
            "model keep notes between runs, so it is the column the version exists "
            "to produce. notes is the most it",
            "ever held at once. badges~ is a mean over a learning curve here, "
            "comparable to other harnesses but",
            "not a description of how well the model ends up playing.",
        ]
    if money:
        out.append("$ is what those tokens cost at today's OpenRouter prices, "
                   "computed now and never stored. $/run is that over its runs.")
    return "\n".join(out)


def markdown_table(version: str,
                   price: dict[str, dict[str, float]] | None = None) -> str:
    rows = [stats(d, version) for d in load(version)]
    rows = [r for r in rows if r.get("runs")]
    if not rows:
        return f"_No models measured under harness `{version}` yet._"
    rows.sort(key=lambda r: -r["badges_mean"])
    learns = cross_run_memory(version)
    lcol, lhdr = ("| learn | notes ", "|--:|--:") if learns else ("", "")
    out = [f"### Harness `{version}`", "",
           f"| # | model | passes | runs | badges~ | ±sem | best {lcol}| tok in/run "
           f"| tok out/run | fallback | $ | $/run |",
           f"|--:|---|--:|--:|--:|--:|--:{lhdr}|--:|--:|--:|--:|--:|"]
    for i, r in enumerate(rows, 1):
        flag = " ⚠︎" if r.get("stale") else ""
        usd = cost(r["tokens_in_per_run"] * r["runs"],
                   r["tokens_out_per_run"] * r["runs"], (price or {}).get(r["model"]))
        lc = r.get("learning") or {}
        cell = ""
        if learns:
            d = lc.get("delta")
            cell = (f"| {'—' if d is None else f'{d:+.2f}'} "
                    f"| {r.get('notes_kept') if r.get('notes_kept') is not None else '—'} ")
        # Total and per-run side by side: the total says what this row cost, the
        # per-run says what another pass of it will cost.
        each = None if usd is None else usd / r["runs"]
        out.append(
            f"| {i} | `{r['model']}`{flag} | {r['passes']} | {r['runs']} | "
            f"**{r['badges_mean']}** | {r['badges_sem']} | {r['badges_best']} {cell}| "
            f"{r['tokens_in_per_run']} | {r['tokens_out_per_run']} | "
            f"{r['fallback_rate']} | {'—' if usd is None else f'{usd:.2f}'} "
            f"| {'—' if each is None else f'{each:.4f}'} |")
    if learns:
        out += ["", f"`learn` is the last {LEARN_K} runs of a pass minus its "
                    f"first {LEARN_K}, in the order played — this harness lets "
                    "the model keep notes between runs, so that column is what it "
                    "exists to measure. `badges~` is a mean over a learning curve "
                    "here."]
    return "\n".join(out)


def write_readme(price: dict[str, dict[str, float]] | None = None) -> Path:
    """Regenerates the table in llm-bench/README.md, newest harness first."""
    path = BENCH / "README.md"
    blocks = [markdown_table(v, price) for v in reversed(versions())]
    body = "\n\n".join(blocks) if blocks else "_Nothing measured yet._"
    generated = f"{README_BEGIN}\n\n{body}\n\n{README_END}"
    if path.is_file():
        text = path.read_text(encoding="utf-8")
        if README_BEGIN in text and README_END in text:
            head, _, rest = text.partition(README_BEGIN)
            _, _, tail = rest.partition(README_END)
            path.write_text(head + generated + tail, encoding="utf-8")
            return path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generated + "\n", encoding="utf-8")
    return path
