"""The model benchmark: one frozen harness, many models.

    uv run pokelike llm-bench --harness v0 --model openai/gpt-4o-mini

Different question from `bots/`. There, the prompt and the tools are the
submission and the model is usually whatever `$MODEL_ID` names — the leaderboard
ranks ideas. Here the harness is held still on purpose and the MODEL is the only
thing that moves, so a row says something about the model rather than about who
tuned their scaffold hardest.

The two feed each other in one direction. Ideas are discovered in `bots/`, where
anyone may change anything and the badge count decides whether it was a good
idea. When one earns it, it is folded into a NEW harness version here. Nothing
flows the other way, and nothing arrives from outside.

WHY THE VERSION IS A DIRECTORY. `llm-bench/v0/harness/bot.py` holds the harness
and `llm-bench/v0/results/` holds what was measured under it. Results live inside
the version rather than beside it so that pairing them wrongly is not a mistake
available to anyone. A harness improvement is `v1/`, a new directory; v0's rows
stay valid where they were earned and are never ranked against v1's, because two
models asked different questions were not compared.

WHAT IS RECORDED, AND WHAT IS NOT. Token counts in and out, per run, never money.
Prices change and a measurement should not rot because a provider ran a promotion,
so cost stays a function of these counts applied whenever it is asked for — from
OpenRouter's model list, at query time.

WHY PASSES AND NOT ONE NUMBER. An LLM run is not reproducible: same seed, same
prompt, different answer. So a model is measured more than once and every pass is
kept in full. Repeats over a FIXED seed list separate the two noise sources —
seed luck is already inside each pass's mean, so the spread ACROSS passes is the
model's own sampling noise. Without that, this benchmark would confidently rank
gaps it cannot resolve, which is the failure the `bots/` table has already been
caught committing over fifty seeds.
"""

from __future__ import annotations

import hashlib
import json
import statistics
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .bench import STANDARD_SEEDS, run_benchmark, summarise

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "llm-bench"
RENDER = Path(__file__).resolve().parent / "core" / "render.py"

README_BEGIN = "<!-- BEGIN llm-bench: generated by `pokelike llm-bench --table`, do not edit by hand -->"
README_END = "<!-- END llm-bench -->"


def versions() -> list[str]:
    """Harness versions on disk, oldest first."""
    if not BENCH.is_dir():
        return []
    found = [d.name for d in BENCH.iterdir()
             if d.is_dir() and (d / "harness" / "bot.py").is_file()]
    return sorted(found, key=lambda v: int(v.lstrip("v") or 0))


def harness_path(version: str) -> Path:
    p = BENCH / version / "harness" / "bot.py"
    if not p.is_file():
        have = ", ".join(versions()) or "none"
        raise FileNotFoundError(f"no harness at {p} (versions on disk: {have})")
    return p


def slug(model: str) -> str:
    """A model id as a filename. `openai/gpt-4o-mini` -> `openai--gpt-4o-mini`."""
    return model.replace("/", "--").replace(":", "-").replace(" ", "-")


def fingerprints(version: str) -> dict[str, str]:
    """What the measurement actually depended on.

    The harness, and the render module it renders the state with. The second one
    is not frozen — it is shared with the CLI — so it is fingerprinted instead:
    change it and every row that used it is marked rather than quietly meaning
    something new. See the header of the harness file.
    """
    sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()[:16]  # noqa: E731
    return {"bot.py": sha(harness_path(version)), "render.py": sha(RENDER)}


# ------------------------------------------------------------------- recording


def result_path(version: str, model: str) -> Path:
    return BENCH / version / "results" / f"{slug(model)}.json"


def record(version: str, model: str, one_pass: dict[str, Any]) -> Path:
    """Appends a pass to this model's file under this harness version.

    Appends rather than replaces, because two passes of the same model are the
    only way to know whether the gap to another model is bigger than the model's
    own variance.
    """
    path = result_path(version, model)
    if path.is_file():
        doc = json.loads(path.read_text(encoding="utf-8"))
    else:
        doc = {"model": model, "harness": version, "passes": []}
    # Recorded per pass, not per file: a pass played before render.py changed and
    # one played after are different measurements, and the file must be able to
    # say so rather than carrying one hash for both.
    doc["passes"].append(one_pass)
    doc["model"] = model
    doc["harness"] = version
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=1), encoding="utf-8")
    return path


def load(version: str) -> list[dict[str, Any]]:
    d = BENCH / version / "results"
    if not d.is_dir():
        return []
    return [json.loads(f.read_text(encoding="utf-8")) for f in sorted(d.glob("*.json"))]


# ------------------------------------------------------------------ statistics


def stats(doc: dict[str, Any], version: str | None = None) -> dict[str, Any]:
    """Pooled over every run of every pass, with the across-pass spread beside it.

    Statistics are derived here and never stored: the rows are the record, and a
    stored average is a number that cannot be checked and goes wrong silently when
    the definition changes.
    """
    passes = doc.get("passes") or []
    runs = [r for p in passes for r in (p.get("runs") or [])]
    if not runs:
        return {"model": doc.get("model"), "passes": 0, "runs": 0}

    badges = [r.get("badges") or 0 for r in runs]
    sd = statistics.stdev(badges) if len(badges) > 1 else 0.0
    per_pass = [
        statistics.mean([r.get("badges") or 0 for r in p["runs"]])
        for p in passes if p.get("runs")
    ]
    tok_in = sum(r.get("tokens_in") or 0 for r in runs)
    tok_out = sum(r.get("tokens_out") or 0 for r in runs)
    turns = sum(r.get("turns") or 0 for r in runs)
    falls = sum(r.get("fallbacks") or 0 for r in runs)

    out = {
        "model": doc.get("model"),
        "passes": len(passes),
        "runs": len(runs),
        "badges_mean": round(statistics.mean(badges), 3),
        # The number that decides whether any gap in this table is real.
        "badges_sem": round(sd / len(badges) ** 0.5, 3) if sd else 0.0,
        "badges_median": statistics.median(badges),
        "badges_best": max(badges),
        # Sampling noise on its own: the seeds are fixed, so what moves between
        # passes is the model.
        "pass_spread": round(max(per_pass) - min(per_pass), 3) if len(per_pass) > 1 else None,
        "tokens_in_per_run": round(tok_in / len(runs)),
        "tokens_out_per_run": round(tok_out / len(runs)),
        "tokens_total": tok_in + tok_out,
        "fallback_rate": round(falls / turns, 3) if turns else 0.0,
    }
    if version:
        now = fingerprints(version)
        used = {k: v for p in passes for k, v in (p.get("fingerprint") or {}).items()}
        out["stale"] = bool(used) and used != now
    return out


def cost(stat: dict[str, Any], usd_in_per_mtok: float, usd_out_per_mtok: float) -> float:
    """What a pass would have cost at the prices you pass in.

    Not stored anywhere and not fetched here on purpose: prices are somebody
    else's changing fact, and a benchmark that recorded them would be reporting
    history as though it were current.
    """
    runs = max(stat.get("runs") or 1, 1)
    return round(
        (stat.get("tokens_in_per_run", 0) * usd_in_per_mtok
         + stat.get("tokens_out_per_run", 0) * usd_out_per_mtok) * runs / 1e6, 4)


# ---------------------------------------------------------------------- running


def play_model(game, version: str, model: str, site: Path,
               seeds: list[int] | None = None) -> dict[str, Any]:
    """One pass: this model over the seed list, under this harness."""
    from .bot.catalogue import load_class

    seeds = seeds or STANDARD_SEEDS
    cls = load_class(harness_path(version))
    bot = cls(seed=0, model=model)

    # Token counts are per run: `on_start` resets them, so reading notes() once at
    # the end would report only the last of fifty runs. `on_run` hands back the row
    # itself, so each one carries what that run actually spent.
    def on_run(row: dict[str, Any], done: int, total: int) -> None:
        n = bot.notes()
        row.update(tokens_in=n.get("tokens_in", 0), tokens_out=n.get("tokens_out", 0),
                   calls=n.get("calls", 0), turns=n.get("turns", 0),
                   fallbacks=n.get("fallbacks", 0), retries=n.get("retries", 0))

    result = run_benchmark(
        game, bot, bot_name=f"{model} @ {version}", site=site, seeds=seeds,
        category="llm", description=f"model benchmark, harness {version}",
        on_run=on_run,
    )
    return _as_pass(version, model, seeds, result["runs"], result["game"],
                    result.get("notes") or {})


def _as_pass(version: str, model: str, seeds: list[int], runs: list[dict[str, Any]],
             game: dict[str, str], notes: dict[str, Any]) -> dict[str, Any]:
    turns = sum(r.get("turns") or 0 for r in runs)
    falls = sum(r.get("fallbacks") or 0 for r in runs)
    return {
        "recorded_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "model": model,
        "harness": version,
        "fingerprint": fingerprints(version),
        "game": game,
        "seeds": seeds,
        "summary": summarise(runs),
        "tokens_in": sum(r.get("tokens_in") or 0 for r in runs),
        "tokens_out": sum(r.get("tokens_out") or 0 for r in runs),
        "retries": sum(r.get("retries") or 0 for r in runs),
        "fallback_rate": round(falls / turns, 3) if turns else 0.0,
        "notes": notes,
        "runs": sorted(runs, key=lambda r: r["seed"]),
    }


# ------------------------------------------------------------------- in parallel
#
# Worth much more here than for a local bot. An LLM run is about twenty turns and
# one HTTP request each, so almost all of its wall clock is spent waiting on the
# provider rather than on this machine -- which means workers can outnumber cores
# and still help. Fifty seeds sequentially is half an hour; eight at a time is a
# few minutes, for the same tokens and the same money.
#
# Processes, not threads, and not by choice: Playwright's sync API is bound to the
# thread that created it, so one game per process is the only arrangement that
# works. `experiments/drrn/collect.py` fans out the same way for the same reason.
#
# Seeds are independent, so splitting them changes nothing about the result: the
# merged pass is what a sequential run would have produced, sorted back into seed
# order. Interleaved rather than in blocks, so a worker that draws a run of long
# games does not become the one everybody waits for.


def fan_out(version: str, model: str, seeds: list[int], workers: int,
            site: Path, port0: int = 8500) -> dict[str, Any]:
    """The same pass, played by several processes at once."""
    import queue
    import subprocess
    import sys
    import threading

    from tqdm import tqdm

    chunks = [seeds[k::workers] for k in range(workers)]
    chunks = [c for c in chunks if c]
    procs = []
    for k, chunk in enumerate(chunks):
        procs.append(subprocess.Popen(
            [sys.executable, "-m", "pokelike.llmbench", "--worker",
             "--harness", version, "--model", model, "--port", str(port0 + k),
             "--seeds", ",".join(str(s) for s in chunk)],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        ))

    # Rows arrive as they finish, from whichever worker finished them, so the bar
    # measures the whole pass rather than one process's share of it.
    rows: list[dict[str, Any]] = []
    q: queue.Queue = queue.Queue()

    def pump(p: Any) -> None:
        for line in p.stdout:
            line = line.strip()
            if line.startswith("{"):
                q.put(json.loads(line))
        q.put(None)

    for p in procs:
        threading.Thread(target=pump, args=(p,), daemon=True).start()

    bar = tqdm(total=len(seeds), desc=f"{model} @ {version}", unit="run", leave=True)
    ended = 0
    while ended < len(procs):
        item = q.get()
        if item is None:
            ended += 1
            continue
        rows.append(item)
        bar.update(1)
        done = [r for r in rows if r.get("badges") is not None]
        bar.set_postfix(
            badges=round(sum(r["badges"] for r in done) / len(done), 2) if done else None,
            tok=f"{sum(r.get('tokens_in', 0) + r.get('tokens_out', 0) for r in rows) / 1e6:.2f}M",
            fell=sum(r.get("fallbacks", 0) for r in rows),
        )
    bar.close()

    # All or nothing. A pass with 43 of 50 seeds in it is worse than no pass: the
    # mean would be over whichever seeds happened to survive, and nothing in the
    # file would say so.
    for k, p in enumerate(procs):
        p.wait()
        if p.returncode != 0:
            err = (p.stderr.read() or "").strip()[-600:]
            raise RuntimeError(
                f"worker {k} exited {p.returncode}; discarding the whole pass "
                f"rather than recording a partial one.\n{err}"
            )
    if len(rows) != len(seeds):
        raise RuntimeError(
            f"expected {len(seeds)} runs, collected {len(rows)}; discarding the pass"
        )

    from .bench import bundle_fingerprint
    return _as_pass(version, model, seeds, rows, bundle_fingerprint(site), {})


def _worker() -> int:
    """One process, one browser, its slice of the seeds. Prints a JSON row each."""
    import argparse

    from .assets.server import AssetServer
    from .bot.catalogue import load_class
    from .core.game import Game
    from .runner import play_run

    p = argparse.ArgumentParser()
    p.add_argument("--worker", action="store_true")
    p.add_argument("--harness", required=True)
    p.add_argument("--model", required=True)
    p.add_argument("--port", type=int, required=True)
    p.add_argument("--seeds", required=True)
    a = p.parse_args()

    seeds = [int(s) for s in a.seeds.split(",") if s]
    cls = load_class(harness_path(a.harness))
    bot = cls(seed=0, model=a.model)
    server = AssetServer(ROOT / "site", port=a.port)
    server.start()
    game = Game(url=server.url)
    game.open()
    try:
        for seed in seeds:
            full = play_run(game, bot, seed, max_steps=400)
            n = bot.notes()
            row = {k: full[k] for k in ("seed", "steps", "score", "badges", "maps",
                                        "kos", "faints", "ending", "stalled")}
            row.update(tokens_in=n.get("tokens_in", 0), tokens_out=n.get("tokens_out", 0),
                       calls=n.get("calls", 0), turns=n.get("turns", 0),
                       fallbacks=n.get("fallbacks", 0), retries=n.get("retries", 0))
            print(json.dumps(row), flush=True)
    finally:
        game.close()
        server.stop()
    return 0


if __name__ == "__main__":
    raise SystemExit(_worker())


# ----------------------------------------------------------------------- table


def format_table(version: str) -> str:
    rows = [stats(d, version) for d in load(version)]
    rows = [r for r in rows if r.get("runs")]
    if not rows:
        return f"no models measured under harness {version} yet"
    rows.sort(key=lambda r: -r["badges_mean"])
    head = (f"{'model':<34}{'passes':>7}{'runs':>6}{'badges~':>9}{'±sem':>7}"
            f"{'med':>5}{'best':>6}{'tok in/run':>11}{'tok out/run':>12}{'fallback':>9}")
    out = [head, "-" * len(head)]
    for r in rows:
        out.append(
            f"{str(r['model'])[:33]:<34}{r['passes']:>7}{r['runs']:>6}"
            f"{r['badges_mean']:>9}{r['badges_sem']:>7}{r['badges_median']:>5}"
            f"{r['badges_best']:>6}{r['tokens_in_per_run']:>11}"
            f"{r['tokens_out_per_run']:>12}{r['fallback_rate']:>9}"
            + ("  <- harness or render changed since this ran" if r.get("stale") else "")
            + ("  <- fallback over 0.1: measuring the harness, not the model"
               if r["fallback_rate"] > 0.1 else "")
        )
    out += ["-" * len(head),
            f"harness {version}, {len(STANDARD_SEEDS)} fixed seeds a pass. Two models "
            f"whose means differ by less than about",
            "twice the ±sem are not distinguishable here — read that column before "
            "reading the order."]
    return "\n".join(out)


def markdown_table(version: str) -> str:
    rows = [stats(d, version) for d in load(version)]
    rows = [r for r in rows if r.get("runs")]
    if not rows:
        return f"_No models measured under harness `{version}` yet._"
    rows.sort(key=lambda r: -r["badges_mean"])
    out = [f"### Harness `{version}`", "",
           "| # | model | passes | runs | badges~ | ±sem | best | tok in/run | tok out/run | fallback |",
           "|--:|---|--:|--:|--:|--:|--:|--:|--:|--:|"]
    for i, r in enumerate(rows, 1):
        flag = " ⚠︎" if r.get("stale") else ""
        out.append(
            f"| {i} | `{r['model']}`{flag} | {r['passes']} | {r['runs']} | "
            f"**{r['badges_mean']}** | {r['badges_sem']} | {r['badges_best']} | "
            f"{r['tokens_in_per_run']} | {r['tokens_out_per_run']} | {r['fallback_rate']} |")
    return "\n".join(out)


def write_readme() -> Path:
    """Regenerates the table in llm-bench/README.md, newest harness first."""
    path = BENCH / "README.md"
    blocks = [markdown_table(v) for v in reversed(versions())]
    body = "\n\n".join(blocks) if blocks else "_Nothing measured yet._"
    generated = f"{README_BEGIN}\n\n{body}\n\n{README_END}"
    if path.is_file():
        text = path.read_text(encoding="utf-8")
        if README_BEGIN in text and README_END in text:
            head, _, rest = text.partition(README_BEGIN)
            _, _, tail = rest.partition(README_END)
            path.write_text(head + generated + tail, encoding="utf-8")
            return path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generated + "\n", encoding="utf-8")
    return path
