"""Building and formatting the standings from measured results on disk."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ...bot.catalogue import BOTS
from .record import load_results


def build_index(root: Path | None = None) -> dict[str, Any]:
    """Regenerates index.json from whatever is measured on disk."""
    base = Path(root) if root else BOTS
    rows = []
    for e in load_results(base):
        s = e.get("summary") or {}
        notes = e.get("notes") or {}
        entry = {
            "bot": e.get("bot"), "author": e.get("author"),
            "category": e.get("category"), "description": e.get("description"),
            "score_mean": s.get("score_mean"), "score_stdev": s.get("score_stdev"),
            "score_best": s.get("score_best"), "badges_mean": s.get("badges_mean"),
            "badges_best": s.get("badges_best"), "maps_mean": s.get("maps_mean"),
            "completed": s.get("completed"), "runs": s.get("runs"),
            "game": (e.get("game") or {}).get("sha256"),
            # LLM-specific metadata for the models sub-table.
            "model": notes.get("model"),
            "harness": notes.get("harness"),
            "fallback_rate": notes.get("fallback_rate"),
            "stock_tools": notes.get("stock_tools"),
            "state_view": notes.get("state_view"),
            "fingerprint": (e.get("fingerprint") or "")[:12],
            "stale": e.get("stale", False),
            "unverified": e.get("unverified", False),
            "artifacts": len(e.get("artifacts") or []),
        }
        # Only stored when not kanto, so existing index files stay identical.
        if e.get("region") and e["region"] != "kanto":
            entry["region"] = e["region"]
        rows.append(entry)
    # Ranked by badges, not score: the engine's score formula rewards fighting
    # more than it rewards progress. See experiments/env/rewards.py.
    rows.sort(key=lambda r: (
        r["badges_mean"] is None, -(r["badges_mean"] or 0), -(r["score_mean"] or 0)
    ))
    index = {"entries": rows}
    base.mkdir(parents=True, exist_ok=True)
    (base / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8")
    render_readme(base, index)
    return index


README_BEGIN = "<!-- BEGIN standings: generated by `pokelike bot board`, do not edit by hand -->"
README_END = "<!-- END standings -->"


def as_markdown(index: dict[str, Any]) -> str:
    """Returns the standings as a markdown table, ranked by badges."""
    rows = index.get("entries") or []
    if not rows:
        return ("_No bots measured yet._ Yours would be the first, see "
                "[CONTRIBUTING.md](../CONTRIBUTING.md).\n")
    out = [
        "| # | bot | author | how | runs | badges~ | badges+ | score~ | best | code |",
        "|--:|---|---|---|--:|--:|--:|--:|--:|---|",
    ]
    for i, r in enumerate(rows, 1):
        n = lambda k, d="-": r[k] if r.get(k) is not None else d  # noqa: E731
        mark = " ⚠︎" if r.get("stale") else (" ?" if r.get("unverified") else "")
        out.append(
            f"| {i} | **[{r.get('bot')}]({r.get('bot')}/)** | {r.get('author') or '-'} "
            f"| {r.get('category') or '-'} | {n('runs', 0)} "
            f"| **{n('badges_mean')}** | {n('badges_best')} "
            f"| {n('score_mean')} | {n('score_best')} | `{r.get('fingerprint') or '-'}`{mark} |"
        )

    # LLM sub-table: shows model, harness version, and fallback rate.
    llm = [r for r in rows if r.get("model")]
    if llm:
        out += ["", "**Models.**", "",
                "| bot | model | harness | sees | tools | fallback rate |",
                "|---|---|--:|---|---|--:|"]
        for r in llm:
            rate = r.get("fallback_rate")
            flag = " ⚠︎" if rate is not None and rate > 0.1 else ""
            stock = r.get("stock_tools")
            tools = "shared" if stock else ("own ⚠︎" if stock is False else "-")
            out.append(f"| {r.get('bot')} | `{r.get('model')}` | {r.get('harness', '-')} "
                       f"| {r.get('state_view') or '-'} | {tools} "
                       f"| {rate if rate is not None else '-'}{flag} |")
        out += ["",
                "An LLM result is **not reproducible**: providers change models behind a "
                "fixed name and sampling is stochastic. `fallback rate` is the share of "
                "turns the model did not decide, played instead by the harness's backup "
                "heuristic. **⚠︎ above 0.1 means the row is measuring us more than the "
                "model**. `harness` is the version of the shared loop in "
                "`pokelike/bot/llm.py`; rows measured under different numbers were not "
                "asked the same question. `tools` says whether the model was "
                "offered the shared four or a set of the bot's own. **Own ⚠︎ is "
                "not a fault**, it is a different question, and comparing it "
                "with the rest as though it were the same one is."]
    out += [
        "",
        "Ranked by **badges**, the game's own progress counter. `badges~` is the mean "
        "over the standard 50 seeds, `badges+` the best single run. `code` is a "
        "fingerprint over the bot and its artifacts; **⚠︎ means the files changed "
        "since the score was measured**, so the row no longer describes what is on "
        "disk, and **? means the result carries no fingerprint at all** and cannot "
        "be checked either way. Re-running the benchmark clears both.",
        "",
    ]
    return "\n".join(out)


def render_readme(root: Path, index: dict[str, Any]) -> Path | None:
    """Writes the standings into bots/README.md, between the marker comments."""
    readme = Path(root) / "README.md"
    if not readme.is_file():
        return None
    text = readme.read_text(encoding="utf-8")
    begin, end = text.find(README_BEGIN), text.find(README_END)
    if begin < 0 or end < 0:
        return None
    readme.write_text(
        text[:begin] + README_BEGIN + "\n\n" + as_markdown(index) + "\n" + text[end:],
        encoding="utf-8",
    )
    return readme


def format_table(index: dict[str, Any]) -> str:
    """Returns the standings as a fixed-width terminal table."""
    rows = index.get("entries") or []
    if not rows:
        return "no bots measured yet"
    # Show region column only when at least one entry is not kanto.
    show_region = any(r.get("region") and r["region"] != "kanto" for r in rows)
    head = (f"{'bot':<20}{'category':>10}"
            + (f"{'region':>9}" if show_region else "")
            + f"{'runs':>6}{'badge~':>8}{'badge+':>8}"
            f"{'score~':>9}{'stdev':>8}{'best':>7}{'done':>6}")
    out = ["bots on the standard 50 seeds. Each scaffold is its author's, so this "
           "ranks ideas.",
           "", head, "-" * len(head)]
    for r in rows:
        v = lambda k: r[k] if r.get(k) is not None else "-"  # noqa: E731
        out.append(
            f"{(r['bot'] or '')[:19]:<20}{(r['category'] or ''):>10}"
            + (f"{(r.get('region') or 'kanto'):>9}" if show_region else "")
            + f"{r['runs'] or 0:>6}"
            f"{v('badges_mean'):>8}{v('badges_best'):>8}{v('score_mean'):>9}"
            f"{v('score_stdev'):>8}{v('score_best'):>7}{v('completed'):>6}"
            + ("  <- code changed since this was measured" if r.get("stale")
               else "  <- no fingerprint: cannot be checked" if r.get("unverified") else "")
        )
    return "\n".join(out)
