"""General commands: setup, mirror, play, api, schema, history."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from ....assets.mirror import build
from ....core import render
from ....core.game import IllegalAction
from ....stats import format_summary, record, recent, summary
from ..shared import (MISSING_DEPS_HELP, SITE_ROOT, _server_and_game,
                      browser_works)

# The state reference is generated into STATE.md between these two lines.
STATE_BEGIN = "<!-- BEGIN state-reference: generated by `pokelike schema --markdown`, do not edit by hand -->"
STATE_END = "<!-- END state-reference -->"

REPL_HELP = """
commands:
  <number>   take the action with that number
  w a b      swap team slots a and b (slot 0 leads; free, does not use the turn)
  s          show the score
  j          show the raw state as JSON
  l          show the legend of map symbols
  n          new run
  q          quit
"""


def cmd_setup(args) -> int:
    """Gets everything ready: browser + offline copy. Run once."""
    import subprocess

    print("[1/3] downloading the headless browser (~120 MB)")
    r = subprocess.run(
        [sys.executable, "-m", "playwright", "install", "chromium", "--only-shell"]
    )
    if r.returncode != 0:
        print("browser installation failed", file=sys.stderr)
        return r.returncode

    print("[2/3] checking it actually starts")
    ok, why = browser_works()
    if not ok:
        print("\n  the browser does not start.\n", file=sys.stderr)
        if "missing dependencies" in why or "error while loading shared libraries" in why:
            print(MISSING_DEPS_HELP, file=sys.stderr)
        else:
            print(f"  {why[:600]}", file=sys.stderr)
        return 3
    print("      ok")

    if (SITE_ROOT / "index.html").is_file() and not args.force:
        print(f"[3/3] offline copy already in {SITE_ROOT}, skipping")
        print("      (use --force to rebuild it)")
    else:
        print("[3/3] downloading the game for offline use (~130 MB, a few minutes)")
        build(SITE_ROOT)

    print("\nReady. Try:  pokelike play")
    return 0


def cmd_mirror(args) -> int:
    build(SITE_ROOT, phases=args.phase)
    return 0


def cmd_play(args) -> int:
    server, game = _server_and_game(args)
    try:
        obs = game.reset(seed=args.seed)
        print(f"\nnew run, seed {args.seed}")
        if args.shots:
            print(f"images in {args.shots}/")
        print(REPL_HELP)
        while True:
            print()
            print(render.screen(obs))
            if args.shots:
                f = game.screenshot(Path(args.shots) / f"{game.steps:03d}-{obs['screen']}.png")
                print(f"\n[image: {f}]")
            if obs.get("done"):
                print()
                print(render.score_view(game.score()))
                print("\n('n' for another run, 'q' to quit)")

            try:
                line = input("\n> ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                print()
                return 0

            if line in {"q", "quit", "exit"}:
                return 0
            if line == "n":
                args.seed += 1
                obs = game.reset(seed=args.seed)
                print(f"\nnew run, seed {args.seed}")
                continue
            if line == "s":
                print()
                print(render.score_view(game.score()))
                continue
            if line == "j":
                print(json.dumps(game.state(), indent=1, ensure_ascii=False))
                continue
            if line == "l":
                print()
                print(render.LEGEND)
                continue
            if line.startswith("w"):
                bits = line.split()
                if len(bits) != 3 or not all(b.isdigit() for b in bits[1:]):
                    print("usage: w <slot> <slot>, e.g. 'w 0 2'")
                    continue
                try:
                    obs = game.reorder(int(bits[1]), int(bits[2]))
                except IllegalAction as e:
                    print(e)
                continue
            if line in {"?", "h", "help"}:
                print(REPL_HELP)
                continue
            if not line.isdigit():
                print("did not understand: type a number, or '?' for help")
                continue

            try:
                obs = game.step(int(line))
            except IllegalAction as e:
                print(f"action refused: {e}")
    finally:
        game.close()
        server.stop()


def cmd_api(args) -> int:
    from ...api.server import serve

    server, game = _server_and_game(args)
    try:
        # A run is ready as soon as the server starts, so GET /state answers
        # right away without having to POST /new first.
        game.reset(seed=args.seed)
        print(f"API on http://127.0.0.1:{args.api_port}/   (ctrl-c to stop)")
        print(f"run ready with seed {args.seed}."
              f"  Try:  curl 127.0.0.1:{args.api_port}/state")
        serve(game, port=args.api_port)
        return 0
    finally:
        game.close()
        server.stop()


def cmd_schema(args) -> int:
    """Prints what a bot receives, captured from a live run."""
    from ....core.schema import as_markdown, capture, describe

    server, game = _server_and_game(args)
    try:
        obs = capture(game)
    finally:
        game.close()
        server.stop()

    if args.json:
        print(json.dumps(obs, indent=1))
    elif args.markdown:
        # Written into STATE.md rather than into the README. It is 420 lines of
        # generated reference, which is longer than everything a reader needs to
        # decide whether the project is for them, and it pushed the rest of the
        # page out of reach.
        out = Path(__file__).resolve().parents[5] / "STATE.md"
        text = out.read_text(encoding="utf-8")
        begin, end = text.find(STATE_BEGIN), text.find(STATE_END)
        if begin < 0 or end < 0:
            print(f"markers not found in {out}: expected\n  {STATE_BEGIN}\n  {STATE_END}",
                  file=sys.stderr)
            return 2
        out.write_text(
            text[:begin] + STATE_BEGIN + "\n" + as_markdown(obs) + "\n" + text[end:],
            encoding="utf-8",
        )
        print(f"state reference written into {out}")
    else:
        print(describe(obs))
    return 0


def cmd_stats(args) -> int:
    print(format_summary(summary(), explain=args.explain))
    if args.recent:
        print()
        for r in recent(args.recent, bot=args.bot):
            print(f"  #{r['id']:<5} {r['played_at']}  {r['bot']:<10} seed {r['seed']:<5}"
                  f" steps {r['steps']:>3}  {r['ending']:<16} score {r['points']}")
    return 0
