"""The frozen harness for the model benchmark, v3: the same loop, better eyes.

WHAT THIS IS. v2's agent loop unchanged, with two corrections to what the model is
looking at. Every model measured under v3 was asked exactly the questions this file
asks.

WHY IT IS A VERSION AND NOT A FIX. Neither change is an improvement to the agent
loop, and neither could be applied to v2. Both alter what the model reads, so a v2
row and a v3 row are answers to different questions, and the only honest way to hold
both is a new directory.

WHAT CHANGED FROM v2, AND WHY EACH.

  1. THE NODE TOOLTIPS. The game puts text under the pointer on every map node: the
     trainer's archetype and which types they use, a gym leader's roster with levels,
     what a trade or an item node does. `Officer - +2 Levels - Fire Pokemon`.
     `Brock - Rock Gym | Geodude Lv12 | Onix Lv14`.

     Under v0 to v2 none of it was in the state at all. So the benchmark was not
     measuring how well a model plays this game with the information a player has,
     it was measuring how well it plays half blind, and a person reading the same
     terminal was choosing blind too. That is a defect in the instrument, not a
     difficulty setting.

     It is read by calling the engine's own `getNodeLabel`, so it cannot drift from
     what is displayed, and unrevealed nodes are skipped. Expect this to help, and
     expect it to help the careful models most: under v0 the ranking followed input
     per run, which is to say it followed how much a model had bothered to look at.
     Now looking is worth more.

  2. THE MOVE TUTOR BLOCK, ONLY AT THE TUTOR. Under v0 to v2 it was printed on every
     turn, because the bridge fills `offered_moves` unconditionally and nothing gated
     on the screen. Measured on seed 10000: it was on 11 of the first 13 turns, and
     not one of them was a tutor. 187 characters a turn, on the order of 58k tokens
     across a pass, describing an exchange that was not on offer.

     A model that reasoned about it was reasoning about nothing, and one that ignored
     it paid for the tokens anyway.

  3. AND ONE THING THAT IS NOT ABOUT LOOKING. The journal records what was DONE,
     from the harness's own data, with the model's sentence kept underneath and
     labelled as its own. v0 to v2 recorded only the sentence, under a heading
     reading YOUR RECENT MOVES, so the model read its own guesses back as a record of
     events. It matters more here than under v0, because v2 also carries the last
     three turns verbatim: two channels for the model's reasoning, one of them
     labelled as fact.

WHAT DID NOT CHANGE. The prompt, the eight tools, the scratchpad of three turns,
twelve notes across runs, six tool rounds, 4000 tokens an answer, temperature 0.
Everything v2 said about why those are what they are still stands.

SO WHAT DOES A v3 ROW MEAN. "How well does this model play when told the rules and
how to use the loop, seeing what a person sees." v0 asked how well it plays told only
the rules. v2 asked the same as v3 minus the eyes. Three questions, three tables;
comparing across them mixes the change with the answer.

WHAT TO EXPECT, WRITTEN DOWN FIRST SO IT CANNOT BE ADJUSTED AFTERWARDS. Badges up
and input per run roughly flat: the tooltips add a few hundred characters a turn and
the tutor block removes about as many. If badges do NOT move, that is the more
interesting result, and it says the models were not losing for want of information.

THIS IS AN EXPERIMENT, NOT AN IMPROVEMENT. v2's rows stay valid under v2.

**DO NOT EDIT THIS FILE.** Once a result exists under `../results/`, editing it
makes every one of those rows a claim about code that no longer exists. The next
idea is `llm-bench/v4/harness/bot.py`, a fresh directory, and these rows stay valid
under v3 where they were earned. That is why the version is in the path rather than
in a variable.

WHY IT IS A COPY AND NOT AN IMPORT. The shared harness in `src/pokelike/bot/llm.py`
is meant to evolve -- it serves the submissions in `bots/`, and a good idea found
there should reach every future LLM bot. That is the opposite of what a benchmark
needs. If this file imported the shared one, the next improvement made for a
submission would silently change what every recorded model score meant.

WHAT ELSE IS FROZEN IN THIS DIRECTORY. Three more files, and the reason is the same
one:

  render.py   the text the model reads. Used to be `pokelike.core.render`, shared
              with the CLI and merely fingerprinted, on the argument that copying it
              would be worse than the problem. That failed the first time the shared
              renderer had a defect: the MOVE TUTOR bug above could not be fixed for
              the person at the terminal without marking every score ever recorded.
  bridge.js   what is in the state at all, and the ORDER `actions` come in. A bot
              answers with an index into that list, so reordering does not change
              what the model sees, it changes what its answer means.
  init.js     the seeded Math.random and the pinned clock. The run seed is built
              from both, so moving a constant here does not mark a recorded score,
              it voids it: every seed would map to a different run.

WHAT IS STILL SHARED, AND HOW THAT IS CAUGHT. `browser.py`, `game.py` and
`runner.py` drive the game, and freezing them too would mean each harness carrying
its own browser plumbing. Every result records a sha256 of the four frozen files and
of those three, plus the name and hash of the game bundle, and the table marks a row
when any of them stops matching what is on disk. Drift is reported rather than
absorbed.

Generated mechanically from v2, never transcribed by hand.
"""

from __future__ import annotations

import importlib.util
import json
import os
import random
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from pokelike.bot.base import Bot

# The renderer is the COPY beside this file, loaded by path rather than imported.
#
# Two reasons it cannot be a plain import. `load_class` runs a harness with
# `spec_from_file_location` and no parent package, so `from . import render` has
# nothing to be relative to. And every harness directory is named `harness`, so
# all three versions would land on the same name in `sys.modules` and shadow one
# another; the version directory is what makes this one unique.
_HERE = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location(
    f"pokelike_harness_{_HERE.parent.name}_render", _HERE / "render.py"
)
render = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = render
_spec.loader.exec_module(render)

# How a decision is made here. Written into every result; a row measured under a
# different number is marked as such rather than ranked as if it were the same.
#
#   1  agentic loop with team_details / what_lies_ahead / set_lead / play,
#      situation rendered by core.render.screen, prose index as a last resort
#   2  the above plus remember / revise / forget, notes carried between runs,
#      six tool rounds instead of four
#   3  the above plus a scratchpad of the last few turns carried within a run,
#      a `plan` tool for the route through the map, and 4000 tokens an answer
#   4  the above, with the node tooltips a person can read, and a journal that
#      separates what was done from what the model said about it
HARNESS = 4


# ---------------------------------------------------------------- what is true
#
# The rules are shared, the strategy is not. The split matters: everything below
# is a FACT about the game, several of them read out of the bundle rather than
# guessed, and a benchmark where each bot restates the facts measures who copied
# them correctly instead of who plays better.
#
# The two that are easy to get wrong, and were:
#
#   * BADGES ARE THE GOAL. The engine's score formula was written for the Battle
#     Tower and two of its six terms never fire in Story mode, so a prompt that
#     chases "maps cleared" points the model at something that is always zero.
#     An earlier version of this prompt did exactly that.
#   * Choosing a node CLOSES the others on that layer, forever.

GAME_RULES = """You are playing Pokelike, a Pokemon roguelike.

YOUR GOAL: earn as many gym badges as you can before your team is wiped out.
Badges measure how far you got. A run ends when every Pokemon has fainted.

HOW A TURN WORKS
- The map is a layered graph running top to bottom, with a boss at the bottom.
- You pick one node from the legal ones. The moment you pick, every other node on
  that layer CLOSES FOREVER. The choice is irreversible and it also decides which
  nodes you will be able to reach next.
- Battles resolve themselves. You never choose moves. What you decide is where to
  go, who to catch, which item to take and who to give it to.
- Your team holds up to 6 Pokemon.

NODE TYPES
  o catch        adds a Pokemon to your team
  x wild fight   one wild Pokemon, gives experience
  T trainer      1 Pokemon on map 0, 2 on maps 1-2, 3 from map 3 onwards
  i item         an item to equip or keep
  + pokecenter   restores HP
  ? unknown      only revealed when you enter it
  $ trade        M move tutor    S shop    B boss

WHAT ACTUALLY KILLS RUNS
Losing Pokemon. Every faint is permanent for that run, and once the team is empty
it is over, no matter how well you were doing.

WHAT YOU REMEMBER, AND FOR HOW LONG
Four different things, with four different lifetimes. Knowing which is which is
most of playing this well.

  1. THIS TURN. The screen above, plus anything you ask a tool.

  2. YOUR LAST FEW TURNS, in full. The exchanges of the previous three turns come
     with you: your own words, the tools you called, what they answered. This is
     why you do not have to re-derive what you worked out a moment ago -- read it
     instead. If you wrote "the team is too weak for the boss, level up first",
     that sentence is still in front of you.

  3. YOUR PLAN FOR THIS MAP, if you write one. Shown every turn until you replace
     it. It dies with the map.

  4. YOUR NOTES, which OUTLIVE THE RUN. This is the only thing that crosses from
     one game into the next. Everything else is gone when your team is wiped out.

HOW TO USE YOUR NOTES -- READ THIS, MOST PLAYERS IGNORE IT
You get twelve notes of 160 characters. They are shown to you every single turn,
numbered, so you never need to ask for them.

  `remember` -- write a lesson you want to have in the NEXT run, not a reminder for
      later this turn. Good: "trainer nodes on map 0 are safe with a level 8 lead".
      "Skipping the pokecenter before a boss lost me the run three times." Useless:
      "I am on map 1", which will be false in a minute.
  `revise`   -- sharpen one when you learn it was nearly right. Notes are worth more
      when they are specific: a number in a note beats an adjective.
  `forget`   -- delete one that was wrong, or make room for a better one.

The cap is the point. Once you hold twelve, the only way to record something better
is to improve or drop an old one, so treat them as your twelve most valuable
beliefs about this game rather than a diary. When you die, the notes are all you
keep -- so before your team is wiped out, it is worth writing down what killed you.

HOW TO PLAY WELL
Nobody has told you the optimal strategy, because nobody knows it. What follows is
sound reasoning from the rules above, and your notes are how you improve on it.

  - LOOK BEFORE YOU CLOSE A DOOR. A map choice closes every alternative on that
    layer forever AND decides what you can reach next, so call `what_lies_ahead`
    before choosing on the map. A node that looks worse but keeps two paths open is
    often better than a slightly better node that funnels you into one.
  - DECIDE THE ROUTE EARLY. Write a `plan` before your first choice on a map, while
    every option is still open. Losing usually traces back to a choice made many
    turns before the turn where you died.
  - LEVEL BEFORE THE BOSS, NOT DURING. Trainers carry more Pokemon than wild fights
    and give correspondingly more experience. The gym is at the bottom of the map,
    you can see it coming, and arriving under-levelled is the common way to stop at
    one badge.
  - HEAL BEFORE THE BOSS. The pokecenter is the only thing that restores HP, and a
    boss fought at half health costs Pokemon you cannot replace.
  - BREADTH EARLY, DEPTH LATER. Early catches are cheap insurance: a team of one is
    one faint from the end of the run. Check `team_details` rather than assuming.
  - THE LEAD MATTERS AND IS FREE. `set_lead` does not consume your turn, so put a
    healthy, well-matched Pokemon in front before a fight instead of after.
"""

CLOSING = """
Before you decide: read your notes above, read what you said in your last turns, and
check your plan. Use `remember` whenever this run teaches you something that will
still be true in the next one -- that is the only thing you get to keep.

Think briefly, then call `play` with your chosen index. Always call `play`."""


# ---------------------------------------------------------------------- tools
#
# Shared by default for the same reason the rules are: a model given a tool
# another model was not is not being compared, it is being helped.
#
# A bot may still add its own, or replace these outright -- see `tools()` and
# `run_tool()` on HarnessV3. What it may not do is hide that it did: the tool names
# go into every result and a bot whose set differs from the shared one is
# marked in the standings, so its row is read as the different question it is.

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "team_details",
            "description": "Full team stats: HP, levels, types, held items.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "what_lies_ahead",
            "description": (
                "For each legal action, which nodes it leads to on the next layer. "
                "Useful to avoid closing off good paths: this choice decides what "
                "you will be able to do next."
            ),
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "set_lead",
            "description": (
                "Move a team member to slot 0, so they enter the next battle first. "
                "Free: it does not use the turn, and you still have to call play "
                "afterwards. Only offered on the map screen."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "index": {"type": "integer", "description": "team slot to promote"},
                },
                "required": ["index"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "remember",
            "description": (
                "Write down something you have learned about this game, to be shown "
                "back to you on every later turn AND in later runs. Use it for "
                "lessons that will still be true next time, not for what is on "
                "screen now. Keep each note short and concrete."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "note": {"type": "string", "description": "one lesson, one sentence"},
                },
                "required": ["note"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "revise",
            "description": (
                "Replace one of your notes with a better version of it. Use this "
                "when a lesson turns out to be half right: your notes are capped, "
                "so sharpening one is often worth more than adding another."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer", "description": "which note, as numbered"},
                    "note": {"type": "string", "description": "what it should say instead"},
                },
                "required": ["id", "note"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "forget",
            "description": (
                "Delete one of your notes. Worth doing when a lesson was wrong, or "
                "when you need the room for a better one."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer", "description": "which note, as numbered"},
                },
                "required": ["id"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "plan",
            "description": (
                "Write down the route you mean to take through this map, and why. "
                "It is shown back to you every turn until you change it, so it is "
                "how a decision made now reaches the turn that has to honour it. "
                "Calling this again replaces it. Choosing a node closes every other "
                "node on that layer forever, so the order you take them in is most "
                "of the game."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "route": {
                        "type": "string",
                        "description": "the plan, in a sentence or two",
                    },
                },
                "required": ["route"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "play",
            "description": "Perform the chosen action and end the turn.",
            "parameters": {
                "type": "object",
                "properties": {
                    "index": {"type": "integer", "description": "index of the legal action"},
                    "why": {"type": "string", "description": "one sentence on the reason"},
                },
                "required": ["index", "why"],
            },
        },
    },
]


_STOCK_TOOL_NAMES = [t["function"]["name"] for t in TOOLS]


class LLMError(RuntimeError):
    """Something went wrong on one call. Recoverable: fall back and play on."""


class LLMConfigError(LLMError):
    """The setup is wrong and every call will fail the same way.

    A bad token, a model name the endpoint does not serve, a URL that is not an
    OpenAI-compatible API. Falling back on these would play a whole run on the
    backup heuristic and report it as an LLM result, which, in a benchmark, puts
    an entry on the leaderboard labelled `llm` that no model ever played.
    So these stop the run instead.
    """


class LLMBudgetError(LLMError):
    """The run asked for more tokens than the bot allowed itself.

    Only raised when a bot sets `TOKEN_BUDGET`. A model that thinks ten times
    longer than the others is not straightforwardly better than them, and over
    fifty runs the difference is money, so a bot may declare a ceiling and be
    held to it rather than discovering the bill afterwards.
    """


# ------------------------------------------------------------------------ bot


class HarnessV3(Bot):
    """A bot that asks a model what to do, one call per turn.

    Subclass it and set `PROMPT`. Everything else has a working default.

    | attribute      | what it decides                                        |
    |----------------|--------------------------------------------------------|
    | `PROMPT`       | the system prompt: **this is your submission**          |
    | `MODEL`        | model id, or None to take `$MODEL_ID`                   |
    | `TEMPERATURE`  | sampling                                               |
    | `MAX_TOKENS`   | ceiling on one answer                                  |
    | `MAX_ROUNDS`   | tool rounds before the turn is given up on             |
    | `MEMORY`       | how many past turns are shown back to the model        |
    | `TOKEN_BUDGET` | tokens per run, 0 for no ceiling                       |
    | `EXTRA_TOOLS`  | tools of your own, on top of the shared eight           |
    | `STATE_VIEW`   | **what the model reads each turn**                      |

    `STATE_VIEW` is the one to think hardest about, because it decides what the
    model is looking at rather than what it is told to do:

    | value | what the model gets | roughly |
    |---|---|--:|
    | `"screen"` | the ASCII view a person sees. The default | 880 chars |
    | `"json"` | the whole state dict, compact JSON | 5900 chars |
    | `"both"` | the view, then the dict under it | 6800 chars |
    | `["team", "actions"]` | just those keys, as JSON | varies |

    Six times the tokens is the price of `"json"`, and it is not only money:
    filling the context with a map the turn does not need takes room from the
    reasoning it was about to do. The default drops real things -- the engine's
    type/item table, the map edges, raw base stats -- because it renders what a
    person would look at, not everything that is true. Which of those matters is
    an experiment, which is why this is a knob and not our decision.

    `view(state)` is the escape hatch when none of the settings fit. Override it and
    return whatever string you like; the journal and the "pick an index"
    instruction are added around it by the harness, so you cannot break them by
    forgetting them.

    To give the model something the shared tools do not offer, declare it in
    `EXTRA_TOOLS` and answer it in `run_tool`:

        class MyBot(HarnessV3):
            EXTRA_TOOLS = [{
                "type": "function",
                "function": {
                    "name": "bag",
                    "description": "What you are carrying.",
                    "parameters": {"type": "object", "properties": {}},
                },
            }]

            def run_tool(self, name, args, state):
                if name == "bag":
                    return ", ".join(state.get("bag") or []) or "(empty)"
                return super().run_tool(name, args, state)

    Replacing the shared set entirely is `tools()`. Both are allowed and both
    are recorded: a bot with its own tools is answering a different question
    from one without, and the standings say so rather than ranking them as
    though they had been asked the same thing.

    On `MODEL`: pin it in the bot file if you want a leaderboard row that means
    one specific model. The id is not a secret, and pinning it puts it inside
    the fingerprint, so swapping the model shows as a changed bot. Leave it None
    and the bot plays whatever `$MODEL_ID` names, which is what you want while
    experimenting and what the four prompt bots shipped in `bots/` do.
    """

    name = "llm-bench-v2"

    HARNESS = HARNESS
    PROMPT = GAME_RULES + CLOSING
    MODEL: str | None = None
    TEMPERATURE = 0.0
    # 1500 in v0 and v1, and that number DISQUALIFIED a model rather than
    # measuring it: openai/gpt-5-nano spent more output than input reasoning and
    # fell back on 45% of its turns, which is our ceiling being reported as its
    # incompetence. A harness that cannot let a reasoner finish a sentence is
    # measuring itself.
    MAX_TOKENS = 4000
    # Six, not v0's four. Three more tools means a model may spend rounds
    # curating notes before it gets to play(), and a turn that runs out of rounds
    # falls back -- which would be counted against the model for doing exactly
    # what this version asks of it.
    MAX_ROUNDS = 6
    MEMORY = 6
    TOKEN_BUDGET = 0
    # Attempts after the first, for failures that are worth trying again: rate
    # limits and the 5xx family. Not a nicety once runs go in parallel -- a 429
    # would otherwise be counted as a turn the model failed to answer, which is
    # exactly the column that decides whether a benchmark row means anything.
    RETRIES = 4
    # THE POINT OF THIS VERSION. Notes survive on_start, so they cross from one
    # run into the next; they are reset only by building a new bot, which happens
    # once per pass. A pass is therefore one lifetime of fifty runs.
    CROSS_RUN_MEMORY = True
    NOTES_MAX = 12
    NOTE_CHARS = 160
    # How many finished exchanges travel to the next turn, verbatim. Three because
    # the loop already costs several times a plain chat and this multiplies the
    # request: at three the model sees the shape of what it just tried, and the
    # turns before that are still in the journal as one line each.
    SCRATCH_TURNS = 3
    # The route it means to take through THIS map. Per run, not per turn: the map
    # is visible ahead and a choice closes every other node on its layer forever,
    # which is the condition where deciding in advance beats reacting -- and it is
    # where these models lose, arriving at the second gym under-levelled because of
    # a choice made twenty moves earlier.
    PLAN_CHARS = 300
    EXTRA_TOOLS: list[dict[str, Any]] = []
    STATE_VIEW: Any = "screen"

    def __init__(self, seed: int = 0, endpoint: str | None = None,
                 token: str | None = None, model: str | None = None,
                 verbose: bool = False, **overrides: Any) -> None:
        super().__init__(seed=seed)
        self.endpoint = (endpoint or os.environ.get("FW_ENDPOINT", "")).rstrip("/")
        self.token = token or os.environ.get("FW_TOKEN", "")
        self.model = model or self.MODEL or os.environ.get("MODEL_ID", "")
        if not self.endpoint or not self.token:
            raise LLMConfigError(
                "FW_ENDPOINT and FW_TOKEN environment variables are required\n"
                '  export FW_ENDPOINT="https://..."   # base URL, no /v1\n'
                '  export FW_TOKEN="..."'
            )
        if not self.model:
            raise LLMConfigError(
                f"{type(self).__name__} pins no MODEL, so MODEL_ID is required\n"
                '  export MODEL_ID="gpt-4o-mini"'
            )

        # Per-instance copies of the class settings, so a caller can override one
        # without editing the bot: create("llm-survivor") uses the declared ones,
        # HarnessV3(temperature=0) in a notebook does not.
        self.system = overrides.pop("prompt", None) or self.PROMPT
        self.temperature = overrides.pop("temperature", self.TEMPERATURE)
        self.max_tokens = overrides.pop("max_tokens", self.MAX_TOKENS)
        self.max_rounds = overrides.pop("max_rounds", self.MAX_ROUNDS)
        self.memory = overrides.pop("memory", self.MEMORY)
        # Settable here as well as on the class so an experiment can put four
        # views on the same seeds without four bot folders. A SUBMISSION should
        # still declare it on the class: the fingerprint covers the class, and a
        # row whose view was chosen by the caller does not say what it played.
        self.state_view = overrides.pop("view", None) or self.STATE_VIEW
        self.token_budget = overrides.pop("token_budget", self.TOKEN_BUDGET)
        if overrides:
            raise TypeError(f"unknown settings: {', '.join(sorted(overrides))}")
        self.verbose = verbose or bool(os.environ.get("POKELIKE_VERBOSE"))

        # Checked once, here, rather than discovered fifty runs in. Without
        # `play` there is no way for the model to end a turn, so every turn
        # exhausts its rounds and falls back -- a whole benchmark of our backup
        # heuristic, filed under the model's name, with nothing that looks wrong
        # until you read fallback_rate.
        names = self.tool_names()
        if "play" not in names:
            raise LLMConfigError(
                f"{type(self).__name__}.tools() offers no `play` tool "
                f"({', '.join(names) or 'nothing'}).\n"
                "  It is how the model ends a turn; without it every turn falls back."
            )
        if len(names) != len(set(names)):
            raise LLMConfigError(
                f"{type(self).__name__} declares a tool twice: "
                f"{', '.join(sorted({n for n in names if names.count(n) > 1}))}.\n"
                "  Providers reject a duplicated function name."
            )

        self.calls = 0
        self.turns = 0
        self.tokens_used = 0
        self.tokens_in = 0
        self.tokens_out = 0
        self.retries = 0
        self.fallbacks = 0
        self.journal: list[str] = []
        # The notes. Deliberately NOT cleared by on_start -- see
        # CROSS_RUN_MEMORY. Not called `memory`: that name is taken by v0's
        # journal-trim size, and `_commit` slices the journal with it.
        self.notebook: list[str] = []
        # Per RUN, both of them: the plan is about this map, and the scratchpad is
        # this episode's reasoning. Only the notebook crosses a run boundary.
        self.plan: str = ""
        self.scratch: list[list[dict[str, Any]]] = []
        self._last_why = ""
        # The turn decided in `rearrange`, waiting for `choose` to collect it.
        self._pending: tuple[int | None, int | None, str] | None = None

    # ------------------------------------------------------------------ hooks

    def on_start(self, seed: int) -> None:
        self.seed = seed
        # `journal` is within-run and goes. `memory` is the whole point of v1 and
        # STAYS: it is what the model carries from the last run into this one.
        self.journal = []
        # A new map and a new episode: the route it planned and the exchanges it
        # had are about the run that just ended. The notebook is not.
        self.plan = ""
        self.scratch = []
        self._pending = None
        self.calls = self.turns = self.tokens_used = self.fallbacks = 0
        self.tokens_in = self.tokens_out = self.retries = 0
        self._last_why = ""

    def notes(self) -> dict[str, Any]:
        """Ends up in the run registry, and in the result a benchmark records.

        `fallback_rate` is the honest column of an LLM benchmark. Every fallback
        is a turn the model did not decide, played by the backup heuristic under
        the model's name, so a row with a high one is measuring our heuristic,
        not the model, and should be read as a broken run rather than a bad one.
        """
        return {
            "model": self.model,
            "harness": self.HARNESS,
            "bot": type(self).__name__,
            "calls": self.calls,
            "turns": self.turns,
            "tokens": self.tokens_used,
            "tokens_in": self.tokens_in,
            "tokens_out": self.tokens_out,
            # Transient failures that were retried rather than counted
            # against the model. High means the provider was struggling.
            "retries": self.retries,
            "fallbacks": self.fallbacks,
            # Saved with EVERY run, not just at the end of a pass: the interesting
            # object here is how the notes change, and a single final snapshot
            # cannot show a lesson being learned and then revised away.
            "notebook": list(self.notebook),
            "notes_kept": len(self.notebook),
            # What it committed to on this map, and how much of its own reasoning
            # it was carrying. Both are per run, so both belong in the run's row.
            "plan": self.plan,
            "scratch_turns": len(self.scratch),
            "fallback_rate": round(self.fallbacks / self.turns, 3) if self.turns else 0.0,
            "temperature": self.temperature,
            # False means this bot answers a different question from the others:
            # it gave the model tools they did not have, or took some away.
            "stock_tools": self.tool_names() == _STOCK_TOOL_NAMES,
            # What the model was looking at. Two rows with different views are
            # not answering the same question, any more than two with different
            # tools are.
            "state_view": self.view_name(),
            "reproducible": False,
        }

    def tool_names(self) -> list[str]:
        return [t["function"]["name"] for t in self.tools()]

    def artifacts(self) -> list:
        """What a submission of this bot carries.

        The prompt and the model reference, never the key. An LLM result cannot
        be reproduced exactly (providers change models behind a fixed name and
        sampling is stochastic), so the least we can do is record precisely what
        was asked of which model, under which harness.
        """
        from pokelike.leaderboard import Artifact

        return [
            Artifact(
                name="prompt.md",
                kind="prompt",
                description=f"system prompt, {type(self).__name__}",
                text=self.system,
            ),
            Artifact(
                name="model.json",
                kind="model-ref",
                description="which model answered, and how it was asked",
                data={
                    "model": self.model,
                    "pinned": self.MODEL is not None,
                    "harness": self.HARNESS,
                    "temperature": self.temperature,
                    "max_tokens": self.max_tokens,
                    "max_rounds": self.max_rounds,
                    "memory": self.memory,
                    "scratch_turns": self.SCRATCH_TURNS,
                    "plan_chars": self.PLAN_CHARS,
                    "token_budget": self.token_budget,
                    "tools": self.tool_names(),
                    "stock_tools": self.tool_names() == _STOCK_TOOL_NAMES,
                    "state_view": self.view_name(),
                    "reproducible": False,
                    "why_not": (
                        "providers change models behind a fixed name and sampling is "
                        "stochastic; rerunning this will not give identical results"
                    ),
                },
            ),
        ]

    # --------------------------------------------------------------- decision

    def explain(self) -> str:
        return self._last_why

    def rearrange(self, state: dict[str, Any]) -> tuple[int, int] | None:
        """Who leads, decided in the SAME model call as the move.

        The run loop asks for this before `choose`, so the whole turn is thought
        about once: `_agentic_round` runs here, the chosen action is cached, and
        `choose` returns it without a second request. One HTTP call per turn, and
        the model simply gets one more tool.

        Offered only on the map screen. Elsewhere the options ARE the team (the
        swap screen, the equip modal), so reordering underneath would change what
        an index means between deciding and playing.
        """
        self._pending = None
        if state.get("screen") != "map-screen" or not state.get("can_reorder"):
            return None
        try:
            index, why, lead = self._agentic_round(state, allow_lead=True)
        except LLMConfigError:
            raise
        except Exception:  # noqa: BLE001, handled again and counted in choose
            return None
        team = state.get("team") or []
        if lead is None or not 0 < lead < len(team):
            self._pending = (state.get("steps"), index, why)
            return None
        # Carried into the turn's explanation rather than set here: `choose`
        # overwrites `_last_why` with the move reason, so a lead decision set
        # here was performed and then never shown.
        why = f"lead {team[lead]['name']} | {why}"
        self._pending = (state.get("steps"), index, why)
        return (0, lead)

    def choose(self, state: dict[str, Any]) -> int:
        self.turns += 1
        n = len(state["actions"])
        # Already decided in rearrange, this same turn. `steps` guards it: a
        # cached index must never be replayed against a different turn.
        if self._pending and self._pending[0] == state.get("steps"):
            _, index, why = self._pending
            self._pending = None
            if isinstance(index, int) and 0 <= index < n:
                return self._commit(state, index, why)
        try:
            index, why, _ = self._agentic_round(state)
        except (LLMConfigError, LLMBudgetError):
            # Not recoverable: every later call fails identically, or the run has
            # spent what it was allowed. Better to stop than to quietly hand the
            # rest of the run to the backup heuristic and file it as an LLM run.
            raise
        except Exception as e:  # noqa: BLE001, a transient failure must not end the run
            return self._fall_back(state, f"{type(e).__name__}: {e}"[:80])

        if not isinstance(index, int) or not 0 <= index < n:
            return self._fall_back(state, f"model returned index {index}")
        return self._commit(state, index, why)

    def _commit(self, state: dict[str, Any], index: int, why: str) -> int:
        self._last_why = why
        self.journal.append(self._journal_entry(state, index, why))
        self.journal = self.journal[-self.memory:]
        if self.verbose:
            print(f"   [llm] -> [{index}] {why[:100]}")
        return index

    def _journal_entry(self, state: dict[str, Any], index: int, why: str) -> str:
        """One past turn, with the action separated from the talk about it.

        v0 to v2 recorded `why` alone, the model's own sentence, under a heading
        reading YOUR RECENT MOVES. So a model was handed its own guesses back as a
        record of events: "a second Pokemon matters more than one more fight this
        early" is a plan, and one turn later it reads as a thing that happened.
        Nothing distinguished them and the model had no way to.

        This matters more here than it would have under v0, because v2 added a
        scratchpad: the model now sees its own words from the last three turns
        VERBATIM as well, so there were two channels carrying its reasoning and one
        of them was labelled as fact.

        What was done comes from `state["actions"][index]`, the harness's own data.
        The sentence is kept, because it is how a model notices it has spent five
        turns on one idea; it is just not evidence.
        """
        actions = state.get("actions") or []
        act = actions[index] if 0 <= index < len(actions) else {}
        if act.get("kind") == "node":
            did = f"node {act.get('id', '?')} ({act.get('node', 'node')})"
            if act.get("tooltip"):
                did += f", {act['tooltip']}"
        else:
            did = str(act.get("label") or act.get("id") or "action")
        said = " ".join(str(why or "").split())[:200]
        return (f"step {state.get('steps')}: [{index}] {did}\n"
                f"    it said: {said or '(nothing)'}")

    def _fall_back(self, state: dict[str, Any], reason: str) -> int:
        self.fallbacks += 1
        self._last_why = f"(fell back: {reason})"
        if self.verbose:
            print(f"   [llm] fallback: {reason}")
        return self._fallback(state)

    def _fallback(self, state: dict[str, Any]) -> int:
        """Backup choice when the model does not answer or gets it wrong.

        Not random: it prefers what keeps the team alive, healing first if someone
        is hurt, otherwise widen the team. Override it if your bot would rather
        fail differently, but count on it being used: over fifty runs, something
        times out.
        """
        actions = state["actions"]
        team = state.get("team") or []
        hurt = [p for p in team if p["max_hp"] and p["hp"] / p["max_hp"] < 0.4]

        order = ["pokecenter", "catch", "item"] if hurt else ["catch", "item", "pokecenter"]
        for kind in order:
            for i, a in enumerate(actions):
                if a.get("node") == kind:
                    return i
        return 0

    # ---------------------------------------------------------- agentic loop

    def _agentic_round(self, state: dict[str, Any],
                       allow_lead: bool = False) -> tuple[int, str, int | None]:
        """One turn of thinking. Returns (action index, reason, lead or None)."""
        lead: int | None = None
        # THE CHANGE THAT MAKES v2. v0 and v1 opened a fresh two-message
        # conversation every turn, so whatever the model worked out at turn 12 by
        # reading its team and the exits was gone at turn 13: all that crossed the
        # boundary was six one-line journal entries saying WHAT it chose, never why
        # or what it had seen. Twenty independent decisions glued together, not an
        # agent reasoning about an episode.
        #
        # Now the last SCRATCH_TURNS exchanges come along verbatim, its own words
        # included. Bounded rather than unbounded because the alternative is a
        # request that grows all run and prices itself out -- a loop of this kind
        # already costs several times a plain chat, and the older turns are still
        # summarised in the journal.
        history: list[dict[str, Any]] = [m for turn in self.scratch for m in turn]
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": self.system},
            *history,
            {"role": "user", "content": self._situation(state)},
        ]
        # What this turn adds to the scratchpad, kept apart from `messages` so the
        # system prompt and the older turns are not copied into it again.
        this_turn: list[dict[str, Any]] = [messages[-1]]

        for _ in range(self.max_rounds):
            msg = self._call(messages)
            calls = msg.get("tool_calls") or []
            if not calls:
                # No tool: maybe it wrote the index out in prose.
                index = self._index_from_text(msg.get("content") or "", len(state["actions"]))
                if index is not None:
                    return index, "(read from prose)", lead
                raise LLMError("the model called no tool")

            spoke = {"role": "assistant", "content": msg.get("content") or "",
                     "tool_calls": calls}
            messages.append(spoke)
            this_turn.append(spoke)

            for c in calls:
                name = c["function"]["name"]
                try:
                    args = json.loads(c["function"].get("arguments") or "{}")
                except json.JSONDecodeError:
                    args = {}

                if name == "play":
                    # The turn ends, so its exchange joins the scratchpad -- with
                    # the play call in it, because "I chose 2 and here is why" is
                    # the most useful line the next turn can read.
                    self._remember_turn(this_turn)
                    return args.get("index"), str(args.get("why", "")), lead

                if name == "set_lead":
                    # Recorded, not applied here: the bot has no handle on the
                    # game, and the run loop is what performs the swap. Kept even
                    # when not allowed, so the model gets told why rather than
                    # silently ignored.
                    want = args.get("index")
                    if allow_lead and isinstance(want, int):
                        lead = want
                        reply = f"ok, slot {want} will lead. Now call play()."
                    else:
                        reply = ("not available on this screen: the options here are "
                                 "your team, so reordering would change what an index "
                                 "means. Call play().")
                    answer = {"role": "tool", "tool_call_id": c["id"], "content": reply}
                    messages.append(answer)
                    this_turn.append(answer)
                    continue

                answer = {"role": "tool", "tool_call_id": c["id"],
                          "content": self.run_tool(name, args, state)}
                messages.append(answer)
                this_turn.append(answer)

        # Rounds exhausted: the turn is lost to the fallback, and its exchange is
        # kept anyway. A turn that ran out of ideas is exactly what the next turn
        # should be able to see, rather than repeating it.
        self._remember_turn(this_turn)
        raise LLMError(f"no call to play() within {self.max_rounds} rounds")

    def _remember_turn(self, turn: list[dict[str, Any]]) -> None:
        """Adds one finished exchange to the scratchpad, oldest dropped first.

        The screen it was looking at is replaced by one line before the turn is
        kept, and that line is most of what makes this version affordable. Measured
        on three seeds with the whole turn kept: 269k input tokens for ONE run
        against 41k under v0 -- six and a half times, because every kept turn
        dragged another full render of team, map and actions along with it. Four
        copies of the screen in a request, and the model's own reasoning, which is
        the entire point of the scratchpad, as the crumbs.

        It is also wrong on its own terms and not merely dear. A stale screen
        invites the model to reason about a map that has already changed, while the
        CURRENT one is right there in the fresh user message. What cannot be
        reconstructed from anywhere else is what it said and what the tools told it.
        That is what stays.
        """
        kept = [
            {"role": "user",
             "content": "[the screen you were shown that turn, since changed]"}
            if m.get("role") == "user" else m
            for m in turn
        ]
        self.scratch.append(kept)
        self.scratch = self.scratch[-self.SCRATCH_TURNS:] if self.SCRATCH_TURNS else []

    # ------------------------------------------------------------------ tools

    def tools(self) -> list[dict[str, Any]]:
        """The tools this bot offers the model, in OpenAI function-calling form.

        The shared eight plus whatever `EXTRA_TOOLS` declares. Override to drop
        or replace them, but `play` has to survive: it is how a turn ends, and
        a model with no way to end the turn falls back on every single one.
        """
        return [*TOOLS, *self.EXTRA_TOOLS]

    def run_tool(self, name: str, args: dict[str, Any], state: dict[str, Any]) -> str:
        """Answers one tool call. Whatever this returns is shown to the model.

        Override for your own tools and call `super()` for the shared ones. An
        unknown name gets a message rather than an exception: a model that
        invents a tool should be told so and allowed to carry on, not have the
        turn thrown away and played by the fallback.
        """
        if name == "team_details":
            return render.team_view(state.get("team")) or "(empty team)"
        if name == "what_lies_ahead":
            return self._exits(state)
        if name in ("remember", "revise", "forget"):
            return self._remember(name, args)

        if name == "plan":
            # Truncated rather than refused, like a note: a plan cut to 300
            # characters is still a plan, an error message is a wasted round.
            route = str(args.get("route") or "").strip().replace("\n", " ")
            if not route:
                return "nothing to plan: `route` was empty."
            had, self.plan = bool(self.plan), route[: self.PLAN_CHARS]
            return (("plan replaced. " if had else "plan noted. ")
                    + "You will see it every turn until you change it.")
        return f"unknown tool: {name}"

    # --------------------------------------------------------------- memory

    def _remember(self, verb: str, args: dict[str, Any]) -> str:
        """The three memory verbs. Every answer states the cap, on purpose.

        A model that cannot see how full its notes are will keep calling
        `remember` and be silently refused, then behave as though the lesson were
        saved. Telling it the count every time makes `revise` and `forget` visibly
        useful rather than decorative.

        Notes are truncated rather than rejected for being long: a lesson cut to
        160 characters is still a lesson, while an error message is a wasted round.
        """
        note = str(args.get("note") or "").strip().replace("\n", " ")
        note = note[: self.NOTE_CHARS]

        if verb == "remember":
            if not note:
                return "nothing to remember: `note` was empty."
            if len(self.notebook) >= self.NOTES_MAX:
                return (f"your notes are full ({self.NOTES_MAX}). Use `revise` to "
                        f"improve one or `forget` to make room, then try again.")
            self.notebook.append(note)
            return (f"noted as [{len(self.notebook)}]. "
                    f"{len(self.notebook)}/{self.NOTES_MAX} notes used.")

        # revise and forget both address a note by the number the model was shown,
        # which is 1-based. An out-of-range id is answered rather than raised: the
        # model should be told and carry on, not lose the turn to the fallback.
        try:
            i = int(args.get("id"))
        except (TypeError, ValueError):
            return f"`id` must be a number between 1 and {len(self.notebook)}."
        if not 1 <= i <= len(self.notebook):
            return (f"there is no note [{i}]. You have {len(self.notebook)}: "
                    f"use a number between 1 and {len(self.notebook)}.")

        if verb == "forget":
            gone = self.notebook.pop(i - 1)
            return (f"forgotten: {gone[:60]}. "
                    f"{len(self.notebook)}/{self.NOTES_MAX} notes used, and they have "
                    f"been renumbered.")
        if not note:
            return "nothing to revise it to: `note` was empty."
        self.notebook[i - 1] = note
        return f"note [{i}] rewritten. {len(self.notebook)}/{self.NOTES_MAX} notes used."

    def _memory_block(self) -> list[str]:
        """The notes as the model sees them: numbered, so it can revise and forget.

        Numbered from 1 because the ids appear in prose the model reads back, and
        an off-by-one between what it is shown and what the tool accepts would look
        to it like the tool being broken.
        """
        if not self.notebook:
            return ["", "WHAT YOU HAVE LEARNED SO FAR: nothing yet. Use `remember` "
                    "when you learn something that will still be true next run."]
        return ["", f"WHAT YOU HAVE LEARNED (kept across runs, "
                    f"{len(self.notebook)}/{self.NOTES_MAX}):",
                *(f"  [{i}] {n}" for i, n in enumerate(self.notebook, 1))]

    def _plan_block(self) -> list[str]:
        """The route it committed to, or the invitation to commit to one.

        Shown every turn on purpose. A plan the model has to be asked for is a plan
        it forgets; a plan in front of it is one it can notice itself breaking.
        """
        if not self.plan:
            return ["", "YOUR PLAN FOR THIS MAP: none yet. Use `plan` to write the "
                    "route you mean to take, before the first choice closes options "
                    "you wanted."]
        return ["", f"YOUR PLAN FOR THIS MAP (yours, change it with `plan`): "
                    f"{self.plan}"]

    # ---------------------------------------------------------------- context

    def view(self, state: dict[str, Any]) -> str:
        """What the model reads each turn. THE hook for changing that.

        Reads `STATE_VIEW` (or whatever was passed as `view=`). Override it
        outright for anything the four settings do not cover -- the harness adds
        the journal and the instruction line around whatever this returns, so
        replacing it wholesale cannot silently cost the bot its memory or leave
        the model without the range of legal indices. That was the shape of the
        old private `_situation`, where the thing you wanted to change and the
        plumbing you must not break lived in one method.
        """
        spec = self.state_view
        if isinstance(spec, str) and spec == "screen":
            return render.screen(state)
        if isinstance(spec, str) and spec in ("json", "both"):
            raw = json.dumps(state, separators=(",", ":"))
            if spec == "json":
                return raw
            return f"{render.screen(state)}\n\nTHE SAME STATE, IN FULL:\n{raw}"
        if isinstance(spec, (list, tuple)):
            missing = [k for k in spec if k not in state]
            if missing:
                # Not an error: a key can be absent on one screen and present on
                # the next -- `map` is gone during a battle. Saying so beats a
                # view that quietly shrinks and a run that gets worse for reasons
                # nobody can see.
                if self.verbose:
                    print(f"   [llm] STATE_VIEW: no {', '.join(missing)} on this screen")
            return json.dumps({k: state[k] for k in spec if k in state},
                              separators=(",", ":"))
        raise LLMConfigError(
            f"STATE_VIEW is {spec!r}. Use 'screen', 'json', 'both', a list of "
            f"state keys, or override view(state) yourself."
        )

    def view_name(self) -> str:
        """What to record: the setting, or 'custom' if `view` was replaced."""
        if type(self).view is not HarnessV3.view:
            return "custom"
        return self.state_view if isinstance(self.state_view, str) else \
            "keys:" + ",".join(self.state_view)

    def _situation(self, state: dict[str, Any]) -> str:
        """The whole user message: the view, plus what the harness owns.

        Deliberately not the hook. The journal is what stops a bot walking the
        same loop forever, and the instruction line is what tells the model how
        many options there are -- neither is a choice a bot should be able to
        drop by accident while changing something else.
        """
        parts = [self.view(state)]
        # Before the journal: what was learned across runs outranks what happened
        # in the last six turns of this one.
        parts += self._memory_block()
        parts += self._plan_block()
        if self.journal:
            parts += [
                "",
                "WHAT YOU DID, AND WHAT YOU SAID AT THE TIME.",
                "The action on each first line is the game's record. The sentence "
                "under it is your own from that turn: it is what you meant to do, "
                "not something that has been verified since.",
                *(f"  {r}" for r in self.journal),
            ]
        parts += [
            "",
            f"Pick an index between 0 and {len(state['actions']) - 1} and call play().",
        ]
        return "\n".join(parts)

    def _exits(self, state: dict[str, Any]) -> str:
        """Where each legal action leads, by reading the map's edges."""
        m = state.get("map")
        if not m:
            return "You are not on the map: this choice opens or closes no paths."
        by_id = {n["id"]: n for n in m["nodes"]}
        rows = []
        for i, a in enumerate(state["actions"]):
            if a.get("kind") != "node":
                rows.append(f"  [{i}] {a.get('label', '')[:60]}")
                continue
            after = [by_id[t]["kind"] for f, t in m["edges"] if f == a["id"] and t in by_id]
            follows = ", ".join(sorted(after)) if after else "nothing (end of map)"
            rows.append(f"  [{i}] {a['node']:<12} -> leads to: {follows}")
        return "Exits on the next layer:\n" + "\n".join(rows)

    # ------------------------------------------------------------------- HTTP

    def _call(self, messages: list[dict[str, Any]]) -> dict[str, Any]:
        if self.token_budget and self.tokens_used >= self.token_budget:
            raise LLMBudgetError(
                f"run spent {self.tokens_used} tokens, budget is {self.token_budget}"
            )
        body = json.dumps({
            "model": self.model,
            "messages": messages,
            "tools": self.tools(),
            "tool_choice": "auto",
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
            # Best effort only. Providers that honour it get closer to repeatable
            # runs; most ignore it, and none of them promise it. Nothing here
            # depends on it working. See `reproducible: False` in the artifacts.
            "seed": self.seed,
        }).encode("utf-8")

        req = urllib.request.Request(
            f"{self.endpoint}/v1/chat/completions",
            data=body,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Content-Type": "application/json",
            },
        )
        # Retried, with backoff, for the failures that are transient. A rate limit
        # is not the model failing to answer: counted as a fallback it would show
        # up as the model being bad at the game, and it is the first thing that
        # happens when runs go in parallel.
        #
        # Auth and model-not-found are NOT retried -- they fail identically
        # forever, so trying again just wastes the run more slowly.
        answer: dict[str, Any] | None = None
        for attempt in range(self.RETRIES + 1):
            try:
                with urllib.request.urlopen(req, timeout=180) as r:
                    answer = json.loads(r.read())
                break
            except urllib.error.HTTPError as e:
                detail = e.read()[:300].decode("utf-8", "replace")
                if e.code in (401, 403):
                    raise LLMConfigError(
                        f"HTTP {e.code} from {self.endpoint}: the endpoint rejected the "
                        f"token.\n  Check FW_TOKEN, a placeholder left in place looks "
                        f"exactly like this.\n  {detail}"
                    ) from e
                if e.code == 404:
                    raise LLMConfigError(
                        f"HTTP 404 from {self.endpoint}/v1/chat/completions.\n"
                        f"  Either the endpoint is not an OpenAI-compatible API, or it "
                        f"does not serve MODEL_ID={self.model!r}.\n  {detail}"
                    ) from e
                if e.code in (408, 409, 425, 429, 500, 502, 503, 504) \
                        and attempt < self.RETRIES:
                    self.retries += 1
                    time.sleep(min(2 ** attempt, 30) + random.random())
                    continue
                raise LLMError(f"HTTP {e.code}: {detail}") from e
            except Exception as e:  # network, timeout, malformed JSON
                if attempt < self.RETRIES:
                    self.retries += 1
                    time.sleep(min(2 ** attempt, 30) + random.random())
                    continue
                raise LLMError(f"{type(e).__name__}: {e}") from e
        if answer is None:
            raise LLMError("no answer after retries")

        self.calls += 1
        usage = answer.get("usage") or {}
        # Split, not just the total. Input and output are priced differently --
        # output several times higher -- so a single total cannot be turned into
        # money afterwards, and a model that thinks in long answers costs quite
        # unlike one that reads a long prompt. Kept as counts and nothing else:
        # prices change, and a measurement should not go stale because a provider
        # ran a promotion. Cost is a function of these two numbers applied later.
        self.tokens_in += usage.get("prompt_tokens", 0)
        self.tokens_out += usage.get("completion_tokens", 0)
        self.tokens_used += usage.get(
            "total_tokens",
            usage.get("prompt_tokens", 0) + usage.get("completion_tokens", 0),
        )
        choices = answer.get("choices") or []
        if not choices:
            raise LLMError("response had no choices")
        return choices[0].get("message") or {}

    @staticmethod
    def _index_from_text(text: str, n: int) -> int | None:
        """Last resort: fish a valid index out of a prose answer."""
        import re

        for m in re.finditer(r"\[?(\d+)\]?", text):
            v = int(m.group(1))
            if 0 <= v < n:
                return v
        return None
